
(function(){
  const KEY='belavados_living_map_site_state_v2';
  const B=window.BELAVADOS=window.BELAVADOS||{};
  B.key=KEY;
  B.data=window.BELAVADOS_DATA||{content:{},visitable_locations:{},settlement_assignments:[]};
  B.state=null;
  B.listeners=[];
  B.onChange=function(fn){B.listeners.push(fn)};
  B.emit=function(){B.listeners.forEach(fn=>{try{fn(B.state)}catch(e){console.error(e)}})};
  B.$=(id)=>document.getElementById(id);
  B.escape=function(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))};
  B.slug=function(s){return String(s||'item').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/gi,'-').replace(/^-+|-+$/g,'').toLowerCase()||'item'};
  B.uid=function(prefix){return (prefix||'id')+'_'+Math.random().toString(36).slice(2,10)+'_'+Date.now().toString(36)};
  B.hash=function(str){let h=2166136261>>>0; for(let i=0;i<String(str).length;i++){h^=str.charCodeAt(i); h=Math.imul(h,16777619)} return h>>>0};
  B.rng=function(seed){let a=B.hash(seed||'Belavados'); return function(){a+=0x6D2B79F5; let t=a; t=Math.imul(t^t>>>15,t|1); t^=t+Math.imul(t^t>>>7,t|61); return ((t^t>>>14)>>>0)/4294967296}};
  B.pick=function(arr,r=Math.random){return arr&&arr.length?arr[Math.floor(r()*arr.length)]:undefined};
  B.sample=function(arr,n,r=Math.random){const copy=[...(arr||[])],out=[]; while(copy.length&&out.length<n){out.push(copy.splice(Math.floor(r()*copy.length),1)[0])} return out};
  B.timeToMin=function(t){const [h,m]=String(t).split(':').map(Number); return (h||0)*60+(m||0)};
  B.nowMinutes=function(d){return d.getHours()*60+d.getMinutes()+d.getSeconds()/60};
  B.fmtTime=function(d){return d.toLocaleString([], {weekday:'short', month:'short', day:'numeric', hour:'2-digit', minute:'2-digit', second:'2-digit'});};
  B.setStatus=function(msg){const el=B.$('statusLine'); if(el) el.textContent=msg};
  B.flattenRaces=function(){const cats=B.data.content?.race_categories||{}; const out=[]; Object.entries(cats).forEach(([category,items])=>(items||[]).forEach(r=>out.push({category,race:r}))); return out};
  B.categoryOfType=function(type){const cats=B.data.visitable_locations?.master_location_categories||{}; for(const [cat,types] of Object.entries(cats)){if((types||[]).map(x=>x.toLowerCase()).includes(String(type).toLowerCase())) return cat} return 'Homes, Social Life, and Leisure'};
  B.allLocationTypes=function(){const cats=B.data.visitable_locations?.master_location_categories||{}; const out=[]; Object.entries(cats).forEach(([category,items])=>(items||[]).forEach(type=>out.push({category,type}))); return out};
  B.provinceNames=function(){return (B.data.settlement_assignments||[]).map(p=>p.province)};
  B.settlementsForProvince=function(province){const row=(B.data.settlement_assignments||[]).find(p=>p.province===province); if(!row)return[]; return [...(row.capital_cities||[]),...(row.cities||[]),...(row.towns||[]),...(row.villages||[])];};
  B.randomSettlementElsewhere=function(r=Math.random,currentProvince){const provinces=(B.data.settlement_assignments||[]).filter(p=>p.province!==currentProvince); const p=B.pick(provinces,r)||B.pick(B.data.settlement_assignments||[],r)||{}; const s=B.pick([...(p.capital_cities||[]),...(p.cities||[]),...(p.towns||[]),...(p.villages||[])],r)||'unlisted settlement'; return {province:p.province||'Unknown Province',settlement:s};};
  B.defaultState=function(){return {version:2,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),seed:'Belavados-'+new Date().toISOString().slice(0,10),settlement:{province:'Aelvanyr',name:'Mythraelyn',type:'Capital City',biome:'Coastal River',government:'Participatory Democracy',tags:'living map, transit hub, generated NPC simulation',locationTarget:72,npcTarget:120},svg:{name:'',source:'',anchors:[]},locations:[],npcs:[],households:[],selected:{npcId:null,locationId:null,householdId:null},clock:{live:true,pausedAt:null,manualISO:null},log:[]}};
  B.load=function(){try{const raw=window.localStorage?localStorage.getItem(KEY):null; B.state=raw?JSON.parse(raw):B.defaultState()}catch(e){console.warn(e); B.state=B.defaultState()} B.normalizeState(); return B.state};
  B.normalizeState=function(){const s=B.state||(B.state=B.defaultState()); s.settlement=s.settlement||{}; s.locations=s.locations||[]; s.npcs=s.npcs||[]; s.households=s.households||[]; s.selected=s.selected||{}; s.svg=s.svg||{name:'',source:'',anchors:[]}; return s};
  B.save=function(){B.normalizeState(); B.state.updatedAt=new Date().toISOString(); try{if(window.localStorage)localStorage.setItem(KEY,JSON.stringify(B.state));}catch(e){console.warn('Belavadös save failed; continuing without browser storage.',e);} B.emit(); return B.state};
  B.reset=function(){B.state=B.defaultState(); B.save()};
  B.exportJSON=function(){B.normalizeState(); const blob=new Blob([JSON.stringify(B.state,null,2)],{type:'application/json'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=B.slug(B.state.settlement?.name||'belavados-settlement')+'_living_site_state.json'; document.body&&document.body.appendChild&&document.body.appendChild(a); a.click(); a.remove&&a.remove(); setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
  B.importJSONFile=function(file){return new Promise((resolve,reject)=>{const reader=new FileReader(); reader.onload=()=>{try{B.state=JSON.parse(reader.result); B.normalizeState(); B.save(); resolve(B.state)}catch(e){reject(e)}}; reader.onerror=reject; reader.readAsText(file)})};
  B.downloadText=function(filename,text,type='text/plain'){const blob=new Blob([text],{type}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=filename; document.body&&document.body.appendChild&&document.body.appendChild(a); a.click(); a.remove&&a.remove(); setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
  B.describeState=function(){const s=B.state||B.defaultState(); return `${s.settlement?.name||'Settlement'} in ${s.settlement?.province||'Province'}: ${s.locations?.length||0} locations, ${s.npcs?.length||0} NPCs, ${s.households?.length||0} households.`};
})();

/* Belavadös compatibility/export/import helpers — additive patch, preserves the existing generator modules. */
(function(){
  'use strict';
  const B=window.BELAVADOS=window.BELAVADOS||{}; if(!B) return;
  const enc=new TextEncoder();
  B.$$=B.$$||((sel,root=document)=>Array.from(root.querySelectorAll(sel)));
  B.stripTags=B.stripTags||function(s){return String(s??'').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();};
  B.safeName=B.safeName||function(value,opt={}){
    let s=String(value||'Belavados').trim().normalize('NFKD').replace(/[\u0300-\u036f]/g,'');
    s=s.replace(/['’`´]/g,'').replace(/[‐‑‒–—-]/g,'');
    if(opt.firstWord) s=(s.split(/\s+/)[0]||s);
    s=s.replace(/[^A-Za-z0-9_\s]/g,'').trim();
    s=opt.joinWords?s.replace(/\s+/g,''):s.replace(/\s+/g,'_');
    return s||'Belavados';
  };
  B.settlementFileStem=B.settlementFileStem||function(settlement,province){return `${B.safeName(settlement,{firstWord:true,joinWords:true})}_${B.safeName(province,{joinWords:true})}`;};
  const oldNormalize=B.normalizeState;
  B.normalizeState=function(){
    const s=oldNormalize?oldNormalize.call(B):(B.state=B.state||{});
    s.world=s.world||{settlements:[],travelNetworks:[],transportationNetworks:[],relationshipNetworks:[]};
    ['settlements','travelNetworks','transportationNetworks','relationshipNetworks'].forEach(k=>s.world[k]=Array.isArray(s.world[k])?s.world[k]:[]);
    s.imports=s.imports||{pending:[],committed:[]};
    s.imports.pending=Array.isArray(s.imports.pending)?s.imports.pending:[];
    s.imports.committed=Array.isArray(s.imports.committed)?s.imports.committed:[];
    s.settlement=s.settlement||{};
    s.settlement.dangerLevel=s.settlement.dangerLevel||'Moderate';
    s.settlement.alignmentPreference=s.settlement.alignmentPreference||'Balanced / civic cooperation';
    return s;
  };
  const oldLoad=B.load;
  B.load=function(){const s=oldLoad?oldLoad.call(B):(B.state=B.defaultState?B.defaultState():{}); B.normalizeState(); return s;};
  const oldSave=B.save;
  B.save=function(){B.normalizeState(); if(oldSave) return oldSave.call(B); try{if(window.localStorage)localStorage.setItem(B.key||'belavados_living_map_site_state_v2',JSON.stringify(B.state));}catch(e){console.warn('Belavadös save failed; continuing without browser storage.',e);} B.emit&&B.emit(); return B.state;};
  B.log=B.log||function(msg){B.normalizeState(); B.state.log=B.state.log||[]; B.state.log.unshift({at:new Date().toISOString(),message:String(msg)}); B.state.log=B.state.log.slice(0,100);};
  B.downloadBlob=B.downloadBlob||function(filename,blob){const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=filename; document.body&&document.body.appendChild&&document.body.appendChild(a); a.click(); a.remove&&a.remove(); setTimeout(()=>URL.revokeObjectURL(a.href),1200);};
  const oldDownloadText=B.downloadText;
  B.downloadText=function(filename,text,type='text/plain'){ if(B.downloadBlob) return B.downloadBlob(filename,new Blob([text],{type})); return oldDownloadText&&oldDownloadText(filename,text,type); };
  B.toGeoJSON=function(){B.normalizeState(); return {type:'FeatureCollection',name:B.state.settlement?.name||'Belavadös settlement',features:(B.state.locations||[]).map(l=>({type:'Feature',id:l.id,geometry:{type:'Point',coordinates:[Number(l.x||0),Number(l.y||0)]},properties:{name:l.name,category:l.category,type:l.type,use:l.use,settlement:B.state.settlement?.name,province:B.state.settlement?.province,items:l.inventory||[],services:l.services||[],prices:l.prices||[],employees:l.employees||[],visitors:l.visitors||[],residents:l.residents||[]}}))};};
  B.exportGeoJSON=function(){B.downloadText(B.settlementFileStem(B.state.settlement?.name,B.state.settlement?.province)+'.geojson',JSON.stringify(B.toGeoJSON(),null,2),'application/geo+json');};
  function xmlEscape(s){return String(s??'').replace(/[<>&'"]/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;',"'":'&apos;','"':'&quot;'}[c]));}
  function crcTable(){let t=[]; for(let n=0;n<256;n++){let c=n; for(let k=0;k<8;k++) c=(c&1)?(0xEDB88320^(c>>>1)):(c>>>1); t[n]=c>>>0;} return t;}
  const table=crcTable();
  function bytes(data){ if(data instanceof Uint8Array)return data; if(data instanceof ArrayBuffer)return new Uint8Array(data); return enc.encode(String(data??'')); }
  function crc32Bytes(arr){let crc=-1; for(const b of arr) crc=(crc>>>8)^table[(crc^b)&0xff]; return (crc^(-1))>>>0;}
  function u16(n){return [n&255,(n>>>8)&255];} function u32(n){return [n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255];}
  function concat(parts){const len=parts.reduce((a,p)=>a+p.length,0); const out=new Uint8Array(len); let o=0; parts.forEach(p=>{out.set(p,o); o+=p.length;}); return out;}
  B.createZipBytes=function(files){let offset=0; const locals=[],centrals=[]; files.forEach(file=>{const nameBytes=enc.encode(String(file.name||'file').replace(/^\/+/,'')); const dataBytes=bytes(file.data); const crc=crc32Bytes(dataBytes); const local=concat([enc.encode('PK\x03\x04'),new Uint8Array([...u16(20),...u16(0),...u16(0),...u16(0),...u16(0),...u32(crc),...u32(dataBytes.length),...u32(dataBytes.length),...u16(nameBytes.length),...u16(0)]),nameBytes,dataBytes]); locals.push(local); const central=concat([enc.encode('PK\x01\x02'),new Uint8Array([...u16(20),...u16(20),...u16(0),...u16(0),...u16(0),...u16(0),...u32(crc),...u32(dataBytes.length),...u32(dataBytes.length),...u16(nameBytes.length),...u16(0),...u16(0),...u16(0),...u16(0),...u32(0),...u32(offset)]),nameBytes]); centrals.push(central); offset+=local.length;}); const central=concat(centrals), local=concat(locals); const end=concat([enc.encode('PK\x05\x06'),new Uint8Array([...u16(0),...u16(0),...u16(files.length),...u16(files.length),...u32(central.length),...u32(local.length),...u16(0)])]); return concat([local,central,end]);};
  B.createZipBlob=function(files){return new Blob([B.createZipBytes(files)],{type:'application/zip'});};
  B.snapshotHTML=function(){B.normalizeState(); const state=JSON.stringify(B.state).replace(/<\//g,'<\\/'); const title=`${B.state.settlement?.name||'Belavadös'} Player Snapshot`; const css=`body{margin:0;background:#061018;color:#ecffff;font-family:system-ui,Segoe UI,Arial,sans-serif}main{max-width:1200px;margin:auto;padding:24px}.card{border:1px solid rgba(0,255,255,.28);border-radius:16px;background:rgba(0,0,0,.32);padding:16px;margin:12px 0}.tags{display:flex;flex-wrap:wrap;gap:6px}.tag{border:1px solid rgba(0,255,255,.35);border-radius:999px;padding:4px 8px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:12px}`; return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${xmlEscape(title)}</title><style>${css}</style></head><body><main><h1>${xmlEscape(title)}</h1><p>${xmlEscape(B.describeState?B.describeState():'Exported Belavadös settlement')}</p><section class="card"><h2>Settlement</h2><pre id="overview"></pre></section><section class="grid"><div class="card"><h2>Locations</h2><div id="locations"></div></div><div class="card"><h2>NPCs</h2><div id="npcs"></div></div></section><script id="belavados-state" type="application/json">${state}</script><script>const S=JSON.parse(document.getElementById('belavados-state').textContent);const e=s=>String(s??'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));overview.textContent=JSON.stringify(S.settlement,null,2);locations.innerHTML=(S.locations||[]).map(l=>'<article><h3>'+e(l.name)+'</h3><p>'+e(l.type)+' · '+e(l.category)+'</p><div class="tags">'+[...(l.inventory||[]),...(l.services||[])].slice(0,18).map(x=>'<span class="tag">'+e(x)+'</span>').join('')+'</div></article>').join('');npcs.innerHTML=(S.npcs||[]).map(n=>'<article><h3>'+e(n.name)+'</h3><p>'+e(n.race)+' · '+e(n.genderIdentity)+' · '+e(n.pronouns)+'</p><p>'+e(n.job||'')+'</p></article>').join('');<\/script></main></body></html>`;};
  B.exportHTML=function(){B.downloadText(B.settlementFileStem(B.state.settlement?.name,B.state.settlement?.province)+'.html',B.snapshotHTML(),'text/html');};
  B.docxFiles=function(){B.normalizeState(); const s=B.state; const para=t=>`<w:p><w:r><w:t>${xmlEscape(t)}</w:t></w:r></w:p>`; const body=[para(`${s.settlement?.name||'Settlement'} — ${s.settlement?.province||'Province'}`),para(`Type: ${s.settlement?.type||''}`),para(`Government: ${s.settlement?.government||''}`),para(`Tags: ${s.settlement?.tags||''}`),para(`Locations: ${(s.locations||[]).length}`),...(s.locations||[]).slice(0,120).map(l=>para(`${l.name} — ${l.type}; items/services: ${[...(l.inventory||[]),...(l.services||[])].slice(0,12).join(', ')}`)),para(`NPCs: ${(s.npcs||[]).length}`),...(s.npcs||[]).slice(0,160).map(n=>para(`${n.name} — ${n.race}; ${n.genderIdentity}; ${n.pronouns}; ${n.job||''}; home ${n.homeLocationName||''}; work ${n.workLocationName||''}`))].join(''); return [{name:'[Content_Types].xml',data:'<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>'},{name:'_rels/.rels',data:'<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>'},{name:'word/document.xml',data:`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${body}<w:sectPr><w:pgSz w:w="12240" w:h="15840"/><w:pgMar w:top="720" w:right="720" w:bottom="720" w:left="720"/></w:sectPr></w:body></w:document>`}];};
  B.exportDOCX=function(){B.downloadBlob(B.settlementFileStem(B.state.settlement?.name,B.state.settlement?.province)+'.docx',new Blob([B.createZipBytes(B.docxFiles())],{type:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'}));};
  B.exportZIP=function(){B.normalizeState(); const stem=B.settlementFileStem(B.state.settlement?.name,B.state.settlement?.province); const zipName=B.safeName(B.state.settlement?.name,{firstWord:true,joinWords:true})+'.zip'; const files=[{name:`${stem}.html`,data:B.snapshotHTML()},{name:`${stem}.json`,data:JSON.stringify(B.state,null,2)},{name:`${stem}.geojson`,data:JSON.stringify(B.toGeoJSON(),null,2)},{name:`${stem}.docx`,data:B.createZipBytes(B.docxFiles())},{name:'generator/site.css',data:'/* CSS is embedded inside the exported HTML snapshot. */'},{name:'generator/embedded.js',data:'// JavaScript is embedded inside the exported HTML snapshot.'},{name:'README.txt',data:`Belavadös export for ${B.state.settlement?.name||'Settlement'}.\nHTML, JSON, GeoJSON, DOCX, embedded CSS, and embedded JavaScript placeholder files are included.\n`}]; B.downloadBlob(zipName,B.createZipBlob(files));};
  B.extractStateFromHTML=function(text){const m=String(text).match(/<script[^>]+id=["']belavados-state["'][^>]*>([\s\S]*?)<\/script>/i); if(m){const t=document.createElement('textarea'); t.innerHTML=m[1]; return JSON.parse(t.value||m[1]);} const j=String(text).match(/\{[\s\S]*"locations"[\s\S]*"npcs"[\s\S]*\}/); if(j) return JSON.parse(j[0]); throw new Error('No embedded Belavadös state found in HTML.');};
  B.queueImport=function(payload,sourceName,type){B.normalizeState(); B.state.imports.pending.push({id:B.uid?B.uid('import'):'import_'+Date.now(),type,sourceName,importedAt:new Date().toISOString(),payload}); B.log(`Queued ${sourceName} for world commit.`); B.save();};
  B.importFiles=async function(files){const list=Array.from(files||[]), results=[]; for(const file of list){const name=file.name||'import'; const ext=(name.split('.').pop()||'').toLowerCase(); if(ext==='json'||ext==='geojson'){const text=await file.text(); const data=JSON.parse(text); B.queueImport(data,name,ext); results.push(data);} else if(ext==='html'){const text=await file.text(); const state=B.extractStateFromHTML(text); B.queueImport(state,name,'html'); results.push(state);} else if(ext==='docx'){B.queueImport({filename:name,size:file.size,preview:`DOCX artifact imported for lore/reference: ${name}`},name,'docx'); results.push(name);} else {const text=await file.text(); B.queueImport({filename:name,text:text.slice(0,25000)},name,'text'); results.push(name);} } return results;};
  B.commitImports=function(){B.normalizeState(); const pending=[...(B.state.imports.pending||[])]; let addedLocations=0, addedNpcs=0, addedSettlements=0; const locIds=new Set((B.state.locations||[]).map(l=>l.id)); const npcIds=new Set((B.state.npcs||[]).map(n=>n.id)); pending.forEach(item=>{const p=item.payload||{}; if((item.type==='geojson'||p.type==='FeatureCollection')&&Array.isArray(p.features)){(p.features||[]).forEach((f,i)=>{const prop=f.properties||{}; const id=prop.id||f.id||(B.uid?B.uid('geo_loc'):'geo_'+Date.now()+i); if(locIds.has(id))return; const coords=f.geometry?.coordinates||[50,50]; B.state.locations.push({id,name:prop.name||`Imported location ${i+1}`,type:prop.type||'imported location',category:prop.category||'Imported',x:Number(coords[0]||50),y:Number(coords[1]||50),inventory:prop.items||[],services:prop.services||[],prices:prop.prices||[],employees:[],visitors:[],residents:[],notes:`Imported from ${item.sourceName}`}); locIds.add(id); addedLocations++;});} else if(p.locations||p.npcs||p.settlement){if(p.settlement){B.state.world.settlements.push({id:B.uid?B.uid('world_settlement'):'world_'+Date.now(),source:item.sourceName,committedAt:new Date().toISOString(),settlement:p.settlement,locationCount:(p.locations||[]).length,npcCount:(p.npcs||[]).length}); addedSettlements++;} (p.locations||[]).forEach(l=>{const id=l.id||(B.uid?B.uid('loc'):'loc_'+Date.now()); if(locIds.has(id))return; B.state.locations.push(Object.assign({},l,{id,importedFrom:item.sourceName})); locIds.add(id); addedLocations++;}); (p.npcs||[]).forEach(n=>{const id=n.id||(B.uid?B.uid('npc'):'npc_'+Date.now()); if(npcIds.has(id))return; B.state.npcs.push(Object.assign({},n,{id,importedFrom:item.sourceName})); npcIds.add(id); addedNpcs++;}); if(Array.isArray(p.households)) B.state.households.push(...p.households.filter(h=>h&&h.id)); if(p.world){['travelNetworks','transportationNetworks','relationshipNetworks'].forEach(k=>{if(Array.isArray(p.world[k]))B.state.world[k].push(...p.world[k]);});}} else {B.state.world.settlements.push({id:B.uid?B.uid('artifact'):'artifact_'+Date.now(),source:item.sourceName,type:item.type,artifact:p,committedAt:new Date().toISOString()}); addedSettlements++;} B.state.imports.committed.push(Object.assign({},item,{committedAt:new Date().toISOString()}));}); B.state.imports.pending=[]; if(B.rebuildIndexes)B.rebuildIndexes(); if(B.enrichLivingStructure)B.enrichLivingStructure(); B.log(`Committed imports: ${addedSettlements} settlement/artifact records, ${addedLocations} locations, ${addedNpcs} NPCs.`); B.save(); return {addedSettlements,addedLocations,addedNpcs};};
  B.applyPriceModifiers=function(){B.normalizeState(); const rank=String(B.state.settlement?.type||'Town').toLowerCase(); const biome=String(B.state.settlement?.biome||'other').toLowerCase(); const rankMult=rank.includes('capital')?1.35:rank.includes('city')?1.2:rank.includes('village')?0.85:1; const biomeMult=/ocean|coast|river/.test(biome)?0.95:/mountain|desert|waste/.test(biome)?1.25:/forest|plains|valley/.test(biome)?1:1.08; (B.state.locations||[]).forEach((l,idx)=>{const goods=[...(l.inventory||[]),...(l.services||[])].slice(0,20); l.prices=goods.map((name,i)=>{const base=5+((idx+i*7)%44); const cp=Math.max(1,Math.round(base*rankMult*biomeMult)); const label=cp>=100?`${(cp/100).toFixed(2)} gp`:cp>=10?`${(cp/10).toFixed(1)} sp`:`${cp} cp`; return {name,price:label,availability:rank.includes('village')?'limited':rank.includes('capital')?'excellent':'standard'};});}); return B.state.locations;};
  const baseGenLoc=B.generateLocations;
  if(baseGenLoc&&!B._priceWrap){B.generateLocations=function(){const out=baseGenLoc.apply(B,arguments); B.applyPriceModifiers(); B.save&&B.save(); return out;}; B._priceWrap=true;}
  B.generateMissingLocations=function(target){B.normalizeState(); target=Number(target||B.state.settlement?.locationTarget||B.state.locations.length); if((B.state.locations||[]).length>=target) return B.state.locations; const old=[...B.state.locations]; const oldKeys=new Set(old.map(l=>(l.id+'|'+l.name).toLowerCase())); if(baseGenLoc) baseGenLoc.call(B,{count:target}); const fresh=[...(B.state.locations||[])]; B.state.locations=old; fresh.forEach(l=>{const key=(l.id+'|'+l.name).toLowerCase(); if(B.state.locations.length<target&&!oldKeys.has(key)) B.state.locations.push(l);}); B.applyPriceModifiers(); if(B.rebuildIndexes)B.rebuildIndexes(); B.log(`Generated missing locations up to ${B.state.locations.length}.`); B.save(); return B.state.locations;};
  B.generateCategoryLocations=function(category,count=8){B.normalizeState(); const r=B.rng((B.state.seed||'Belavados')+'|category|'+category+'|'+Date.now()); const types=B.allLocationTypes().filter(x=>!category||x.category===category); for(let i=0;i<count;i++){const t=B.pick(types,r)||B.pick(B.allLocationTypes(),r)||{category:category||'Imported',type:'market'}; const id=B.uid?B.uid('loc'):'loc_'+Date.now()+i; const inv=B.data.content?.inventory_by_category?.[t.category]||['local goods','local service']; B.state.locations.push({id,name:`${String(t.type||'Location').replace(/\b\w/g,c=>c.toUpperCase())} ${B.state.locations.length+1}`,type:t.type,category:t.category,x:8+Math.round(r()*84),y:10+Math.round(r()*78),overlayColor:'#00ffff',use:'workplace',inventory:B.sample?B.sample(inv,4,r):inv.slice(0,4),services:B.sample?B.sample(inv,3,r):inv.slice(0,3),hours:'locally posted hours',priceBand:'settlement adjusted',capacity:20+Math.round(r()*120),residents:[],employees:[],visitors:[],notes:`Generated category location for ${t.category}.`});} B.applyPriceModifiers(); if(B.rebuildIndexes)B.rebuildIndexes(); if(B.enrichLivingStructure)B.enrichLivingStructure(); B.log(`Generated ${count} ${category||'category'} locations without changing existing records.`); B.save(); return B.state.locations;};
  B.rerollLocation=function(id,mode='all'){B.normalizeState(); const l=B.state.locations.find(x=>x.id===id)||B.state.locations[0]; if(!l)return null; const r=B.rng((B.state.seed||'Belavados')+'|reroll-location|'+id+'|'+mode+'|'+Date.now()); const inv=B.data.content?.inventory_by_category?.[l.category]||['local goods','local service']; if(mode==='inventory'||mode==='all') l.inventory=B.sample?B.sample(inv,4+r()*3|0,r):inv.slice(0,5); if(mode==='services'||mode==='all') l.services=B.sample?B.sample(inv,3+r()*3|0,r):inv.slice(0,4); if(mode==='all'){l.notes=`Rerolled with ${B.state.settlement?.type||'settlement'} and ${B.state.settlement?.biome||'biome'} modifiers.`; l.capacity=8+Math.round(r()*240);} B.applyPriceModifiers(); if(B.enrichLocationStructure)B.enrichLocationStructure(l); B.log(`Rerolled ${mode} for ${l.name}.`); B.save(); return l;};
  B.generateAllRacesInCategory=function(category){B.normalizeState(); const races=(B.racesForCategory?B.racesForCategory(category):B.flattenRaces().filter(r=>r.category===category).map(r=>r.race)); if(!B.state.locations.length&&B.generateLocations)B.generateLocations(); if(B.generateNpcs)B.generateNpcs(Math.max(1,races.length)); (B.state.npcs||[]).forEach((n,i)=>{if(races[i]){n.race=races[i]; n.raceCategory=category||n.raceCategory;}}); if(B.enrichLivingStructure)B.enrichLivingStructure(); if(B.rebuildIndexes)B.rebuildIndexes(); B.log(`Generated NPC coverage for ${races.length} races in ${category||'selected category'}.`); B.save(); return B.state.npcs;};
  B.rerollNpc=function(id,mode='traits'){B.normalizeState(); const n=B.state.npcs.find(x=>x.id===id)||B.state.npcs[0]; if(!n)return null; const r=B.rng((B.state.seed||'Belavados')+'|reroll-npc|'+id+'|'+mode+'|'+Date.now()); if(mode==='traits'||mode==='all') n.traits=B.sample?B.sample(B.data.content?.personality_traits||[],4,r):n.traits; if(mode==='rumors'||mode==='all') n.rumors=[`Seen near ${B.pick(B.state.locations||[],r)?.name||'an unknown location'} after hours.`,`Knows a quiet truth about ${B.state.settlement?.name||'the settlement'}.`]; if(mode==='relationships'||mode==='all') n.relationships=(n.relationships||[]).slice().reverse(); if(mode==='schedule'||mode==='all'){(n.schedule||[]).forEach((bl,i)=>{if(i%3===0){const loc=B.pick(B.state.locations||[],r); if(loc){bl.locationId=loc.id; bl.locationName=loc.name;}}});} if(B.enrichNpcStructure)B.enrichNpcStructure(n); if(B.rebuildIndexes)B.rebuildIndexes(); B.log(`Rerolled ${mode} for ${n.name}.`); B.save(); return n;};
})();
