
(function(){
const B=window.BELAVADOS;
function init(){B.load(); bind(); render();}
function bind(){B.$('importFile')?.addEventListener('change',async e=>{if(e.target.files[0]){await B.importJSONFile(e.target.files[0]);render();B.setStatus('Imported JSON state.')}}); B.$('exportBtn')?.addEventListener('click',()=>B.exportJSON()); B.$('snapshotBtn')?.addEventListener('click',downloadSnapshot); B.$('clearBtn')?.addEventListener('click',()=>{if(confirm('Clear saved browser data?')){B.reset();render()}}); B.$('regenBtn')?.addEventListener('click',()=>{B.generateLocations();B.generateNpcs(B.state.settlement.npcTarget||120);render()}); B.$('rawState')?.addEventListener('input',e=>{try{B.state=JSON.parse(e.target.value);B.normalizeState();B.save();render()}catch(err){B.setStatus('Raw JSON is not valid yet.')}})}
function render(){const info=B.$('diagnostics'); if(info)info.innerHTML=`<div class="stat"><b>${B.state.locations.length}</b><span>locations</span></div><div class="stat"><b>${B.state.npcs.length}</b><span>NPCs</span></div><div class="stat"><b>${B.state.households.length}</b><span>households</span></div><div class="stat"><b>${B.state.svg?.anchors?.length||0}</b><span>SVG anchors</span></div>`; const raw=B.$('rawState'); if(raw)raw.value=JSON.stringify(B.state,null,2); const log=B.$('logBox'); if(log)log.innerHTML=(B.state.log||[]).map(x=>`<div>${B.escape(x.at)} — ${B.escape(x.message)}</div>`).join('')}
function downloadSnapshot(){const stateScript=`<script>localStorage.setItem('${B.key}', ${JSON.stringify(JSON.stringify(B.state))}); location.href='belavados_map_PLAYER.html';<\/script>`; const html=`<!doctype html><html><head><meta charset="utf-8"><title>Belavadös State Loader</title></head><body><p>Loading saved Belavadös state...</p>${stateScript}</body></html>`; B.downloadText(B.slug(B.state.settlement?.name||'belavados')+'_state_loader.html',html,'text/html')}
window.addEventListener('DOMContentLoaded',init);
})();
