
(function(){
const B=window.BELAVADOS;
function init(){B.load(); bind(); render();}
function bind(){const target=B.$('locationTargetPage'); if(target) target.value=B.state.settlement?.locationTarget||72; B.$('generateLocationPageBtn')?.addEventListener('click',()=>{const count=Number(B.$('locationTargetPage')?.value||B.state.settlement?.locationTarget||72); B.state.settlement.locationTarget=count; B.generateLocations({count}); if(B.state.npcs.length){if(B.assignExistingNpcsToLocations) B.assignExistingNpcsToLocations(); else B.generateNpcs(B.state.npcs.length);} const status=B.$('locationPageStatus'); if(status) status.textContent=`Generated ${B.state.locations.length} locations and assigned ${B.state.npcs.length} existing NPCs to homes, jobs, and visit schedules.`; render();}); B.$('assignNpcLocationsBtn')?.addEventListener('click',()=>{if(!B.state.locations.length) B.generateLocations(); if(B.state.npcs.length&&B.assignExistingNpcsToLocations) B.assignExistingNpcsToLocations(); const status=B.$('locationPageStatus'); if(status) status.textContent=`Assigned ${B.state.npcs.length} NPCs across ${B.state.locations.length} generated locations.`; render();}); B.$('importFile')?.addEventListener('change',async e=>{if(e.target.files[0]){await B.importJSONFile(e.target.files[0]);render()}}); B.$('exportBtn')?.addEventListener('click',()=>B.exportJSON()); ['locationSearch','categoryFilter'].forEach(id=>B.$(id)?.addEventListener('input',()=>render())); fillFilters();}
function fillFilters(){const c=B.$('categoryFilter'); if(c){const cats=[...new Set((B.state.locations||[]).map(l=>l.category))].sort(); c.innerHTML='<option value="">All categories</option>'+cats.map(x=>`<option>${B.escape(x)}</option>`).join('')}}
function render(){fillFilters(); const q=(B.$('locationSearch')?.value||'').toLowerCase(), cat=B.$('categoryFilter')?.value||''; let list=(B.state.locations||[]).filter(l=>{const people=(B.state.npcs||[]).filter(n=>[n.homeLocationId,n.workLocationId].includes(l.id)).map(n=>n.name).join(' '); const hay=[l.name,l.type,l.category,l.use,l.hours,l.priceBand,(l.inventory||[]).join(' '),(l.services||[]).join(' '),people].join(' ').toLowerCase(); return (!q||hay.includes(q))&&(!cat||l.category===cat)}); const out=B.$('locationList'); if(out)out.innerHTML=list.map(l=>B.locationCard(l,{full:true})).join('')||'<div class="notice">No locations match.</div>'; const summary=B.$('summaryBox'); if(summary)summary.innerHTML=`<div class="stat"><b>${list.length}</b><span>shown</span></div><div class="stat"><b>${B.state.locations.length}</b><span>total locations</span></div>`;}
window.addEventListener('DOMContentLoaded',init);
})();
