
(function(){
const B=window.BELAVADOS; let ticker=null;
function init(){B.load(); fillControls(); bind(); renderAll(); ticker=setInterval(()=>{B.updateNpcCurrents(); renderClock(); renderNpcLayer(); renderActiveBoard(); renderSelectedLight();},1000)}
function fillControls(){const s=B.state; const province=B.$('provinceSelect'), settlement=B.$('settlementSelect'), type=B.$('settlementType'), biome=B.$('biomeSelect'); if(province){province.innerHTML=B.provinceNames().map(p=>`<option>${B.escape(p)}</option>`).join(''); province.value=s.settlement.province||province.value; fillSettlementSelect()} if(type){type.innerHTML=(B.data.content.settlement_types||[]).map(x=>`<option>${B.escape(x)}</option>`).join(''); type.value=s.settlement.type||'Town'} if(biome){biome.innerHTML=(B.data.content.biomes||[]).map(x=>`<option>${B.escape(x)}</option>`).join(''); biome.value=s.settlement.biome||biome.value} ['settlementName','governmentType','settlementTags','locationTarget','npcTarget','seedInput'].forEach(id=>{const el=B.$(id); if(!el)return; const key={settlementName:'name',governmentType:'government',settlementTags:'tags',locationTarget:'locationTarget',npcTarget:'npcTarget',seedInput:'seed'}[id]; el.value=id==='seedInput'?s.seed:(s.settlement[key]??'')})}
function fillSettlementSelect(){const sel=B.$('settlementSelect'), province=B.$('provinceSelect')?.value||B.state.settlement.province; if(!sel)return; const items=B.settlementsForProvince(province); sel.innerHTML=items.map(x=>`<option>${B.escape(x)}</option>`).join(''); sel.value=B.state.settlement.name&&items.includes(B.state.settlement.name)?B.state.settlement.name:(items[0]||''); const name=B.$('settlementName'); if(name&&!name.value) name.value=sel.value;}
function readControls(){const s=B.state; const prov=B.$('provinceSelect')?.value; if(prov)s.settlement.province=prov; const nm=B.$('settlementName')?.value||B.$('settlementSelect')?.value; if(nm)s.settlement.name=nm; const st=B.$('settlementType')?.value; if(st)s.settlement.type=st; const bio=B.$('biomeSelect')?.value; if(bio)s.settlement.biome=bio; const gov=B.$('governmentType')?.value; if(gov!==undefined)s.settlement.government=gov; const tags=B.$('settlementTags')?.value; if(tags!==undefined)s.settlement.tags=tags; const lt=Number(B.$('locationTarget')?.value); if(lt)s.settlement.locationTarget=lt; const nt=Number(B.$('npcTarget')?.value); if(nt)s.settlement.npcTarget=nt; const seed=B.$('seedInput')?.value; if(seed) s.seed=seed;}
function bind(){B.$('provinceSelect')?.addEventListener('change',()=>{fillSettlementSelect(); const name=B.$('settlementName'); if(name) name.value=B.$('settlementSelect').value; readControls(); B.save()}); B.$('settlementSelect')?.addEventListener('change',e=>{B.$('settlementName').value=e.target.value; readControls(); B.save()}); ['settlementName','governmentType','settlementTags','locationTarget','npcTarget','seedInput','settlementType','biomeSelect'].forEach(id=>B.$(id)?.addEventListener('change',()=>{readControls();B.save();renderAll()}));
 B.$('generateLocationsBtn')?.addEventListener('click',()=>{readControls();B.generateLocations();renderAll()}); B.$('generateNpcsBtn')?.addEventListener('click',()=>{readControls();B.generateNpcs(Number(B.state.settlement.npcTarget||120));renderAll()}); B.$('generateAllBtn')?.addEventListener('click',()=>{readControls();B.generateLocations();B.generateNpcs(Number(B.state.settlement.npcTarget||120));renderAll()}); B.$('saveBtn')?.addEventListener('click',()=>{readControls();B.save();B.setStatus('Saved in this browser.')}); B.$('exportBtn')?.addEventListener('click',()=>B.exportJSON()); B.$('resetBtn')?.addEventListener('click',()=>{if(confirm('Clear this browser state and start a new generator state?')){B.reset();fillControls();renderAll()}});
 B.$('importFile')?.addEventListener('change',async e=>{const file=e.target.files[0]; if(!file)return; try{await B.importJSONFile(file); fillControls(); renderAll(); B.setStatus('Imported settlement state.')}catch(err){alert('Import failed: '+err.message)}}); B.$('svgFile')?.addEventListener('change',readSvg);}
function readSvg(e){const file=e.target.files[0]; if(!file)return; if(!/\.svg$/i.test(file.name)){alert('Please upload an SVG file only.');return} const reader=new FileReader(); reader.onload=()=>{try{const parsed=B.extractSvgAnchors(reader.result,file.name); B.state.svg=parsed; B.state.settlement.locationTarget=Math.max(B.state.settlement.locationTarget||0,parsed.anchors.length||0); B.save(); B.generateLocations({useSvg:true,count:parsed.anchors.length||B.state.settlement.locationTarget}); fillControls(); renderAll(); B.setStatus(`SVG loaded: ${parsed.anchors.length} clickable regions scanned and auto-filled.`)}catch(err){alert('SVG scan failed: '+err.message)}}; reader.readAsText(file)}
function renderAll(){B.updateNpcCurrents(); renderClock(); renderMap(); renderSelected(); renderActiveBoard(); B.renderStats(); renderLog();}
function renderClock(){const el=B.$('clockBox'); if(!el)return; const d=B.currentDate(); const bel=belavadosDate(d); el.innerHTML=`<div class="stat"><b>${B.escape(d.toLocaleTimeString())}</b><span>local live clock</span></div><div class="stat"><b>${B.escape(bel)}</b><span>Belavadös calendar</span></div>`}
function belavadosDate(d){return B.belavadosTimeLabel?B.belavadosTimeLabel(d):(d.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}))}
function renderMap(){const box=B.$('mapViewport'); if(!box)return; if(B.state.svg?.source){box.innerHTML=B.state.svg.source+`<div id="npcLayer" class="npc-layer"></div>`; bindSvgRegions()} else {box.innerHTML=`<div class="generated-map">${(B.state.locations||[]).map(l=>`<button class="region-dot" title="${B.escape(l.name)}" data-id="${l.id}" style="left:${l.x}%;top:${l.y}%;background:${l.overlayColor}"></button>`).join('')}<div id="npcLayer" class="npc-layer"></div>${!B.state.locations.length?'<div class="empty-map"><div><h2>No map generated yet</h2><p>Upload an SVG or generate locations to populate the settlement.</p></div></div>':''}</div>`; box.querySelectorAll('.region-dot').forEach(btn=>btn.addEventListener('click',()=>{B.state.selected.locationId=btn.dataset.id;B.save();renderSelected()}));} renderNpcLayer();}
function bindSvgRegions(){const bySource=Object.fromEntries((B.state.locations||[]).map(l=>[l.sourceId,l.id])); document.querySelectorAll('#mapViewport [data-bdg-location-id]').forEach(el=>{const source=el.getAttribute('data-bdg-location-id'); const loc=(B.state.locations||[]).find(l=>l.sourceId===source||l.id===source); if(loc){el.setAttribute('data-location-id',loc.id); el.addEventListener('click',ev=>{ev.stopPropagation(); B.state.selected.locationId=loc.id; B.save(); renderSelected();});}})}
function renderNpcLayer(){const layer=B.$('npcLayer'); if(!layer)return; const npcs=(B.state.npcs||[]).slice(0,90); layer.innerHTML=npcs.map(n=>{const p=B.npcPosition(n); return `<div class="npc-token ${p.away?'away':''}" style="left:${p.x}%;top:${p.y}%" title="${B.escape(n.name)} — ${B.escape(p.label||'')}">${B.escape(p.icon||n.icon||'🧍')}<span class="mini-name">${B.escape(n.name.split(' ')[0])}</span></div>`}).join('')}
function renderSelected(){const loc=B.state.locations.find(l=>l.id===B.state.selected.locationId); const npc=B.state.npcs.find(n=>n.id===B.state.selected.npcId); const lp=B.$('selectedLocation'); if(lp)lp.innerHTML=B.locationCard(loc); const np=B.$('selectedNpc'); if(np)np.innerHTML=B.npcCard(npc); renderSelectedLight()}
function renderSelectedLight(){const npc=B.state.npcs.find(n=>n.id===B.state.selected.npcId); const el=B.$('selectedNpcNow'); if(el&&npc){const bl=B.activeBlock(npc); el.textContent=`${npc.name}: ${bl.icon||''} ${bl.label||bl.scenario} @ ${bl.locationName||''}`}}
function renderActiveBoard(){const el=B.$('activeBoard'); if(!el)return; const rows=(B.state.npcs||[]).slice(0,18).map(n=>{const p=B.activeBlock(n); return `<tr><td>${B.escape(p.icon||'')}</td><td><a href="#" data-npc="${n.id}">${B.escape(n.name)}</a></td><td>${B.escape(p.scenario)}</td><td>${B.escape(p.locationName||'')}</td><td>${B.escape(p.label||'')}</td></tr>`}).join(''); el.innerHTML=`<div class="table-wrap"><table><thead><tr><th></th><th>NPC</th><th>Scenario</th><th>Location</th><th>Details</th></tr></thead><tbody>${rows}</tbody></table></div>`; el.querySelectorAll('[data-npc]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();B.state.selected.npcId=a.dataset.npc;B.save();renderSelected()}))}
function renderLog(){const el=B.$('logBox'); if(!el)return; el.innerHTML=(B.state.log||[]).slice(0,6).map(x=>`<div class="small">${B.escape(new Date(x.at).toLocaleTimeString())}: ${B.escape(x.message)}</div>`).join('')||'<div class="small">No generator actions yet.</div>'}
window.addEventListener('DOMContentLoaded',init);
})();
