
(function(){
const B=window.BELAVADOS;
function init(){B.load(); bind(); render(); setInterval(()=>{B.updateNpcCurrents(); render(false)},3000)}
function bind(){const target=B.$('npcTargetPage'); if(target) target.value=B.state.settlement?.npcTarget||120; B.$('generateNpcPageBtn')?.addEventListener('click',()=>{const count=Number(B.$('npcTargetPage')?.value||B.state.settlement?.npcTarget||120); B.state.settlement.npcTarget=count; if(!B.state.locations.length) B.generateLocations(); B.generateNpcs(count); B.setStatus&&B.setStatus('Generated NPC lives.'); const status=B.$('npcPageStatus'); if(status) status.textContent=`Generated ${B.state.npcs.length} NPC lives with households, family trees, schedules, work trips, vacations, and map movement.`; render();}); B.$('refreshNpcPageBtn')?.addEventListener('click',()=>{B.rebuildIndexes&&B.rebuildIndexes(); B.updateNpcCurrents&&B.updateNpcCurrents(); B.enrichLivingStructure&&B.enrichLivingStructure(); B.save&&B.save(); const status=B.$('npcPageStatus'); if(status) status.textContent='Refreshed NPC schedules, family metadata, relationships, and location indexes.'; render();}); B.$('importFile')?.addEventListener('change',async e=>{if(e.target.files[0]){await B.importJSONFile(e.target.files[0]);render()}}); B.$('exportBtn')?.addEventListener('click',()=>B.exportJSON()); ['npcSearch','raceFilter','scenarioFilter'].forEach(id=>B.$(id)?.addEventListener('input',()=>render())); fillFilters();}
function fillFilters(){const race=B.$('raceFilter'); if(race){const races=[...new Set((B.state.npcs||[]).map(n=>n.race))].sort(); race.innerHTML='<option value="">All races</option>'+races.map(x=>`<option>${B.escape(x)}</option>`).join('')} const sc=B.$('scenarioFilter'); if(sc){const scenarios=[...new Set((B.state.npcs||[]).map(n=>B.activeBlock(n).scenario))].sort(); sc.innerHTML='<option value="">All current scenarios</option>'+scenarios.map(x=>`<option>${B.escape(x)}</option>`).join('')}}
function render(updateFilters=true){if(updateFilters)fillFilters(); const q=(B.$('npcSearch')?.value||'').toLowerCase(), race=B.$('raceFilter')?.value||'', scenario=B.$('scenarioFilter')?.value||''; let list=(B.state.npcs||[]).filter(n=>{const hay=[n.name,n.race,n.genderIdentity,n.pronouns,n.job,n.personality,(n.hobbies||[]).join(' '),n.homeLocationName,n.workLocationName].join(' ').toLowerCase(); const bl=B.activeBlock(n); return (!q||hay.includes(q))&&(!race||n.race===race)&&(!scenario||bl.scenario===scenario)}); const out=B.$('npcList'); if(out)out.innerHTML=list.map(n=>B.npcCard(n,{full:true})).join('')||'<div class="notice">No NPCs match.</div>'; const summary=B.$('summaryBox'); if(summary)summary.innerHTML=`<div class="stat"><b>${list.length}</b><span>shown</span></div><div class="stat"><b>${B.state.npcs.length}</b><span>total NPCs</span></div>`; document.querySelectorAll('.npc-card').forEach(card=>card.addEventListener('click',()=>{B.state.selected.npcId=card.dataset.id;B.save()}));}
window.addEventListener('DOMContentLoaded',init);
})();
