
(function(){
const B=window.BELAVADOS;
const catColors={
  'Food, Drink, and Hospitality':'#d88a3d','Retail and Household Goods':'#6fd6ff','Crafting and Industry':'#b6b6b6','Magic, Religion, and Lore':'#a174ff','Health, Alchemy, and Apothecary':'#65e6a1','Transit and Logistics':'#ffcf5a','Government, Security, and Law':'#5f93ff','Homes, Social Life, and Leisure':'#ff8bc3','Education, Guilds, and Training':'#8fd1ff','Wilderness, Agriculture, and Animals':'#7ed957'};
const locationHints=[
  ['tavern',['tavern','inn','restaurant','common house','cookshop']],['library',['library','archive','arcane university']],['market',['market','food market','general store','department store']],['forge',['blacksmith','foundry','armory','weapon shop']],['dock',['ferry dock','steamship dock','harbor','dock','skyship dock']],['temple',['temple','shrine','monastery']],['clinic',['hospital','clinic','healer','apothecary']],['guard',['guard station','courthouse','town hall']],['school',['school','academy','guildhall','training yard']],['farm',['farm','stable','greenhouse','ranch']]
];
function randInt(r,min,max){return Math.floor(r()*(max-min+1))+min}
function chance(r,p){return r()<p}
function wordsForName(kind,r){const parts=B.data.content.name_parts; const pre=B.pick(parts.prefixes,r), noun=B.pick(parts.nouns,r), suf=chance(r,.34)?' '+B.pick(parts.suffixes,r):''; const clean=String(kind||'place').split(/\s+/).map(w=>w[0]?.toUpperCase()+w.slice(1)).join(' '); return `${pre} ${clean} ${noun}${suf}`;}
function locationTypeForAnchor(anchor,r){const label=(anchor.label||anchor.id||'').toLowerCase(); for(const [hint,types] of locationHints){if(label.includes(hint)) return B.pick(types,r)} return B.pick(B.allLocationTypes(),r)?.type||'common house'}
function locationTypeForSettlement(index,r){const st=B.state.settlement?.type||'Town'; const biome=(B.state.settlement?.biome||'').toLowerCase(); let pool=B.allLocationTypes(); if(index<3 && /capital|city/i.test(st)) pool=pool.concat([{category:'Government, Security, and Law',type:'town hall'},{category:'Transit and Logistics',type:'portal station'},{category:'Transit and Logistics',type:'skyship dock'},{category:'Magic, Religion, and Lore',type:'arcane university'}]);
  if(/coastal|ocean|underwater|reef|river|beach/.test(biome)) pool=pool.concat([{category:'Transit and Logistics',type:'ferry dock'},{category:'Crafting and Industry',type:'shipyard'},{category:'Health, Alchemy, and Apothecary',type:'pressure clinic'}]);
  if(/forest|tree|rainforest|marsh|swamp|farming|grassland|prairie/.test(biome)) pool=pool.concat([{category:'Wilderness, Agriculture, and Animals',type:'farm'},{category:'Wilderness, Agriculture, and Animals',type:'stable'},{category:'Magic, Religion, and Lore',type:'shrine'}]);
  if(/mountain|cavern|valley/.test(biome)) pool=pool.concat([{category:'Crafting and Industry',type:'foundry'},{category:'Transit and Logistics',type:'caravan stop'},{category:'Wilderness, Agriculture, and Animals',type:'ranger lodge'}]);
  return B.pick(pool,r)?.type||'market';}
function inventoryForCategory(category,r){const inv=B.data.content.inventory_by_category?.[category]||['local service']; return B.sample(inv,randInt(r,3,6),r)}
function inferUse(category,type){const t=(type||'').toLowerCase(); if(/inn|hotel|hostel|house|apartment|residence|common/.test(t)) return 'mixed home and public'; if(/home|leisure|hospitality/.test(category)) return 'public and social'; if(/government|law/.test(category)) return 'civic'; if(/transit/.test(category)) return 'transit'; return 'workplace'}
B.generateLocations=function(options={}){
  B.normalizeState(); const s=B.state; const r=B.rng(s.seed+'|locations|'+(s.svg?.name||'')); const count=Number(options.count||s.settlement.locationTarget||60); const anchors=(options.useSvg!==false && s.svg?.anchors?.length)?s.svg.anchors:[]; const source=anchors.length?anchors:Array.from({length:count},(_,i)=>({id:'generated_slot_'+(i+1),label:'Generated map region '+(i+1),x:8+(i*37%84),y:10+(i*53%80),source:'generated'}));
  const locations=source.slice(0,Math.max(source.length,count)).map((anchor,i)=>{
    const type=anchors.length?locationTypeForAnchor(anchor,r):locationTypeForSettlement(i,r); const category=B.categoryOfType(type); const id='loc_'+B.slug(anchor.id||anchor.label||type)+'_'+i; const name=anchor.label && !/^generated map region/i.test(anchor.label)?anchor.label:wordsForName(type,r);
    return {id,name,type,category,sourceId:anchor.id||'',source:anchor.source||'generated',x:Number(anchor.x??(8+(i*37%84))),y:Number(anchor.y??(10+(i*53%80))),overlayColor:catColors[category]||'#00ffff',use:inferUse(category,type),inventory:inventoryForCategory(category,r),services:inventoryForCategory(category,r),hours:hoursFor(category,type,r),priceBand:B.pick(['copper-friendly','silver standard','guild-priced','noble luxury','donation-based'],r),capacity:randInt(r,8,240),residents:[],employees:[],visitors:[],notes:`Auto-filled from ${anchor.source||'the settlement generator'} using ${s.settlement?.type||'settlement'} + ${s.settlement?.biome||'biome'} context.`}
  });
  s.locations=locations; s.selected.locationId=locations[0]?.id||null; B.rebuildIndexes(); B.log('Generated '+locations.length+' visitable locations.'); B.save(); return locations;
}
function hoursFor(category,type,r){if(/Transit/.test(category))return '05:30-23:30; emergency bell after hours'; if(/Food/.test(category))return '06:00-23:00; breakfast, supper, and late tables'; if(/Government/.test(category))return '08:00-17:00; court days vary'; if(/Health/.test(category))return '24-hour urgent window; normal care 07:00-19:00'; if(/Magic/.test(category))return '09:00-21:00; licensed rituals by appointment'; return `${String(randInt(r,6,10)).padStart(2,'0')}:00-${String(randInt(r,17,23)).padStart(2,'0')}:00`}
B.extractSvgAnchors=function(svgText,name='uploaded.svg'){
  const parser=new DOMParser(); const doc=parser.parseFromString(svgText,'image/svg+xml'); const svg=doc.querySelector('svg'); if(!svg) throw new Error('No SVG root was found.');
  doc.querySelectorAll('script,foreignObject,iframe,object,embed').forEach(el=>el.remove());
  doc.querySelectorAll('*').forEach(el=>{[...el.attributes].forEach(attr=>{if(/^on/i.test(attr.name)) el.removeAttribute(attr.name); if(/javascript:/i.test(attr.value)) el.removeAttribute(attr.name);});});
  doc.querySelectorAll('[id*="menu" i],[class*="menu" i],[id*="toolbar" i],[class*="toolbar" i],[id*="pin" i],[class*="pin" i]').forEach(el=>{if(!el.matches('svg')) el.remove();});
  const candidates=[...doc.querySelectorAll('[data-location], [data-name], path[id], polygon[id], polyline[id], rect[id], circle[id], ellipse[id], g[id]')].filter(el=>!el.closest('defs,clipPath,mask,marker,pattern,linearGradient,radialGradient,symbol'));
  const anchors=[]; candidates.forEach((el,i)=>{const id=el.getAttribute('data-location')||el.getAttribute('data-name')||el.getAttribute('id')||('svg_region_'+i); if(!id||/^svg/i.test(id)&&i>200) return; const label=(el.getAttribute('data-label')||el.getAttribute('aria-label')||el.querySelector('title')?.textContent||id).replace(/[_-]+/g,' ').trim(); const pt=centroidFromElement(el,i,candidates.length); const locId='svg_'+B.slug(id)+'_'+i; el.setAttribute('data-bdg-location-id',locId); el.classList.add('bdg-region'); anchors.push({id:locId,originalId:id,label:label||('SVG Region '+(i+1)),x:pt.x,y:pt.y,source:'svg'});});
  const serializer=new XMLSerializer(); return {name,source:serializer.serializeToString(svg),anchors};
}
function nums(s){return (String(s||'').match(/-?\d*\.?\d+/g)||[]).map(Number)}
function centroidFromElement(el,i,total){const tag=el.tagName.toLowerCase(); let xs=[],ys=[]; if(tag==='circle'||tag==='ellipse'){xs=[Number(el.getAttribute('cx')||50)]; ys=[Number(el.getAttribute('cy')||50)]} else if(tag==='rect'){const x=Number(el.getAttribute('x')||0),y=Number(el.getAttribute('y')||0),w=Number(el.getAttribute('width')||10),h=Number(el.getAttribute('height')||10); xs=[x+w/2]; ys=[y+h/2]} else {const vals=nums(el.getAttribute('points')||el.getAttribute('d')||''); for(let n=0;n<vals.length-1;n+=2){xs.push(vals[n]);ys.push(vals[n+1])}}
  if(!xs.length){const angle=(i/Math.max(total,1))*Math.PI*2; return {x:50+Math.cos(angle)*35,y:50+Math.sin(angle)*35}}
  const avg=a=>a.reduce((p,c)=>p+c,0)/a.length; let x=avg(xs),y=avg(ys); const max=Math.max(...xs,...ys,100); if(max>100){const minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys); x=((x-minX)/(maxX-minX||1))*80+10; y=((y-minY)/(maxY-minY||1))*80+10} return {x:Math.max(2,Math.min(98,x)),y:Math.max(2,Math.min(98,y))};}
function makeNpcBase(r,household,home,role,index){const content=B.data.content; const race=B.pick(B.flattenRaces(),r)||{race:'Human',category:'Traditional D&D Peoples'}; const gender=B.pick(content.gender_identities,r)||{identity:'Non-Binary',pronouns:'they/them'}; const name=makeName(r,race.race); const values=B.sample(content.values,2,r); const traits=B.sample(content.personality_traits,4,r); const hobbies=B.sample(content.hobbies,3,r); const flaw=B.pick(content.flaws,r); return {id:B.uid('npc'),name,race:race.race,raceCategory:race.category,genderIdentity:gender.identity,pronouns:gender.pronouns,lifeStage:role.lifeStage,age:role.age,householdId:household.id,homeLocationId:home.id,homeLocationName:home.name,workLocationId:null,workLocationName:'',job:'',roleInHousehold:role.role,alignment:makeAlignment(r),traits,personality:personalityText(traits,values,flaw),hobbies,values,flaw,relationships:[],familyTree:{parents:[],children:[],siblings:[],grandparents:[],grandchildren:[],guardians:[],wards:[],partners:[],exPartners:[],chosenFamily:[]},schedule:[],workTripPlan:null,vacationPlan:null,needProfile:needsProfile(r),memoryLog:[`Moved into ${home.name} with household ${household.name}.`],icon:role.icon||'🧍',current:{scenario:'unknown',locationName:'',x:home.x,y:home.y,icon:'🧍'}}}
function makeName(r,race){const first=['Aelira','Bren','Caelis','Dorna','Erynn','Faelor','Gavren','Hestra','Ilyra','Jorren','Kaelis','Luneth','Maelis','Noryn','Orrik','Phaedra','Quill','Ryn','Sylra','Thorne','Ulwyn','Vaelis','Westra','Xyren','Ylara','Zorren','Amara','Bellis','Corven','Dax','Elowen','Fenn','Gryx','Harrow','Isolde','Jasca','Kith','Mara','Nix','Orla','Perrin','Rook','Sable','Tamsin','Uri','Vexa','Willow','Yestin','Zara']; const last=['Ambergear','Blackreef','Cinderbell','Dawnhollow','Elderbranch','Frostquill','Gearmantle','Harborvow','Ironleaf','Jadewake','Kettlesong','Lanternmere','Moonspoke','Nettlebrook','Oathwharf','Pearlthorn','Quartzrail','Rootcrown','Silverdock','Tideglass','Umberfall','Velvetforge','Wildgear','Yewspire','Zephyrwell']; return `${B.pick(first,r)} ${B.pick(last,r)}`;}
function personalityText(traits,values,flaw){return `${traits.slice(0,2).join(' and ')} in public, driven by ${values.join(' and ')}, but often ${flaw}.`;}
function needsProfile(r){return {energy:randInt(r,35,95),hunger:randInt(r,30,90),social:randInt(r,25,95),fun:randInt(r,20,90),ambition:randInt(r,30,100),homeComfort:randInt(r,35,100)}}
function makeAlignment(r){const axes={altruism:randInt(r,0,3000),lawfulness:randInt(r,0,3000),cooperation:randInt(r,0,3000),honor:randInt(r,0,3000)}; const phase=v=>v<1000?'low':v<2000?'neutral':'high'; const moral=axes.altruism<1000?'Self-First':axes.altruism<2000?'Balanced':'Altruistic'; const order=axes.lawfulness<1000?'Chaotic':axes.lawfulness<2000?'Neutral':'Lawful'; const community=axes.cooperation<1000?'Solitary':axes.cooperation<2000?'Selective':'Communal'; return {axes,phases:Object.fromEntries(Object.entries(axes).map(([k,v])=>[k,phase(v)])),name:`${order} ${moral} (${community})`,summary:`${order} ${moral}; ${community} social pattern; honor ${phase(axes.honor)}.`};}
function roleTemplates(r){return {
  solo:[{role:'householder',lifeStage:B.pick(['young adult','adult','middle-aged'],r),age:randInt(r,22,62),icon:'🧍'}],
  couple:[{role:'partner',lifeStage:'adult',age:randInt(r,24,70),icon:'🧍'},{role:'partner',lifeStage:'adult',age:randInt(r,24,70),icon:'🧍'}],
  polycule:[{role:'partner',lifeStage:'adult',age:randInt(r,24,70),icon:'🧍'},{role:'partner',lifeStage:'adult',age:randInt(r,24,70),icon:'🧍'},{role:'partner',lifeStage:'adult',age:randInt(r,24,70),icon:'🧍'}],
  nuclear:[{role:'parent',lifeStage:'adult',age:randInt(r,28,64),icon:'🧑'},{role:'parent',lifeStage:'adult',age:randInt(r,28,64),icon:'🧑'},{role:'child',lifeStage:B.pick(['child','teen'],r),age:randInt(r,6,17),icon:'🧒'}].concat(chance(r,.55)?[{role:'child',lifeStage:B.pick(['child','teen'],r),age:randInt(r,2,17),icon:'🧒'}]:[]),
  multigeneration:[{role:'grandparent',lifeStage:'elder',age:randInt(r,66,105),icon:'🧓'},{role:'parent',lifeStage:'adult',age:randInt(r,32,58),icon:'🧑'},{role:'parent',lifeStage:'adult',age:randInt(r,30,62),icon:'🧑'},{role:'child',lifeStage:B.pick(['child','teen'],r),age:randInt(r,3,17),icon:'🧒'}],
  chosen:[{role:'chosen family',lifeStage:'adult',age:randInt(r,21,75),icon:'🧍'},{role:'chosen family',lifeStage:'adult',age:randInt(r,21,75),icon:'🧍'},{role:'chosen family',lifeStage:B.pick(['young adult','adult','elder'],r),age:randInt(r,18,88),icon:'🧍'}],
  singleParent:[{role:'parent',lifeStage:'adult',age:randInt(r,25,60),icon:'🧑'},{role:'child',lifeStage:B.pick(['child','teen'],r),age:randInt(r,1,17),icon:'🧒'}]
}}
function residentialLocations(){let locs=B.state.locations.filter(l=>/home|inn|hotel|hostel|common|house|social|leisure|residential|public/.test((l.type+' '+l.category+' '+l.use).toLowerCase())); return locs.length?locs:B.state.locations;}
function workLocationsForAdult(){return B.state.locations.filter(l=>!/home|residential/.test((l.use+' '+l.type).toLowerCase())) || B.state.locations;}
function assignJob(npc,work,r){const jobs=B.data.content.jobs?.[work.category]||['worker','clerk','laborer','specialist']; if(/child/.test(npc.lifeStage)) return {job:'student / family helper',work:B.pick(B.state.locations.filter(l=>/school|library|academy|guild|market|temple/i.test(l.type+' '+l.category)),r)||work}; if(/teen/.test(npc.lifeStage)&&chance(r,.4)) return {job:'apprentice '+B.pick(jobs,r),work}; if(/elder/.test(npc.lifeStage)&&chance(r,.45)) return {job:'retired community elder',work:B.pick(B.state.locations.filter(l=>/temple|library|market|common|garden/i.test(l.type+' '+l.category)),r)||work}; return {job:B.pick(jobs,r)||'worker',work};}
B.generateNpcs=function(count){B.normalizeState(); if(!B.state.locations.length) B.generateLocations(); const s=B.state; const r=B.rng(s.seed+'|npcs|'+s.locations.length+'|'+count); s.npcs=[]; s.households=[]; B.rebuildIndexes(); const homes=residentialLocations(); const workPool=workLocationsForAdult(); let remaining=Number(count||s.settlement.npcTarget||100); let householdNum=1;
  while(remaining>0){const kind=B.pick(['solo','couple','polycule','nuclear','multigeneration','chosen','singleParent'],r); const roles=roleTemplates(r)[kind].slice(0,remaining); const home=B.pick(homes,r)||B.pick(s.locations,r); const household={id:B.uid('household'),name:`Household ${householdNum}: ${home.name}`,kind,homeLocationId:home.id,homeLocationName:home.name,members:[],notes:`${kind} household generated with visible family links.`}; householdNum++;
    roles.forEach((role,i)=>{const npc=makeNpcBase(r,household,home,role,i); const w=B.pick(workPool,r)||home; const assigned=assignJob(npc,w,r); npc.job=assigned.job; npc.workLocationId=assigned.work.id; npc.workLocationName=assigned.work.name; npc.schedule=buildSchedule(npc,home,assigned.work,r); if(chance(r,.18)&&!/child/.test(npc.lifeStage)) npc.workTripPlan=makeWorkTrip(r,s.settlement.province); if(chance(r,.14)) npc.vacationPlan=makeVacation(r,s.settlement.province); s.npcs.push(npc); household.members.push(npc.id); remaining--;});
    s.households.push(household); wireHousehold(s,household,r); if(remaining<=0) break;
  }
  addNonFamilyRelations(s,r); B.rebuildIndexes(); s.selected.npcId=s.npcs[0]?.id||null; s.selected.householdId=s.households[0]?.id||null; B.log('Generated '+s.npcs.length+' NPCs with households, relationships, schedules, work trips, vacations, and moving map tokens.'); B.save(); return s.npcs;}
B.assignExistingNpcsToLocations=function(){B.normalizeState(); if(!B.state.locations.length) B.generateLocations(); const s=B.state; const r=B.rng(s.seed+'|assign-existing|'+s.locations.length+'|'+s.npcs.length); const homes=residentialLocations(); const workPool=workLocationsForAdult(); const householdHomes={};
  (s.households||[]).forEach((h,i)=>{const home=B.pick(homes,r)||B.pick(s.locations,r); if(!home)return; householdHomes[h.id]=home; h.homeLocationId=home.id; h.homeLocationName=home.name; h.name=(h.name||`Household ${i+1}`).replace(/: .*/, '')+`: ${home.name}`;});
  (s.npcs||[]).forEach(n=>{const home=householdHomes[n.householdId]||B.pick(homes,r)||B.pick(s.locations,r); if(!home)return; n.homeLocationId=home.id; n.homeLocationName=home.name; const work=B.pick(workPool,r)||home; const assigned=assignJob(n,work,r); n.job=assigned.job; n.workLocationId=assigned.work.id; n.workLocationName=assigned.work.name; n.schedule=buildSchedule(n,home,assigned.work,r); n.current={scenario:'assigned',locationName:home.name,x:home.x,y:home.y,icon:n.icon||'🧍'}; n.memoryLog=n.memoryLog||[]; n.memoryLog.unshift(`Reassigned to ${home.name} and ${assigned.work.name} after the current location generation.`); n.memoryLog=n.memoryLog.slice(0,30);});
  B.rebuildIndexes(); B.updateNpcCurrents(); B.log('Assigned existing NPC homes, jobs, visitor schedules, and moving tokens to the current locations.'); B.save(); return s.npcs;}

function wireHousehold(s,household,r){const mem=household.members.map(id=>s.npcs.find(n=>n.id===id)).filter(Boolean); const adults=mem.filter(n=>!/child|teen/.test(n.lifeStage)); const children=mem.filter(n=>/child|teen/.test(n.lifeStage)); const elders=mem.filter(n=>/elder/.test(n.lifeStage)||/grandparent/.test(n.roleInHousehold));
  for(let i=0;i<adults.length;i++) for(let j=i+1;j<adults.length;j++){addRelation(adults[i],adults[j],household.kind==='chosen'?'Chosen family':'Romantic partner','familial'); if(household.kind==='polycule'||household.kind==='couple'||household.kind==='nuclear'||household.kind==='multigeneration'){adults[i].familyTree.partners.push(adults[j].id); adults[j].familyTree.partners.push(adults[i].id)}}
  children.forEach(c=>{adults.filter(a=>!/grandparent/.test(a.roleInHousehold)).forEach(p=>{addRelation(p,c,'Parent','familial'); p.familyTree.children.push(c.id); c.familyTree.parents.push(p.id)}); elders.forEach(g=>{addRelation(g,c,'Grandparent','familial'); g.familyTree.grandchildren.push(c.id); c.familyTree.grandparents.push(g.id)});});
  for(let i=0;i<children.length;i++) for(let j=i+1;j<children.length;j++){addRelation(children[i],children[j],'Sibling','familial'); children[i].familyTree.siblings.push(children[j].id); children[j].familyTree.siblings.push(children[i].id)}
  if(household.kind==='chosen'){mem.forEach(a=>mem.filter(b=>a.id!==b.id).forEach(b=>{if(!a.familyTree.chosenFamily.includes(b.id))a.familyTree.chosenFamily.push(b.id)}))}
}
function addRelation(a,b,type,category='personal',strength){const one={npcId:b.id,npcName:b.name,type,category,strength:strength||Math.floor(35+Math.random()*65),history:`${type} relationship through ${category} life.`}; const two={npcId:a.id,npcName:a.name,type:reciprocal(type),category,strength:one.strength,history:one.history}; a.relationships.push(one); b.relationships.push(two);}
function reciprocal(type){if(type==='Parent')return'Child'; if(type==='Child')return'Parent'; if(type==='Grandparent')return'Grandchild'; if(type==='Grandchild')return'Grandparent'; return type;}
function addNonFamilyRelations(s,r){const npcs=s.npcs; npcs.forEach(n=>{const workMates=npcs.filter(o=>o.id!==n.id&&o.workLocationId===n.workLocationId); B.sample(workMates,randInt(r,1,3),r).forEach(o=>addRelation(n,o,B.pick(['Coworker','Professional rival','Mentor','Apprentice','Trusted colleague'],r),'professional',randInt(r,25,95))); const friends=B.sample(npcs.filter(o=>o.id!==n.id&&o.homeLocationId!==n.homeLocationId),randInt(r,1,4),r); friends.forEach(o=>addRelation(n,o,B.pick(['Friend','Close friend','Neighbor','Dating partner','Ex partner','Travel companion','Confidant'],r),'personal',randInt(r,20,100)));});}
function buildSchedule(npc,home,work,r){const meal=B.pick(B.state.locations.filter(l=>/tavern|inn|restaurant|bakery|food|tea|cookshop/i.test(l.type+' '+l.category)),r)||home; const library=B.pick(B.state.locations.filter(l=>/library|archive|school|academy/i.test(l.type+' '+l.category)),r)||meal; const market=B.pick(B.state.locations.filter(l=>/market|store|shop|provisioner/i.test(l.type+' '+l.category)),r)||meal; const date=B.pick(B.state.locations.filter(l=>/theatre|theater|restaurant|tea|garden|bath|tavern|inn/i.test(l.type+' '+l.category)),r)||meal; const temple=B.pick(B.state.locations.filter(l=>/temple|shrine|monastery/i.test(l.type+' '+l.category)),r)||library; const personalSpot=B.pick([library,meal,market,date,temple],r)||home;
  const weekday=[1,2,3,4,5], weekend=[0,6]; const sleep={days:[0,1,2,3,4,5,6],start:'22:00',end:'06:00',scenario:'sleep',label:'sleeping at home',locationId:home.id,locationName:home.name,icon:'🌙'};
  return [sleep,{days:weekday,start:'06:00',end:'07:30',scenario:'home',label:'breakfast, hygiene, family check-ins',locationId:home.id,locationName:home.name,icon:'🏠'},
  {days:weekday,start:'07:30',end:'08:15',scenario:'transit',label:'commute to work',fromId:home.id,toId:work.id,locationId:work.id,locationName:work.name,icon:'🚶'},
  {days:weekday,start:'08:15',end:'12:00',scenario:'work',label:'professional duties: '+npc.job,locationId:work.id,locationName:work.name,icon:'🛠️'},
  {days:weekday,start:'12:00',end:'13:00',scenario:'meal',label:'midday meal and gossip',locationId:meal.id,locationName:meal.name,icon:'🍲'},
  {days:weekday,start:'13:00',end:'17:00',scenario:'work',label:'afternoon duties: '+npc.job,locationId:work.id,locationName:work.name,icon:'🛠️'},
  {days:weekday,start:'17:00',end:'18:00',scenario:'transit',label:'errands after work',fromId:work.id,toId:market.id,locationId:market.id,locationName:market.name,icon:'🧺'},
  {days:[1,3],start:'18:00',end:'20:00',scenario:'library',label:'study, hobby, or professional reading',locationId:library.id,locationName:library.name,icon:'📚'},
  {days:[2,5],start:'18:30',end:'21:00',scenario:'date',label:'date, partner time, or close friendship outing',locationId:date.id,locationName:date.name,icon:'💞'},
  {days:[4],start:'18:00',end:'20:30',scenario:'temple',label:'community rite, choir, or volunteer duty',locationId:temple.id,locationName:temple.name,icon:'🕯️'},
  {days:weekday,start:'20:30',end:'22:00',scenario:'home',label:'home, chores, messages, family tree updates',locationId:home.id,locationName:home.name,icon:'🏠'},
  {days:weekend,start:'07:30',end:'10:00',scenario:'home',label:'slow breakfast, family calls, home repairs',locationId:home.id,locationName:home.name,icon:'🏠'},
  {days:[6],start:'10:00',end:'14:00',scenario:'market',label:'market browsing, shopping, rumors',locationId:market.id,locationName:market.name,icon:'🛍️'},
  {days:[0],start:'10:00',end:'13:00',scenario:'family',label:'family visit, chosen-family brunch, or elder care',locationId:home.id,locationName:home.name,icon:'👪'},
  {days:weekend,start:'14:00',end:'18:00',scenario:'personal',label:'hobby time: '+npc.hobbies.join(', '),locationId:personalSpot.id,locationName:personalSpot.name,icon:'✨'},
  {days:weekend,start:'18:00',end:'22:00',scenario:'social',label:'supper, performances, dates, and neighborhood visits',locationId:date.id,locationName:date.name,icon:'🎭'}];}
function makeWorkTrip(r,currentProvince){const away=B.randomSettlementElsewhere(r,currentProvince); return {weekday:randInt(r,1,5),start:'09:00',end:'17:30',province:away.province,settlement:away.settlement,mode:B.pick(B.data.content.transit_modes,r),purpose:B.pick(['supplier negotiation','guild audit','court filing','teaching rotation','medical consultation','route inspection','family-business delivery','research appointment'],r)};}
function makeVacation(r,currentProvince){const away=B.randomSettlementElsewhere(r,currentProvince); const start=randInt(r,8,24); return {monthDays:[start,start+1],province:away.province,settlement:away.settlement,mode:B.pick(B.data.content.transit_modes,r),purpose:B.pick(['quiet vacation','festival visit','family holiday','romantic trip','pilgrimage','beach rest','forest retreat','food tour'],r)};}
B.rebuildIndexes=function(){const s=B.state;if(!s)return; (s.locations||[]).forEach(l=>{l.residents=[];l.employees=[];l.visitors=[]}); const by=Object.fromEntries((s.locations||[]).map(l=>[l.id,l])); (s.npcs||[]).forEach(n=>{if(by[n.homeLocationId])by[n.homeLocationId].residents.push(n.id); if(by[n.workLocationId])by[n.workLocationId].employees.push(n.id); (n.schedule||[]).forEach(bl=>{if(by[bl.locationId]&&!by[bl.locationId].visitors.includes(n.id)) by[bl.locationId].visitors.push(n.id)})})}
B.currentDate=function(){const s=B.state; if(s?.clock?.live!==false) return new Date(); return s.clock?.manualISO?new Date(s.clock.manualISO):new Date();}
B.activeBlock=function(npc,date=B.currentDate()){const min=B.nowMinutes(date), day=date.getDay(), md=date.getDate(); if(npc.vacationPlan?.monthDays?.includes(md)){return {scenario:'vacation',label:`on ${npc.vacationPlan.purpose} in ${npc.vacationPlan.settlement}, ${npc.vacationPlan.province}`,locationName:`${npc.vacationPlan.settlement}, ${npc.vacationPlan.province}`,away:true,icon:'🎒',x:94,y:10,mode:npc.vacationPlan.mode?.mode||'travel'}}
 if(npc.workTripPlan&&npc.workTripPlan.weekday===day&&min>=B.timeToMin(npc.workTripPlan.start)&&min<B.timeToMin(npc.workTripPlan.end)){return {scenario:'travel_work',label:`work trip for ${npc.workTripPlan.purpose}`,locationName:`${npc.workTripPlan.settlement}, ${npc.workTripPlan.province}`,away:true,icon:'💼',x:92,y:18,mode:npc.workTripPlan.mode?.mode||'travel'}}
 const blocks=npc.schedule||[]; for(const bl of blocks){if(!(bl.days||[]).includes(day)) continue; const st=B.timeToMin(bl.start), en=B.timeToMin(bl.end); if(st<en && min>=st&&min<en) return {...bl,progress:(min-st)/(en-st)}; if(st>en && (min>=st||min<en)) return {...bl,progress:min>=st?(min-st)/(1440-st+en):(1440-st+min)/(1440-st+en)};}
 return blocks.find(b=>b.scenario==='home')||{scenario:'home',label:'at home',locationName:npc.homeLocationName,locationId:npc.homeLocationId,icon:'🏠'};}
B.npcPosition=function(npc,date=B.currentDate()){const bl=B.activeBlock(npc,date); const locs=Object.fromEntries((B.state.locations||[]).map(l=>[l.id,l])); if(bl.away) return {...bl,x:bl.x,y:bl.y}; if(bl.scenario==='transit'&&bl.fromId&&bl.toId){const a=locs[bl.fromId]||locs[npc.homeLocationId]||{x:50,y:50}, b=locs[bl.toId]||locs[bl.locationId]||{x:50,y:50}; const ax=Number(a.x??50), ay=Number(a.y??50), bx=Number(b.x??50), by=Number(b.y??50); const p=Math.max(0,Math.min(1,bl.progress||0)); return {...bl,x:ax+(bx-ax)*p,y:ay+(by-ay)*p};}
 const loc=locs[bl.locationId]||locs[npc.homeLocationId]||{x:50,y:50}; return {...bl,x:loc.x,y:loc.y};}
B.updateNpcCurrents=function(){(B.state?.npcs||[]).forEach(n=>{const pos=B.npcPosition(n); n.current={scenario:pos.scenario,locationName:pos.locationName,label:pos.label,x:pos.x,y:pos.y,icon:pos.icon,away:!!pos.away,mode:pos.mode||''};});}
B.log=function(msg){B.state.log=B.state.log||[]; B.state.log.unshift({at:new Date().toISOString(),message:msg}); B.state.log=B.state.log.slice(0,80)}
})();
