
(function(){
  const U = window.BelavadosUtils;
  const R = {page:{locations:0,npcs:0,relationships:0,travel:0}, pageSize:80, activeTab:'overview', editor:null};
  R.setStateRefs = function(core, getState, setState){ R.core=core; R.getState=getState; R.setState=setState; };
  R.renderAll = function(){ const state=R.getState(); const filter=(U.$('filterInput')?.value||'').toLowerCase(); R.renderOverview(state); R.renderLocations(state, filter); R.renderNPCs(state, filter); R.renderRelationships(state, filter); R.renderTravel(state, filter); R.renderMap(state); R.renderImports(state); U.$('json').textContent=JSON.stringify(state,null,2); U.$('resultCount').textContent=`${state.locations.length} locations · ${state.npcs.length} NPCs · ${state.relationships.length} relationships · ${state.travel.length} travel records`; };
  R.renderOverview = function(state){
    const s=state.settings||{}; const byCat=countBy(state.locations,'category'); const byRace=countBy(state.npcs,'raceCategory'); const rareLocations=state.locations.filter(l=>String(l.tags||'').includes('5%')).length; const moving=state.travel.length; const cacheCount=(state.raceCache||[]).length; const worldAccess=state.npcs.filter(n=>n.worldTravelAccess==='entire-world').length;
    U.$('overview').innerHTML = `<div class="statline"><div class="stat"><b>${U.escapeHTML(s.scopeMode||'none')}</b> scope</div><div class="stat"><b>${state.locations.length}</b> locations</div><div class="stat"><b>${state.npcs.length}</b> NPCs</div><div class="stat"><b>${state.relationships.length}</b> relationships</div><div class="stat"><b>${moving}</b> travelers</div><div class="stat"><b>${rareLocations}</b> rare location variations</div></div>
    <div class="widegrid"><div class="item"><h3>${U.escapeHTML(s.scopeMode==='world'?'Belavadös Whole World':(s.settlementName||s.province||'No settlement generated'))}<small>${U.escapeHTML(s.scopeMode==='world'?'Every province and settlement':((s.province||'')+' · '+(s.settlementType||'')))}</small></h3><div class="mini">Biome: ${U.escapeHTML(s.biome||'')}<br>Government: ${U.escapeHTML(s.governmentType||'')}<br>Danger: ${U.escapeHTML(s.dangerLevel||'')}<br>Time zone: ${U.escapeHTML(s.timezone||'')}<br>Population: ${U.escapeHTML(s.population||'')} · Area: ${U.escapeHTML(s.area||'')}</div><div class="tags">${(s.tags||[]).map(t=>`<span class="tag">${U.escapeHTML(t)}</span>`).join('')}</div></div><div class="item"><h3>Location Categories</h3>${miniBars(byCat)}</div><div class="item"><h3>Race Families</h3>${miniBars(byRace)}</div><div class="item"><h3>Race Cache + World Travel</h3><div class="mini"><b>${cacheCount}</b> cached race${cacheCount===1?'':'s'} available for generation.<br><b>${worldAccess}</b> NPC${worldAccess===1?'':'s'} currently have entire-world travel access.</div><div class="tags">${(state.raceCache||[]).slice(0,12).map(r=>`<span class="tag cyan">${U.escapeHTML(r.label)}</span>`).join('')}</div></div><div class="item"><h3>Persistence + Export</h3><div class="mini">Current state is kept in memory and can be saved to browser storage. Importing a prior export restores NPCs, relationships, schedules, travel histories, locations, race cache, and GeoJSON without regeneration.</div></div></div>`;
  };
  R.renderLocations = function(state, filter){ const rows=state.locations.filter(l=>match(l,filter)); renderPaged('locations', rows, R.page.locations, locCard, 'locations'); };
  R.renderNPCs = function(state, filter){ const rows=state.npcs.filter(n=>match(n,filter)); renderPaged('npcs', rows, R.page.npcs, npcCard, 'npcs'); };
  R.renderRelationships = function(state, filter){ const rows=state.relationships.filter(r=>match(r,filter)); renderPaged('relationships', rows, R.page.relationships, relCard, 'relationships'); };
  R.renderTravel = function(state, filter){ const rows=state.travel.filter(t=>match(t,filter)); renderPaged('travel', rows, R.page.travel, travelCard, 'travel'); };
  R.renderMap = function(state){
    const features=(state.geojson?.features||[]).slice(0,1200);
    const circles=features.map(f=>{const [x,y]=f.geometry.coordinates; return `<circle cx="${x}%" cy="${y}%" r="2" fill="${f.properties.hex||'#00ffff'}" stroke="#101417" stroke-width=".6"><title>${U.escapeHTML(f.properties.name)}</title></circle>`;}).join('');
    const img=state.mapImage?.dataUrl?`<div class="map-preview"><img src="${state.mapImage.dataUrl}" alt="Uploaded map image preview"></div>`:`<div class="map-preview"><div class="mini">No map image uploaded. GeoJSON shell pins are shown below using percentage coordinates.</div></div>`;
    U.$('map').innerHTML=`<div class="widegrid"><div class="item"><h3>Uploaded Map</h3>${img}</div><div class="item"><h3>GeoJSON/SVG Pin Shell Preview</h3><svg class="svg-map" viewBox="0 0 100 100" preserveAspectRatio="none"><rect x="0" y="0" width="100" height="100" fill="#061015"/>${circles}</svg><div class="mini">Showing up to 1,200 pins at 2px radius. Full GeoJSON is preserved in exports.</div></div></div><div class="item codebox">${U.escapeHTML(JSON.stringify(state.geojson,null,2))}</div>`;
  };
  R.renderImports = function(state){
    U.$('imports').innerHTML = state.imports?.length ? `<div class="grid">${state.imports.map(im=>`<div class="item"><h3>${U.escapeHTML(im.name)}<small>${U.escapeHTML(im.kind)}</small></h3><div class="mini">${U.escapeHTML(im.summary||'Imported source')}<br>${(im.warnings||[]).map(w=>U.escapeHTML(w)).join('<br>')}</div><div class="tags">${(im.detectedTags||[]).map(t=>`<span class="tag">${U.escapeHTML(t)}</span>`).join('')}</div></div>`).join('')}</div>` : '<div class="notice">No imports yet.</div>';
  };
  function renderPaged(containerId, rows, page, cardFn, type){
    const start=page*R.pageSize, slice=rows.slice(start,start+R.pageSize), totalPages=Math.max(1,Math.ceil(rows.length/R.pageSize));
    U.$(containerId).innerHTML = `<div class="grid">${slice.map(cardFn).join('')}</div><div class="pagination"><button class="secondary small" data-page="${type}" data-dir="-1">Previous</button><span class="mini">Page ${page+1} of ${totalPages}; showing ${slice.length} of ${rows.length}</span><button class="secondary small" data-page="${type}" data-dir="1">Next</button></div>`;
  }
  function locCard(l){ return `<div class="item"><h3>${U.escapeHTML(l.name)}<small>${U.escapeHTML(l.category)} · ${U.escapeHTML(l.subcategory)}</small></h3><div class="mini">${U.escapeHTML(l.description)}</div><div class="tags"><span class="tag cyan">${U.escapeHTML(l.overlayColor)}</span><span class="tag" style="border-color:${l.hex};color:${l.hex}">${U.escapeHTML(l.hex)}</span>${(l.tags||[]).slice(0,4).map(t=>`<span class="tag">${U.escapeHTML(t)}</span>`).join('')}</div><div class="split"><div class="box"><strong>Employees</strong><br>${(l.employees||[]).slice(0,5).map(e=>U.escapeHTML(e.name)).join('<br>')||'None assigned'}</div><div class="box"><strong>Visitors</strong><br>${(l.visitors||[]).slice(0,5).map(v=>U.escapeHTML(v.name)).join('<br>')||'None shown'}</div></div><div class="btns" style="margin-top:10px"><button class="secondary small" data-edit="location" data-id="${l.id}">Edit</button><button class="secondary small" data-reroll="location" data-part="entire" data-id="${l.id}">Reroll Location</button></div></div>`; }
  function npcCard(n){ return `<div class="item"><h3>${U.escapeHTML(n.name)}<small>${U.escapeHTML(n.race)} · ${U.escapeHTML(n.genderIdentity)} · ${U.escapeHTML(n.pronouns)}</small></h3><div class="mini">${U.escapeHTML(n.personality)}<br><b>Alignment:</b> ${U.escapeHTML(n.alignment?.summary||'')}<br><b>Home:</b> ${U.escapeHTML(n.residence)}<br><b>Work:</b> ${U.escapeHTML(n.employment)} as ${U.escapeHTML(n.socialRole)}</div><div class="tags">${(n.traits||[]).slice(0,6).map(t=>`<span class="tag">${U.escapeHTML(t)}</span>`).join('')}${n.travelPlan?.active?'<span class="tag ok">Traveling</span>':''}${n.worldTravelAccess==='entire-world'?'<span class="tag cyan">World access</span>':''}${n.generatedFromRaceCache?'<span class="tag violet">Race cache</span>':''}</div><div class="btns" style="margin-top:10px"><button class="secondary small" data-edit="npc" data-id="${n.id}">Edit</button><button class="secondary small" data-reroll="npc" data-part="entire" data-id="${n.id}">Reroll NPC</button></div></div>`; }
  function relCard(r){ return `<div class="item"><h3>${U.escapeHTML(r.fromName)} ↔ ${U.escapeHTML(r.toName)}<small>${U.escapeHTML(r.layer)}</small></h3><div class="mini">${U.escapeHTML(r.label)} / ${U.escapeHTML(r.reciprocalLabel)}<br>${U.escapeHTML(r.notes||'')}</div><div class="tags">${(r.settlements||[]).map(s=>`<span class="tag">${U.escapeHTML(s)}</span>`).join('')}</div></div>`; }
  function travelCard(t){ return `<div class="item"><h3>${U.escapeHTML(t.npcName)}<small>${U.escapeHTML(t.mode)} · ${U.escapeHTML(t.reason)}</small></h3><div class="mini">${U.escapeHTML(t.origin)}, ${U.escapeHTML(t.originProvince)} → ${U.escapeHTML(t.destination)}, ${U.escapeHTML(t.destinationProvince)}<br>Departure: ${U.escapeHTML(t.departure)} · Return: ${U.escapeHTML(t.returnWindow)}</div><div class="tags"><span class="tag cyan">${U.escapeHTML(t.travelAccess||'scope-limited')}</span>${t.visibleOnWorldMap?'<span class="tag ok">World-map visible</span>':''}</div></div>`; }
  function miniBars(obj){ const entries=Object.entries(obj).sort((a,b)=>b[1]-a[1]).slice(0,12); return entries.map(([k,v])=>`<div class="mini"><b>${U.escapeHTML(k)}</b>: ${v}</div>`).join('') || '<div class="mini">None yet</div>'; }
  function countBy(rows,key){ return rows.reduce((a,r)=>{const k=r[key]||'Unknown'; a[k]=(a[k]||0)+1; return a;},{}); }
  function match(obj, filter){ return !filter || JSON.stringify(obj).toLowerCase().includes(filter); }
  R.handleClick = function(e){
    const pg=e.target.closest('[data-page]'); if(pg){ const type=pg.dataset.page; const rows=R.getState()[type]||[]; const totalPages=Math.max(1,Math.ceil(rows.length/R.pageSize)); R.page[type]=Math.max(0,Math.min(totalPages-1,(R.page[type]||0)+Number(pg.dataset.dir))); R.renderAll(); return; }
    const edit=e.target.closest('[data-edit]'); if(edit){ R.openEditor(edit.dataset.edit, edit.dataset.id); return; }
    const reroll=e.target.closest('[data-reroll]'); if(reroll){ R.reroll(reroll.dataset.reroll, reroll.dataset.id, reroll.dataset.part); }
  };
  R.openEditor = function(type,id){ const state=R.getState(); const arr=type==='location'?state.locations:state.npcs; const rec=arr.find(x=>x.id===id); if(!rec)return; R.editor={type,id}; U.$('editorTitle').textContent=`Edit ${type}: ${rec.name}`; U.$('editorText').value=JSON.stringify(rec,null,2); U.$('editorBackdrop').classList.add('open'); };
  R.saveEditor = function(){ const state=R.getState(); if(!R.editor)return; let data; try{data=JSON.parse(U.$('editorText').value);}catch(err){U.status('JSON edit failed: '+err.message); return;} const arr=R.editor.type==='location'?state.locations:state.npcs; const idx=arr.findIndex(x=>x.id===R.editor.id); if(idx>=0) arr[idx]=data; R.setState(state); U.$('editorBackdrop').classList.remove('open'); R.renderAll(); U.status('Saved selected record only.'); };
  R.reroll = function(type,id,part='entire'){ const state=R.getState(); if(type==='location'){ const idx=state.locations.findIndex(x=>x.id===id); if(idx>=0) state.locations[idx]=R.core.rerollLocation(state.locations[idx],part); } else { const idx=state.npcs.findIndex(x=>x.id===id); if(idx>=0) state.npcs[idx]=R.core.rerollNPC(state.npcs[idx],part); } R.setState(state); R.renderAll(); U.status(`Rerolled selected ${type} only.`); };
  window.BelavadosRenderers = R;
})();
