
(function(){
const U=BelUtils;
const STORE='belavados_player_map_site_v1';
const App={data:null,state:{settlements:[],selectedId:null},uploadedSettlements:[],currentSettlement(){return (this.state.settlements||[]).find(s=>s.id===this.state.selectedId)||this.state.settlements?.[0]||null;},saveLocal(){localStorage.setItem(STORE,JSON.stringify(this.state));},loadLocal(){try{const s=JSON.parse(localStorage.getItem(STORE)||'null'); if(s&&Array.isArray(s.settlements)) this.state=s;}catch(e){}},upsertSettlement(s,select=true){if(!s)return; s.id=s.id||U.slug(`${s.province}-${s.settlementName}`); const i=this.state.settlements.findIndex(x=>x.id===s.id); if(i>=0)this.state.settlements[i]=s; else this.state.settlements.push(s); if(select)this.state.selectedId=s.id; this.saveLocal(); populateSelectors(this);},renderAll(){BelPlayer.render(this); BelDM.render(this); BelTime.render(this.data,this.currentSettlement());}}
function mode(){return location.hash==='#dm-editor'?'dm':'player';}
function setupMode(){const dm=mode()==='dm'; document.body.classList.toggle('dm-mode',dm); document.body.classList.toggle('player-mode',!dm); U.$('siteTitle').textContent=dm?'Belavadös Hidden DM Settlement Editor':'Belavadös Player Settlement Map'; U.$('modeChip').textContent=dm?'DM Editor Mode':'Player Mode';}
function populateSelectors(app){const provs=Object.keys(app.data.settlementsByProvince||{}).filter(p=>(app.data.settlementsByProvince[p]||[]).length || app.state.settlements.some(s=>s.province===p)).sort(); const allProvs=U.uniq(provs.concat(Object.keys(app.data.provinceByName||{}))).sort(); ['provinceSelect','dmProvinceSelect'].forEach(id=>{const el=U.$(id); if(el) el.innerHTML=allProvs.map(p=>`<option>${U.esc(p)}</option>`).join('');}); const current=app.currentSettlement(); if(current){U.$('provinceSelect').value=current.province; U.$('dmProvinceSelect').value=current.province;}
 populateSettlementDropdown(app); const biome=U.$('dmBiomeSelect'); if(biome) biome.innerHTML=(app.data.biomes||[]).map(b=>`<option>${U.esc(b)}</option>`).join(''); syncDMFields(app);}
function populateSettlementDropdown(app){const prov=U.$('provinceSelect')?.value || U.$('dmProvinceSelect')?.value || Object.keys(app.data.settlementsByProvince)[0]; const saved=app.state.settlements.filter(s=>s.province===prov); const defaults=(app.data.settlementsByProvince[prov]||[]).filter(d=>!saved.some(s=>s.settlementName===d.settlementName)); const merged=saved.concat(defaults); const sel=U.$('settlementSelect'); if(sel){sel.innerHTML=merged.map(s=>`<option value="${U.esc(s.id)}">${U.esc(s.settlementName)}</option>`).join(''); if(app.state.selectedId&&merged.some(s=>s.id===app.state.selectedId)) sel.value=app.state.selectedId; else if(merged[0]) sel.value=merged[0].id;}
 const opt=merged.find(s=>s.id===(sel?.value)); if(opt && !app.state.settlements.some(s=>s.id===opt.id)){const full=BelGenerator.generateSettlement(app.data,{province:opt.province,settlementName:opt.settlementName,size:opt.size||opt.settlementType||'Town',biome:opt.biome||'Grassland Plains',governmentType:opt.governmentType,dangerLevel:opt.dangerLevel,alignmentPreference:opt.alignmentPreference,tags:(opt.tags||[]).join(', '),locationCount:Math.min(80,opt.settlementType==='Capital City'?120:opt.settlementType==='City'?90:50),npcCount:Math.min(180,opt.settlementType==='Capital City'?240:opt.settlementType==='City'?180:100),timeZone:opt.timeZone,displayTimeZones:opt.displayTimeZones}); app.upsertSettlement(full,true); return;} if(opt){app.state.selectedId=opt.id; app.saveLocal();}}
function syncDMFields(app){const s=app.currentSettlement(); if(!s)return; const ids={dmSettlementName:s.settlementName,dmSettlementSize:s.size||s.settlementType,dmBiomeSelect:s.biome,dmGovernmentType:s.governmentType,dmDanger:s.dangerLevel,dmAlignmentPref:s.alignmentPreference,dmTags:(s.tags||[]).join(', '),dmLocationCount:(s.locations||[]).length||60,dmNpcCount:(s.npcs||[]).length||120}; Object.entries(ids).forEach(([id,val])=>{const el=U.$(id); if(el&&val!=null)el.value=val;});}
function wireTabs(){U.$$('.page-tabs').forEach(nav=>nav.addEventListener('click',e=>{const btn=e.target.closest('[data-page]'); if(!btn)return; const group=nav.id==='dmTabs'?'dm-only':'player-only'; U.$$(`.page.${group}`).forEach(p=>p.classList.toggle('active',p.id===btn.dataset.page)); U.$$('#'+nav.id+' .page-tab').forEach(b=>{b.classList.toggle('active',b===btn); b.classList.toggle('secondary',b!==btn);});}));}
function wireSelectors(app){U.$('provinceSelect')?.addEventListener('change',()=>{populateSettlementDropdown(app); app.renderAll(); syncDMFields(app);}); U.$('settlementSelect')?.addEventListener('change',()=>{app.state.selectedId=U.$('settlementSelect').value; app.saveLocal(); syncDMFields(app); app.renderAll();}); U.$('dmProvinceSelect')?.addEventListener('change',()=>{const p=U.$('dmProvinceSelect').value; U.$('provinceSelect').value=p; populateSettlementDropdown(app); syncDMFields(app); app.renderAll();});}
async function init(){setupMode(); BelNav.init(); wireTabs(); App.data=await BelData.loadAll(); App.loadLocal(); (App.data.playerSettlements?.settlements||[]).forEach(s=>{if(!App.state.settlements.some(x=>x.id===s.id)) App.state.settlements.push(s);}); if(!App.state.settlements.length){const seed=App.data.defaultSettlements.find(s=>s.province==='Aelvanyr'&&s.settlementName==='Elarvess')||App.data.defaultSettlements[0]; const s=BelGenerator.generateSettlement(App.data,{province:seed.province,settlementName:seed.settlementName,size:seed.size,biome:seed.biome,governmentType:seed.governmentType,dangerLevel:seed.dangerLevel,alignmentPreference:seed.alignmentPreference,tags:(seed.tags||[]).join(', '),locationCount:90,npcCount:160,timeZone:seed.timeZone,displayTimeZones:seed.displayTimeZones}); App.upsertSettlement(s,true);} populateSelectors(App); wireSelectors(App); BelMap.init(App); BelPlayer.init(App); BelDM.init(App); BelTime.init(App); App.renderAll(); window.BelApp=App; window.addEventListener('hashchange',()=>{setupMode(); App.renderAll();});}
document.addEventListener('DOMContentLoaded',init);
})();
