
(function(){
const U=BelUtils;
function bundle(app){return {schema:'belavados.player.map.bundle.v1',updatedAt:new Date().toISOString(),settlements:app.state.settlements||[]};}
function downloadCurrent(app){const s=app.currentSettlement(); if(!s)return U.toast('No settlement selected.'); U.download(`${U.slug(s.province+'-'+s.settlementName)}.json`,JSON.stringify(s,null,2),'application/json');}
async function downloadDataZip(app){const b=bundle(app); if(window.JSZip){const zip=new JSZip(); zip.file('data/player_settlements.json',JSON.stringify(b,null,2)); zip.file('README.txt',`Upload data/player_settlements.json beside belavados_map_PLAYER.html, or import it in DM mode. Player URL: belavados_map_PLAYER.html\nDM URL: belavados_map_PLAYER.html#dm-editor\n`); const blob=await zip.generateAsync({type:'blob'}); U.download('belavados_player_map_data.zip',blob);} else U.download('player_settlements.json',JSON.stringify(b,null,2),'application/json');}
function locationCSV(app){const s=app.currentSettlement(); if(!s)return; const rows=[['id','name','category','kind','itemsForSale','employees','visitors','residents','notes','x','y']]; (s.locations||[]).forEach(l=>rows.push([l.id,l.name,l.category,l.kind,(l.itemsForSale||[]).join('; '),(l.employees||[]).join('; '),(l.visitors||[]).join('; '),(l.residents||[]).join('; '),l.notes,l.x,l.y])); U.download(`${U.slug(s.settlementName)}_locations.csv`,U.csv(rows),'text/csv');}
function npcCSV(app){const s=app.currentSettlement(); if(!s)return; const rows=[['id','name','race','raceCategory','genderIdentity','pronouns','traits','rumors','home','work','role','familial','romantic','personal','professional','alignment']]; (s.npcs||[]).forEach(n=>rows.push([n.id,n.name,n.race,n.raceCategory,n.genderIdentity,n.pronouns,(n.traits||[]).join('; '),(n.rumors||[]).join('; '),n.homeLocationName,n.workLocationName,n.workplaceRole,(n.relationships?.familial||[]).map(r=>r.npcName+': '+r.type).join('; '),(n.relationships?.romantic||[]).map(r=>r.npcName+': '+r.type).join('; '),(n.relationships?.personal||[]).map(r=>r.npcName+': '+r.type).join('; '),(n.relationships?.professional||[]).map(r=>r.npcName+': '+r.type).join('; '),n.alignment?.summary||''])); U.download(`${U.slug(s.settlementName)}_npcs.csv`,U.csv(rows),'text/csv');}
window.BelExport={bundle,downloadCurrent,downloadDataZip,locationCSV,npcCSV};
})();
