(function(){
const U=BelUtils;
const FIRST=['Ael','Vael','Thal','Mir','Zha','Khar','Lun','Syl','Dra','Fen','Ner','Oth','Vel','Myr','Qel','Ith','Fael','Bryn','Cae','Riven','Mor','Zal','Vor','Elar','Ash','Ssz','Velk','Ish','Nym','Ora','Ul'];
const MID=['ar','eth','wyn','or','un','iel','ael','vyr','thas','mora','drin','rith','skel','av','oryn','esh','ira','zun','ethra','ovar','uin'];
const LAST=['thorn','vale','mere','voss','kair','dell','bloom','wake','forge','mire','glen','barrow','river','spire','whisper','gallow','frost','vandra','loom','harrow','crest'];
const GENDERS=[
 ['Cis-Male','he/him'],['Cis-Female','she/her'],['Demi-Male','he/they'],['Demi-Female','she/they'],['Non-Binary','they/them'],['Trans-Male','he/him'],['Trans-Female','she/her'],['Gender-Fluid','they/she/he'],['Agender','they/them'],['Gender-Less','they/them'],['Gender-Flexible','they/any'],['Bi-Gender','they/he/she'],['Poly-Gender','they/any'],['Neutrois','they/them']
];
const AGE_STAGES=['elder','adult','adult','adult','young adult','young adult','teen','child'];
const TRAITS=['curious','haunted','practical','bold','soft-spoken','jovial','secretive','protective','calculating','romantic','reckless','studious','superstitious','patient','vengeful','generous','stubborn','dream-haunted','family-centered','community-minded','ambitious','loyal','messy','perfectionist','animal-loving','night owl','early riser','hot-headed','playful','bookish','craft-obsessed'];
const RUMORS=['owes a dangerous favor','knows a hidden tunnel','saw something move under the old stones','keeps a forbidden ledger copy','is protecting a runaway','once worked for the transit authority','has a divine-prison rumor','is being courted by a guild','knows where black-market goods surface','survived a failed skyship landing','secretly funds a neighbor through hard times','has a complicated family inheritance dispute','was seen arguing near the docks','hosts weekly family dinners','keeps a careful visitor log'];
const RELTYPES={
 familial:['Parent','Child','Sibling','Grandparent','Grandchild','Cousin','Aunt','Uncle','Niece','Nephew',"Parent's sibling","Sibling's child",'Half-sibling','Step-parent','Step-child','Step-sibling','Adoptive parent','Adoptive child','Foster parent','Foster child','Guardian','Ward','Extended family member','Chosen family'],
 romantic:['Romantic partner','Fiancé','Spouse','Ex partner','Ex spouse','Long-term partner','Dating partner','Primary partner','Secondary partner','Courtship partner'],
 professional:['Employer','Employee','Coworker','Colleague','Supervisor','Subordinate','Manager','Assistant','Apprentice','Mentor','Teacher','Student','Business partner','Contractor','Client','Customer','Supplier','Merchant contact','Trade contact','Guild member','Guild leader','Guild associate','Fellow guard','Fellow priest','Fellow scholar','Fellow artisan','Rival professional','Competitor','Partner in trade'],
 personal:['Friend','Close friend','Best friend','Acquaintance','Neighbor','Rival','Enemy','Frenemy','Confidant','Drinking companion','Travel companion','Protector','Protected person','Benefactor','Debtor','Creditor','Ally','Political ally','Political rival','Informant','Confessor','Companion','Trusted contact','Social peer','Former friend','Estranged acquaintance']
};
const ROMANTIC_STATUS=['Single','Dating','Monogamous Dating','Polyamorous Dating','Engaged','Monogamous Engaged','Polyamorous Engaged','Married','Monogamous Married','Polyamorous Married','Separated','Divorced','Widowed'];
const EMOTIONS=['supportive','warm','tense','hostile','neutral','protective','affectionate','suspicious','loyal','competitive','complicated'];
const VISIBILITY=['public','private','known to household','known at work','rumored','secret'];
const CONFLICT=['none','low','moderate','high','old wound','active feud'];
const DEPENDENCY=['none','minor','mutual','economic','emotional','political','protective','household'];
function name(rng){const first=U.sample(FIRST,rng)+U.sample(MID,rng)+(rng()<.35?U.sample(MID,rng):''); const last=U.sample(FIRST,rng)+U.sample(LAST,rng); return first+' '+last;}
function pickTemplate(data,size,biome){const all=data.generatorData.settlementTypes||[]; let matches=all.filter(t=>t.size===size && ((t.terrain+' '+t.variant).toLowerCase().includes(String(biome||'').toLowerCase()) || String(biome||'').toLowerCase().includes(String(t.terrain||'').toLowerCase()))); if(!matches.length) matches=all.filter(t=>t.size===size); if(!matches.length) matches=all; return U.sample(matches)||{locations:['Town hall','Tavern','General store','Blacksmith','Inn','Market'],size,terrain:biome,variant:biome};}
function classifyLocation(name){const n=String(name).toLowerCase(); if(/hall|court|government|guard|jail|ministry|permit|bureau|census|embassy|authority|palace|parliament|council|headquarters|precinct/.test(n)) return 'government'; if(/market|store|shop|bazaar|exchange|emporium|auction|tailor|bakery|butcher|armory|weapon|blacksmith|apothecary|alchemy|furniture|jewel|food|restaurant|bank|mint/.test(n)) return 'market'; if(/ruin|sewer|black market|pirate|smuggler|prison|cult|danger|undercity|lawless|quarantine|red-lantern/.test(n)) return 'danger'; if(/house|apartment|estate|lodging|room|inn|hotel|hostel|boarding|orphan|tenement|rowhouse|tower|quarters|housing/.test(n)) return 'residence'; return 'service';}
function categoryForLocation(name){const n=String(name).toLowerCase(); if(/tavern|inn|hotel|hostel|restaurant|tea|bakery|butcher|smoke|food|cook|cider|brew|cafe|kitchen/.test(n)) return 'Food, Drink, and Hospitality'; if(/store|market|provision|hardware|home|furniture|dry goods|houseware|department|emporium|bazaar|pawn|bank|mint/.test(n)) return 'Retail and Household Goods'; if(/blacksmith|armory|weapon|foundry|clockwork|artificer|carpenter|wood|glass|potter|tailor|leather|saddler|farrier|ship|boat|workshop|factory|manufactor/.test(n)) return 'Crafting and Industry'; if(/magic|wizard|scroll|library|archive|temple|shrine|monastery|arcane|ichor|worship|cathedral|university|academy|lore/.test(n)) return 'Magic, Religion, and Lore'; if(/apothecary|alchemy|hospital|clinic|healer|sanitarium|chirurgeon|poison|medical|dentist/.test(n)) return 'Health, Alchemy, and Apothecary'; if(/rail|ferry|dock|station|harbor|caravan|skyship|portal|freight|transit|coach|submarine|wharf|pier|terminal|rookery|messenger/.test(n)) return 'Transit and Logistics'; if(/government|town hall|court|guard|barracks|embassy|ministry|jail|prison|permit|bureau|authority|customs|census|palace|parliament|council|public works/.test(n)) return 'Civic, Law, and Administration'; return 'General Services';}
const defaultItems={
 'Food, Drink, and Hospitality':['breakfast','supper','ale','tea','coffee','private room','common room','travel rations','stew','fresh bread','bath','laundry'],
 'Retail and Household Goods':['rope','lantern','backpack','bedroll','soap','blanket','clothing','cookware','housewares','basic tools','torches','waterskin'],
 'Crafting and Industry':['dagger','sword','armor','shield','crossbow bolts','repair services','smithing tools','clockwork parts','wagon fittings','custom fitting'],
 'Magic, Religion, and Lore':['scroll','holy water','spell components','ritual ink','minor charm','lore research','prayer service','warding candle','archive access'],
 'Health, Alchemy, and Apothecary':['healing kit','potion','antitoxin','poison','bandages','elixir','apothecary herbs','medical care','splints'],
 'Transit and Logistics':['ticket','freight crate','mount boarding','wagon rental','ferry passage','skyship berth','caravan escort','messenger dispatch'],
 'Civic, Law, and Administration':['permit','license','court record','tax filing','guard report','settlement registry','public notice'],
 'General Services':['local guide','message delivery','map copy','rumor board','day labor','repair appointment']
};
function itemsFor(data,locName,size,biome,rng){const normal=U.normal(locName); const service=(data.generatorData.serviceItems||[]).filter(x=>normal.includes(U.normal(x.place||'')) || U.normal(x.place||'').includes(normal.split(' ')[0])).slice(0,16).map(x=>x.item); const cat=categoryForLocation(locName); let items=U.uniq(service.concat(defaultItems[cat]||defaultItems['General Services'])); if(/armory|weapon|blacksmith/i.test(locName)) items=U.uniq(items.concat(['dagger','shortsword','longsword','chain mail','shield','arrows','armor fitting'])); if(/inn|hotel|hostel|room/i.test(locName)) items=U.uniq(items.concat(['room','private room','common bunk','breakfast','bath','laundry'])); if(/market|general|provision/i.test(locName)) items=U.uniq(items.concat(['rope','rations','torches','waterskin','backpack','blanket','dagger'])); if(/stable|farrier|mount/i.test(locName)) items=U.uniq(items.concat(['mount boarding','saddle','feed','horse rental','aquatic mount rental'])); return items.sort(()=>rng()-.5).slice(0,14);}
function jobFor(loc,ageStage){if(ageStage==='child') return 'school child'; if(ageStage==='teen') return U.sample(['student','apprentice','runner','junior helper']); const n=String(loc).toLowerCase(); if(/tavern|inn|hotel|hostel|restaurant/.test(n)) return U.sample(['innkeeper','cook','server','hostler','bartender']); if(/guard|jail|barracks|peacekeeper/.test(n)) return U.sample(['guard','watch captain','detective','clerk','armorer']); if(/market|store|shop|bazaar/.test(n)) return U.sample(['shopkeeper','cash clerk','buyer','porter','vendor']); if(/blacksmith|armory|weapon/.test(n)) return U.sample(['smith','armorer','weaponsmith','apprentice']); if(/magic|wizard|scroll|arcane/.test(n)) return U.sample(['scribe','mage clerk','ritualist','apprentice wizard']); if(/hospital|clinic|healer|apothecary/.test(n)) return U.sample(['healer','apothecary','chirurgeon','nurse']); if(/school|university|academy|library/.test(n)) return U.sample(['teacher','student','librarian','lecturer','research assistant']); if(/temple|shrine|cathedral|monastery/.test(n)) return U.sample(['priest','caretaker','confessor','ritual aide']); return U.sample(['clerk','attendant','laborer','specialist','caretaker','runner']);}
function alignment(rng,pref){const axes=['Altruism','Lawfulness','Cooperation','Honor']; const obj={}; axes.forEach(a=>{const score=Math.round((750+rng()*1750)/250)*250; obj[a.toLowerCase()]={label:a,score,phase:score<1000?'low':score<2000?'neutral':'high'};}); obj.summary=pref||`${obj.altruism.phase} altruism / ${obj.lawfulness.phase} lawfulness / ${obj.cooperation.phase} cooperation / ${obj.honor.phase} honor`; return obj;}
function chooseHome(locations,rng){const homes=locations.filter(l=>l.kind==='residence'||/house|room|inn|hotel|hostel|apartment|boarding|estate|orphan|tenement|rowhouse|housing|quarters/i.test(l.name)); return U.sample(homes,rng)||U.sample(locations,rng);}
function chooseWork(locations,rng,ageStage){if(ageStage==='child'||ageStage==='teen') return U.sample(locations.filter(l=>/school|academy|university|library|orphan|home|house/i.test(l.name)),rng)||U.sample(locations,rng); return U.sample(locations.filter(l=>l.kind!=='residence'),rng)||U.sample(locations,rng);}
function makeSchedule(npc,locations,rng){const byId=id=>(locations||[]).find(l=>l.id===id); const home=byId(npc.homeLocationId)||U.sample(locations,rng); const work=byId(npc.workLocationId)||home; const visits=(npc.visitLocationIds||[]).map(byId).filter(Boolean); const social=visits[0]||U.sample(locations.filter(l=>/tavern|market|park|plaza|temple|bath|tea|food|square/i.test(l.name)),rng)||work; const errand=visits[1]||U.sample(locations.filter(l=>l.kind!=='residence'),rng)||social; const night=visits[2]||U.sample(locations.filter(l=>/tavern|inn|theater|casino|garden|district|park|friends/i.test(l.name)),rng)||home; const workStart= npc.traits?.includes('night owl') ? 11 : 8+Math.floor(rng()*2); const shiftLen=(npc.ageStage==='elder'?5:npc.ageStage==='young adult'?7:8); const weekday=[
  {time:'06:00',activity:'wake, breakfast, hygiene, household chores',locationId:home?.id,locationName:home?.name},
  {time:'08:00',activity:npc.ageStage==='child'||npc.ageStage==='teen'?'commute to school/apprenticeship':'commute to work',locationId:work?.id,locationName:work?.name},
  {time:String(workStart).padStart(2,'0')+':00',activity:npc.ageStage==='child'?'classes, play, errands':'work shift, customers, coworkers',locationId:work?.id,locationName:work?.name},
  {time:'12:00',activity:'meal break and local gossip',locationId:social?.id,locationName:social?.name},
  {time:String(Math.min(19,workStart+shiftLen)).padStart(2,'0')+':00',activity:'errands, shopping, temple, guild, or civic stop',locationId:errand?.id,locationName:errand?.name},
  {time:'20:00',activity:'friends, romance, family dinner, hobbies, rumors',locationId:night?.id,locationName:night?.name},
  {time:'23:00',activity:'return home and sleep',locationId:home?.id,locationName:home?.name}
 ];
 const restday=[
  {time:'07:30',activity:'slow breakfast and household care',locationId:home?.id,locationName:home?.name},
  {time:'10:00',activity:'visit market, temple, friends, or family',locationId:social?.id,locationName:social?.name},
  {time:'13:00',activity:'community event, hobby, date, rivalry encounter, or guild errand',locationId:errand?.id,locationName:errand?.name},
  {time:'17:00',activity:'family tree check-in, shared meal, caretaking, or neighborhood talk',locationId:home?.id,locationName:home?.name},
  {time:'21:00',activity:'night social circle or quiet home routine',locationId:night?.id,locationName:night?.name},
  {time:'23:30',activity:'sleep',locationId:home?.id,locationName:home?.name}
 ];
 npc.schedule={style:'Sims-like autonomous weekly routine',weekday,restday,weekly:{Monday:'work/school + errands',Tuesday:'work/school + friends',Wednesday:'Belavadös rest day: family/community/social networks',Thursday:'work/school + guild or temple',Friday:'work/school + romance or rivals',Saturday:'market/community/social',Sunday:'home/family/rest'} };
 npc.movementProfile={currentLocationId:home?.id,currentLocationName:home?.name,updateCadenceMinutes:U.sample([10,15,20,30,45],rng),visitRotation:[home?.id,work?.id,social?.id,errand?.id,night?.id].filter(Boolean),behavior:'Moves between home, work, errands, friends, romance, rivals, worship, shopping, meals, and social events like a Sims-style autonomous resident.'};
}
function makeNPC(data,rng,idx,locations,opts={}){const cat=opts.raceCategory?data.raceCategories[Number(opts.raceCategory)]||U.sample(data.raceCategories,rng):U.sample(data.raceCategories,rng); const race=opts.race||U.sample(cat?.races||data.allRaces.map(r=>r.race),rng)||'Human'; const gender=U.sample(GENDERS,rng); const ageStage=opts.ageStage||U.sample(AGE_STAGES,rng); const home=chooseHome(locations,rng); const work=chooseWork(locations,rng,ageStage)||home; const visits=U.uniq([U.sample(locations,rng),U.sample(locations,rng),U.sample(locations,rng),U.sample(locations,rng)].map(l=>l?.id)).filter(id=>id!==home?.id&&id!==work?.id); const npc={id:`npc_${idx}`,name:name(rng),race,raceCategory:cat?.category||'Mixed',genderIdentity:gender[0],pronouns:gender[1],ageStage,relationshipStatus:'Single',romanticStructure:'none',traits:U.uniq([U.sample(TRAITS,rng),U.sample(TRAITS,rng),U.sample(TRAITS,rng),U.sample(TRAITS,rng)]).slice(0,4),rumors:[U.sample(RUMORS,rng),U.sample(RUMORS,rng)],homeLocationId:home?.id,homeLocationName:home?.name,workLocationId:work?.id,workLocationName:work?.name,workplaceRole:jobFor(work?.name||'',ageStage),visitLocationIds:visits,alignment:alignment(rng,opts.alignmentPreference),relationships:{familial:[],romantic:[],personal:[],professional:[]},familyTree:{parents:[],children:[],siblings:[],partners:[],grandparents:[],grandchildren:[],extendedFamily:[],chosenFamily:[],householdMembers:[]},householdId:'',householdRole:'resident',socialNetwork:{friends:[],rivals:[],guilds:[],politicalGroups:[],communityOrganizations:[]}}; if(home) (home.residents ||= []).push(npc.id); if(work && npc.ageStage!=='child') (work.employees ||= []).push(npc.id); visits.forEach(id=>{const l=locations.find(x=>x.id===id); if(l)(l.visitors ||= []).push(npc.id);}); makeSchedule(npc,locations,rng); return npc;}
function reciprocal(type){const map={'Parent':'Child','Child':'Parent','Grandparent':'Grandchild','Grandchild':'Grandparent','Aunt':"Sibling's child",'Uncle':"Sibling's child",'Niece':"Parent's sibling",'Nephew':"Parent's sibling",'Step-parent':'Step-child','Step-child':'Step-parent','Adoptive parent':'Adoptive child','Adoptive child':'Adoptive parent','Foster parent':'Foster child','Foster child':'Foster parent','Guardian':'Ward','Ward':'Guardian','Employer':'Employee','Employee':'Employer','Supervisor':'Subordinate','Subordinate':'Supervisor','Manager':'Assistant','Assistant':'Manager','Teacher':'Student','Student':'Teacher','Mentor':'Apprentice','Apprentice':'Mentor','Client':'Contractor','Contractor':'Client','Customer':'Merchant contact','Merchant contact':'Customer','Supplier':'Trade contact','Trade contact':'Supplier','Protector':'Protected person','Protected person':'Protector','Benefactor':'Debtor','Debtor':'Benefactor','Creditor':'Debtor'}; return map[type]||type;}
function makeRel(cat,other,type,rng,overrides={}){return Object.assign({category:cat,npcId:other.id,npcName:other.name,type,status:overrides.status||'current',strength:overrides.strength||U.sample(['fragile','steady','intense','distant','trusted','deep','new'],rng),history:overrides.history||U.sample(['old tie','recent complication','publicly known','private secret','guild-recorded','childhood connection','household bond','shared crisis','workplace history'],rng),emotionalTone:overrides.emotionalTone||U.sample(EMOTIONS,rng),socialVisibility:overrides.socialVisibility||U.sample(VISIBILITY,rng),conflictLevel:overrides.conflictLevel||U.sample(CONFLICT,rng),dependencyLevel:overrides.dependencyLevel||U.sample(DEPENDENCY,rng),affection:overrides.affection??Math.round(rng()*100),trust:overrides.trust??Math.round(rng()*100),mutual:overrides.mutual!==false,relationshipStructure:overrides.relationshipStructure||''},overrides.extra||{});}
function addRel(a,b,cat,type,rng,overrides={}){if(!a||!b||a.id===b.id) return; a.relationships[cat] ||= []; b.relationships[cat] ||= []; if(!a.relationships[cat].some(r=>r.npcId===b.id&&r.type===type)) a.relationships[cat].push(makeRel(cat,b,type,rng,overrides)); const rtype=reciprocal(type); if(!b.relationships[cat].some(r=>r.npcId===a.id&&r.type===rtype)) b.relationships[cat].push(makeRel(cat,a,rtype,rng,overrides));}
function treePush(n,field,other){if(n?.familyTree?.[field] && other && !n.familyTree[field].some(x=>x.id===other.id)) n.familyTree[field].push({id:other.id,name:other.name});}
function buildHouseholds(npcs,locations,rng){const byHome={}; npcs.forEach(n=>{(byHome[n.homeLocationId||'unhoused'] ||= []).push(n);}); const households=[]; Object.entries(byHome).forEach(([homeId,group],hidx)=>{const home=locations.find(l=>l.id===homeId); const hid=`household_${hidx+1}`; const h={id:hid,name:`${home?.name||'Wandering'} Household ${hidx+1}`,residenceLocationId:homeId,residenceLocationName:home?.name||'Unhoused',members:group.map(n=>n.id),relationshipStructure:U.sample(['biological family','adoptive family','foster family','step family','chosen family','mixed extended household','polyamorous family household'],rng),notes:'Generated household with layered family/social ties.'}; households.push(h); group.forEach((n,i)=>{n.householdId=hid; n.householdRole=i===0?'household anchor':U.sample(['resident','relative','partner','ward','roommate','chosen family member','caretaker'],rng); n.familyTree.householdMembers=group.filter(o=>o.id!==n.id).map(o=>({id:o.id,name:o.name}));}); const adults=group.filter(n=>!['child','teen'].includes(n.ageStage)); const youths=group.filter(n=>['child','teen'].includes(n.ageStage));
  if(adults.length>=2 && rng()<.72){const partnerCount=Math.min(adults.length, rng()<.22?3:2); const partners=adults.slice(0).sort(()=>rng()-.5).slice(0,partnerCount); partners.forEach((a,i)=>partners.slice(i+1).forEach(b=>{const poly=partnerCount>2; const status=poly?U.sample(['Polyamorous Dating','Polyamorous Engaged','Polyamorous Married'],rng):U.sample(['Monogamous Dating','Monogamous Engaged','Monogamous Married','Married','Dating'],rng); const type=poly?U.sample(['Primary partner','Secondary partner','Long-term partner','Spouse'],rng):U.sample(['Romantic partner','Spouse','Long-term partner','Dating partner'],rng); a.relationshipStatus=status; b.relationshipStatus=status; a.romanticStructure=poly?'polyamorous':'monogamous'; b.romanticStructure=poly?'polyamorous':'monogamous'; addRel(a,b,'romantic',type,rng,{status:'current',relationshipStructure:poly?'polyamorous family network':'monogamous relationship',emotionalTone:'affectionate',dependencyLevel:'emotional'}); treePush(a,'partners',b); treePush(b,'partners',a);})); }
  youths.forEach(y=>{const guardians=adults.slice(0).sort(()=>rng()-.5).slice(0,Math.min(adults.length,rng()<.25?3:2)); if(guardians.length){guardians.forEach(g=>{const t=U.sample(['Parent','Adoptive parent','Foster parent','Guardian','Step-parent'],rng); addRel(g,y,'familial',t,rng,{emotionalTone:'protective',dependencyLevel:'household',socialVisibility:'public'}); treePush(y,'parents',g); treePush(g,'children',y);});} else if(group.length>1){const other=U.sample(group.filter(o=>o.id!==y.id),rng); addRel(other,y,'familial','Chosen family',rng,{dependencyLevel:'household'}); treePush(y,'chosenFamily',other); treePush(other,'chosenFamily',y);} });
  group.forEach((a,i)=>group.slice(i+1).forEach(b=>{if(!a.relationships.familial.some(r=>r.npcId===b.id) && rng()<.65){const type=a.ageStage===b.ageStage?U.sample(['Sibling','Half-sibling','Step-sibling','Cousin','Chosen family'],rng):U.sample(['Extended family member','Chosen family','Cousin'],rng); addRel(a,b,'familial',type,rng,{dependencyLevel:'household',socialVisibility:'public'}); if(/Sibling|sibling/.test(type)){treePush(a,'siblings',b);treePush(b,'siblings',a);} else {treePush(a,'extendedFamily',b);treePush(b,'extendedFamily',a);} }}));
 });
 // Cross-household extended family so isolated households still have roots.
 npcs.forEach(n=>{if(n.relationships.familial.length<2){const other=U.sample(npcs.filter(o=>o.id!==n.id&&o.householdId!==n.householdId),rng); if(other){addRel(n,other,'familial',U.sample(['Cousin','Extended family member','Chosen family'],rng),rng,{socialVisibility:'known to household'}); treePush(n,'extendedFamily',other); treePush(other,'extendedFamily',n);}}});
 return households;
}
function buildProfessionalNetworks(npcs,locations,rng){locations.forEach(loc=>{const staff=(loc.employees||[]).map(id=>npcs.find(n=>n.id===id)).filter(Boolean); if(!staff.length) return; const leader=staff.find(n=>/captain|manager|innkeeper|teacher|priest|healer|guild|head|chief|director|supervisor|clerk/.test(n.workplaceRole))||staff[0]; staff.forEach(n=>{n.socialNetwork.guilds ||= []; if(!n.socialNetwork.guilds.includes(loc.category)) n.socialNetwork.guilds.push(loc.category); if(n!==leader) addRel(leader,n,'professional',U.sample(['Employer','Supervisor','Manager','Mentor','Teacher','Guild leader'],rng),rng,{socialVisibility:'public',dependencyLevel:'economic',history:'workplace hierarchy'});}); staff.forEach((a,i)=>staff.slice(i+1,i+4).forEach(b=>{if(a!==b) addRel(a,b,'professional',U.sample(['Coworker','Colleague','Guild member','Fellow artisan','Business partner','Rival professional','Partner in trade'],rng),rng,{socialVisibility:'public',history:'shared workplace'});}));});}
function buildPersonalNetworks(npcs,locations,rng){npcs.forEach(n=>{const candidates=npcs.filter(o=>o.id!==n.id); const visits=new Set(n.visitLocationIds||[]); const local=candidates.filter(o=>o.homeLocationId===n.homeLocationId||o.workLocationId===n.workLocationId||(o.visitLocationIds||[]).some(id=>visits.has(id))); const pool=local.length?local:candidates; const count=2+Math.floor(rng()*4); for(let i=0;i<count;i++){const other=U.sample(pool,rng); if(!other) continue; const type=U.sample(RELTYPES.personal,rng); addRel(n,other,'personal',type,rng,{status:type.startsWith('Former')?'former':'current'}); if(/friend|companion|confidant|ally|peer/i.test(type) && !n.socialNetwork.friends.includes(other.id)) n.socialNetwork.friends.push(other.id); if(/rival|enemy|frenemy/i.test(type) && !n.socialNetwork.rivals.includes(other.id)) n.socialNetwork.rivals.push(other.id);}
  if(rng()<.28){const adultPool=pool.filter(o=>!['child','teen'].includes(o.ageStage)&&!['child','teen'].includes(n.ageStage)); const other=U.sample(adultPool,rng); if(other){const poly=rng()<.35; const status=poly?U.sample(['Polyamorous Dating','Polyamorous Engaged','Polyamorous Married'],rng):U.sample(['Dating','Engaged','Married','Separated','Divorced','Widowed'],rng); const type=status.includes('Divorced')||status.includes('Separated')?U.sample(['Ex partner','Ex spouse'],rng):poly?U.sample(['Primary partner','Secondary partner','Dating partner','Long-term partner'],rng):U.sample(['Romantic partner','Fiancé','Spouse','Dating partner','Long-term partner'],rng); n.relationshipStatus=status; other.relationshipStatus=other.relationshipStatus==='Single'?status:other.relationshipStatus; n.romanticStructure=poly?'polyamorous':(status.includes('Married')||status.includes('Dating')||status.includes('Engaged')?'monogamous':n.romanticStructure); addRel(n,other,'romantic',type,rng,{status:status.includes('Divorced')||status.includes('Separated')?'former':'current',relationshipStructure:poly?'polyamorous network':'gender-neutral relationship',emotionalTone:status.includes('Separated')?'tense':'affectionate'}); treePush(n,'partners',other); treePush(other,'partners',n);}}
 });}
function connectNPCs(npcs,rng,locations=[]){npcs.forEach(n=>{n.relationships={familial:[],romantic:[],personal:[],professional:[]}; n.familyTree ||= {parents:[],children:[],siblings:[],partners:[],grandparents:[],grandchildren:[],extendedFamily:[],chosenFamily:[],householdMembers:[]};}); const households=buildHouseholds(npcs,locations,rng); buildProfessionalNetworks(npcs,locations,rng); buildPersonalNetworks(npcs,locations,rng); return households;}
function locationNamePool(data,opts,rng){const template=pickTemplate(data,opts.size||'Town',opts.biome||'Grassland Plains'); return {template,pool:U.uniq(template.locations||[])};}
function locationFromBase(data,base,i,opts,rng,blueprint){const clean=String(base||`Location ${i+1}`).split('/')[0].trim() || `Location ${i+1}`; const loc={id:blueprint?.id||`loc_${i+1}`,name:blueprint?.generatedName||clean,sourceType:base,kind:classifyLocation(clean),category:categoryForLocation(clean),x:blueprint?.x??(8+(rng()*84)),y:blueprint?.y??(10+(rng()*78)),itemsForSale:itemsFor(data,clean,opts.size,opts.biome,rng),employees:[],visitors:[],residents:[],notes:blueprint?`Autofilled from blank clickable SVG target ${blueprint.sourceLabel||blueprint.elementId||i+1}.`:`Generated from ${opts.size||'Town'} ${opts.biome||''} pool.`,svgTarget:blueprint||undefined}; return loc;}
function generateSettlement(data,opts={}){const rng=U.seeded(`${opts.province}|${opts.settlementName}|${opts.seed||''}|${opts.svgLocations?.length||0}|${Date.now()}`); const picked=locationNamePool(data,opts,rng); const pool=picked.pool; const blueprints=Array.isArray(opts.svgLocations)?opts.svgLocations:[]; const count=blueprints.length?blueprints.length:U.clamp(opts.locationCount||60,1,900); const locations=[]; for(let i=0;i<count;i++){const base=pool[i%pool.length]||`Location ${i+1}`; const bp=blueprints[i]?Object.assign({},blueprints[i],{id:`loc_${i+1}`,generatedName:String(base).split('/')[0].trim()||`Location ${i+1}`}):null; locations.push(locationFromBase(data,base,i,opts,rng,bp));}
 const ncount=U.clamp(opts.npcCount||Math.max(120,locations.length*2),1,2000); const npcs=[]; for(let i=0;i<ncount;i++) npcs.push(makeNPC(data,rng,i+1,locations,opts)); const households=connectNPCs(npcs,rng,locations); const p=data.provinceByName[opts.province]||{}; return {schema:'belavados.player.settlement.v2',relationshipSystem:'gender-neutral layered Sims-style families, romance, work, friendship, rivalries, schedules, and autonomous movement',id:U.slug(`${opts.province}-${opts.settlementName}`),province:opts.province||'Unknown Province',settlementName:opts.settlementName||'Unnamed Settlement',settlementType:opts.size||'Town',size:opts.size||'Town',biome:opts.biome||picked.template.variant||picked.template.terrain||'Grassland Plains',governmentType:opts.governmentType||'',tags:U.uniq(String(opts.tags||'').split(',').map(s=>s.trim()).concat([opts.biome,opts.size,blueprints.length?'svg-autofilled':'generated']).filter(Boolean)),dangerLevel:opts.dangerLevel||'Moderate',alignmentPreference:opts.alignmentPreference||'Varies by district and NPC',timeZone:opts.timeZone||p.primaryUTC||'UTC',displayTimeZones:opts.displayTimeZones||p.displayUTCs||p.primaryUTC||'UTC',centerLongitude:p.centerLongitude||0,centerLatitude:p.centerLatitude||0,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),sourceTemplate:{terrain:picked.template.terrain,variant:picked.template.variant,size:picked.template.size},map:{svgText:opts.svgText||'',imageDataUrl:''},svgAutofill:{enabled:!!blueprints.length,blankClickableLocationCount:blueprints.length,manualPinCreation:false,notes:blueprints.length?'Uploaded SVG clickable blanks were autofilled from the location generator.':'Default generated settlement; DM uploads remain SVG-only.'},locations,npcs,households};}
function mutateLocations(data,settlement,pct=5){const rng=U.seeded(`loc-reroll-${Date.now()}-${settlement.id}`); const count=Math.max(1,Math.round((settlement.locations.length||1)*pct/100)); const template=pickTemplate(data,settlement.size,settlement.biome); for(let i=0;i<count;i++){const idx=Math.floor(rng()*settlement.locations.length); const base=U.sample(template.locations,rng)||settlement.locations[idx].name; const clean=String(base).split('/')[0].trim(); const old=settlement.locations[idx]; old.name=clean; old.category=categoryForLocation(clean); old.kind=classifyLocation(clean); old.itemsForSale=itemsFor(data,clean,settlement.size,settlement.biome,rng); old.notes=(old.svgTarget?'SVG target retained; ':'')+'Rerolled by DM 5% randomization.';} settlement.updatedAt=new Date().toISOString();}
function mutateNPCs(data,settlement,pct=5,opts={}){const rng=U.seeded(`npc-reroll-${Date.now()}-${settlement.id}`); const count=Math.max(1,Math.round((settlement.npcs.length||1)*pct/100)); for(let i=0;i<count;i++){const idx=Math.floor(rng()*settlement.npcs.length); const replacement=makeNPC(data,rng,idx+1,settlement.locations,opts); replacement.id=settlement.npcs[idx].id; settlement.npcs[idx]=replacement;} settlement.households=connectNPCs(settlement.npcs,rng,settlement.locations); settlement.updatedAt=new Date().toISOString();}
function activeScheduleEntry(npc,date=new Date()){const h=date.getHours()+date.getMinutes()/60; const day=date.getDay(); const entries=(day===3?npc.schedule?.restday:npc.schedule?.weekday)||[]; let active=entries[0]; entries.forEach(e=>{const m=String(e.time||'00:00').match(/(\d{1,2}):(\d{2})/); if(m){const t=Number(m[1])+Number(m[2])/60; if(t<=h) active=e;}}); return active||{};}
window.BelGenerator={generateSettlement,mutateLocations,mutateNPCs,categoryForLocation,classifyLocation,itemsFor,makeNPC,connectNPCs,activeScheduleEntry,relationshipTypes:RELTYPES,genderIdentities:GENDERS.map(g=>g[0]),romanticStatuses:ROMANTIC_STATUS};
})();
