(function(){
const U=BelUtils;
let zoom=1;
function defaultSVG(settlement){const title=U.esc(settlement?.settlementName||'Belavadös'); return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 800" role="img" aria-label="${title} settlement map"><defs><radialGradient id="g" cx="50%" cy="45%" r="70%"><stop offset="0" stop-color="#17323a"/><stop offset="1" stop-color="#04080a"/></radialGradient><filter id="glow"><feGaussianBlur stdDeviation="4" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs><rect width="1200" height="800" fill="url(#g)"/><path d="M80,640 C250,500 330,610 480,470 S780,330 1110,250" fill="none" stroke="#8de0dc" stroke-width="18" opacity=".22"/><path d="M120,380 C260,240 440,260 560,160 C720,25 920,120 1070,70" fill="none" stroke="#d7aa63" stroke-width="10" opacity=".22"/><g opacity=".45" stroke="#00ffff" stroke-width="2" fill="none">${Array.from({length:18},(_,i)=>`<circle cx="${160+i*58}" cy="${210+(i%5)*72}" r="${34+(i%4)*13}"/>`).join('')}</g><text x="600" y="70" text-anchor="middle" font-family="Georgia" font-size="42" fill="#eaffff" filter="url(#glow)">${title}</text><text x="600" y="114" text-anchor="middle" font-family="Georgia" font-size="21" fill="#d7aa63">Generated clickable settlement layer</text></svg>`;}
function renderBase(surface,placeholder,settlement){if(!surface)return; surface.innerHTML=''; if(settlement?.map?.svgText){surface.innerHTML=settlement.map.svgText; const svg=surface.querySelector('svg'); if(svg){svg.removeAttribute('width'); svg.removeAttribute('height'); svg.style.width='100%'; svg.style.height='100%'; svg.style.objectFit='contain';}} else {surface.innerHTML=defaultSVG(settlement);} if(placeholder) placeholder.style.display=settlement?'none':'grid';}
function pinClass(loc){if(loc.kind==='government')return 'government'; if(loc.kind==='market')return 'market'; if(loc.kind==='danger')return 'danger'; return '';}
function activeEntry(npc){if(window.BelGenerator?.activeScheduleEntry) return window.BelGenerator.activeScheduleEntry(npc,new Date()); return {locationId:npc.workLocationId||npc.homeLocationId,locationName:npc.workLocationName||npc.homeLocationName};}
function renderNPCMarkers(viewer,settlement){if(!viewer||!settlement)return; viewer.querySelectorAll('.npc-marker').forEach(n=>n.remove()); const locById=Object.fromEntries((settlement.locations||[]).map(l=>[l.id,l])); const npcs=(settlement.npcs||[]).slice(0,160); const slot=Math.floor(Date.now()/600000); npcs.forEach((npc,idx)=>{const entry=activeEntry(npc); const loc=locById[entry.locationId]||locById[npc.currentLocationId]||locById[npc.workLocationId]||locById[npc.homeLocationId]; if(!loc)return; const rng=U.seeded(`${npc.id}|${slot}`); const dot=document.createElement('button'); dot.className='npc-marker'; dot.title=`${npc.name} — ${entry.activity||'moving'} @ ${loc.name}`; dot.setAttribute('aria-label',dot.title); dot.style.left=U.clamp((loc.x??50)+(rng()-.5)*3.5,1,99)+'%'; dot.style.top=U.clamp((loc.y??50)+(rng()-.5)*3.5,1,99)+'%'; dot.addEventListener('click',e=>{e.stopPropagation(); U.toast(dot.title);}); viewer.appendChild(dot);});}
function renderPins(containerId,settlement,clicker,editable=false){const viewer=U.$(containerId); if(!viewer||!settlement)return; viewer.querySelectorAll('.location-pin,.anchor-dot,.npc-marker').forEach(n=>n.remove()); (settlement.locations||[]).forEach((loc,idx)=>{const pin=document.createElement('button'); pin.className='location-pin '+pinClass(loc); pin.dataset.label=String(idx+1); pin.title=loc.name; pin.style.left=(loc.x??50)+'%'; pin.style.top=(loc.y??50)+'%'; pin.addEventListener('click',e=>{e.stopPropagation(); clicker&&clicker(loc);}); if(editable){pin.draggable=false; pin.addEventListener('pointerdown',e=>{pin.setPointerCapture(e.pointerId); const rect=viewer.getBoundingClientRect(); const move=ev=>{loc.x=U.clamp(((ev.clientX-rect.left)/rect.width)*100,0,100); loc.y=U.clamp(((ev.clientY-rect.top)/rect.height)*100,0,100); pin.style.left=loc.x+'%'; pin.style.top=loc.y+'%';}; const up=()=>{pin.removeEventListener('pointermove',move); pin.removeEventListener('pointerup',up); window.BelApp?.saveLocal?.();}; pin.addEventListener('pointermove',move); pin.addEventListener('pointerup',up);});}
 viewer.appendChild(pin);}); renderNPCMarkers(viewer,settlement);}
function renderPlayer(settlement,onClick){renderBase(U.$('mapSurface'),U.$('mapPlaceholder'),settlement); renderPins('mapViewer',settlement,onClick,false);}
function renderDM(settlement,onClick){renderBase(U.$('dmMapSurface'),U.$('dmMapPlaceholder'),settlement); renderPins('dmMapViewer',settlement,onClick,true);}
function setZoom(surfaceId,z){const el=U.$(surfaceId); if(el)el.style.transform=`scale(${z})`;}
function init(app){U.$('zoomInBtn')?.addEventListener('click',()=>{zoom=Math.min(3,zoom+.15);setZoom('mapSurface',zoom);}); U.$('zoomOutBtn')?.addEventListener('click',()=>{zoom=Math.max(.5,zoom-.15);setZoom('mapSurface',zoom);}); U.$('resetZoomBtn')?.addEventListener('click',()=>{zoom=1;setZoom('mapSurface',zoom);}); document.addEventListener('click',e=>{if(e.target?.closest?.('#addPinBtn,#groupPinsBtn')){e.preventDefault();e.stopImmediatePropagation();U.toast('Manual pin creation is disabled. Upload clickable SVG locations instead.');}},true); setInterval(()=>{const s=app.currentSettlement?.(); if(!s)return; renderNPCMarkers(U.$('mapViewer'),s); if(document.body.classList.contains('dm-mode')) renderNPCMarkers(U.$('dmMapViewer'),s);},15000);}
window.BelMap={init,renderPlayer,renderDM,defaultSVG,renderNPCMarkers};
})();
