
(function(){
const U=BelUtils;
function locationById(s,id){return (s.locations||[]).find(l=>l.id===id);}
function npcById(s,id){return (s.npcs||[]).find(n=>n.id===id);}
function peopleList(s,ids){return (ids||[]).map(id=>npcById(s,id)?.name).filter(Boolean);}
function settlementInfoHTML(s){if(!s)return '<div class="empty">Select a settlement.</div>'; const tags=(s.tags||[]).map(t=>`<span class="tag cyan">${U.esc(t)}</span>`).join(''); return `<div class="statline"><span class="stat"><b>${U.esc(s.province)}</b></span><span class="stat"><b>${U.esc(s.settlementName)}</b></span><span class="stat">${U.esc(s.settlementType||s.size)}</span><span class="stat">${U.esc(s.timeZone)}</span></div><div class="box"><strong>Main settlement information</strong><br><span class="muted">Government: ${U.esc(s.governmentType||'Unspecified')}<br>Danger: ${U.esc(s.dangerLevel||'Moderate')}<br>Alignment preference: ${U.esc(s.alignmentPreference||'Varies')}</span><div style="margin-top:8px">${tags}</div></div><div class="box"><strong>Generated Contents</strong><br><span class="muted">${(s.locations||[]).length} locations • ${(s.npcs||[]).length} NPCs • ${U.esc(s.biome||'mixed biome')}</span></div>`;}
function showLocation(s,loc){const drawer=U.$('locationDrawer'); U.$('drawerTitle').textContent=loc.name; const employees=peopleList(s,loc.employees), visitors=peopleList(s,loc.visitors), residents=peopleList(s,loc.residents); U.$('drawerBody').innerHTML=`<div class="stack"><div class="box"><strong>${U.esc(loc.category||loc.kind||'Location')}</strong><br><span class="muted">${U.esc(loc.notes||'')}</span></div><div class="box"><strong>Items for sale / services</strong><ul class="list">${(loc.itemsForSale||[]).map(i=>`<li>${U.esc(i)}</li>`).join('')||'<li>No inventory listed.</li>'}</ul></div><div class="box"><strong>Employees working</strong><ul class="list">${employees.map(i=>`<li>${U.esc(i)}</li>`).join('')||'<li>No employees assigned.</li>'}</ul></div><div class="box"><strong>Visitors</strong><ul class="list">${visitors.map(i=>`<li>${U.esc(i)}</li>`).join('')||'<li>No visitors currently listed.</li>'}</ul></div><div class="box"><strong>Residents</strong><ul class="list">${residents.map(i=>`<li>${U.esc(i)}</li>`).join('')||'<li>No residents assigned.</li>'}</ul></div></div>`; drawer.classList.add('open');}
function locationCard(s,loc){const employees=peopleList(s,loc.employees).slice(0,8), visitors=peopleList(s,loc.visitors).slice(0,8); return `<article class="item"><h3>${U.esc(loc.name)}<small>${U.esc(loc.category||loc.kind||'Location')}</small></h3><div class="tags">${(loc.itemsForSale||[]).slice(0,12).map(i=>`<span class="tag">${U.esc(i)}</span>`).join('')}</div><div class="split"><div class="box"><strong>Employees</strong><br><span class="muted">${employees.map(U.esc).join(', ')||'None assigned'}</span></div><div class="box"><strong>Visitors</strong><br><span class="muted">${visitors.map(U.esc).join(', ')||'None listed'}</span></div></div></article>`;}
function relationshipSummary(n){return ['familial','romantic','personal','professional'].map(cat=>{const rels=(n.relationships?.[cat]||[]).slice(0,5); return `<div class="box"><strong>${U.esc(cat[0].toUpperCase()+cat.slice(1))}</strong><ul class="list">${rels.map(r=>`<li>${U.esc(r.type)} with ${U.esc(r.npcName)} — ${U.esc(r.status||'current')}, ${U.esc(r.emotionalTone||'neutral')}, trust ${U.esc(r.trust??'—')}, conflict ${U.esc(r.conflictLevel||'none')}</li>`).join('')||'<li>No listed ties.</li>'}</ul></div>`;}).join('');}
function familyTreeSummary(n){const ft=n.familyTree||{}; const line=(label,arr)=>`${label}: ${(arr||[]).map(x=>x.name).slice(0,5).join(', ')||'—'}`; return [line('Parents / guardians',ft.parents),line('Children / wards',ft.children),line('Siblings',ft.siblings),line('Partners',ft.partners),line('Extended / chosen family',(ft.extendedFamily||[]).concat(ft.chosenFamily||[]))].map(U.esc).join('<br>');}
function scheduleSummary(n){const entries=(n.schedule?.weekday||[]).slice(0,6); return entries.map(e=>`<li>${U.esc(e.time)} — ${U.esc(e.activity)} @ ${U.esc(e.locationName||'moving')}</li>`).join('')||'<li>No schedule listed.</li>';}
function npcCard(s,n){const allRels=Object.entries(n.relationships||{}).flatMap(([cat,rels])=>(rels||[]).map(r=>({...r,cat}))); const axes=n.alignment?Object.values(n.alignment).filter(a=>a&&a.label):[]; return `<article class="item"><h3>${U.esc(n.name)}<small>${U.esc(n.race)} • ${U.esc(n.genderIdentity)} • ${U.esc(n.pronouns)} • ${U.esc(n.ageStage||'adult')}</small></h3><div class="tags"><span class="tag ok">${U.esc(n.workplaceRole)}</span><span class="tag violet">${U.esc(n.raceCategory)}</span><span class="tag">${U.esc(n.relationshipStatus||'Single')}</span><span class="tag">${U.esc(n.alignment?.summary||'alignment varies')}</span></div><div class="split"><div class="box"><strong>Employment</strong><br><span class="muted">${U.esc(n.workLocationName||'Unassigned')}<br>${U.esc(n.movementProfile?.behavior||'Moves between home, work, errands, and social stops.')}</span></div><div class="box"><strong>Residence / Household</strong><br><span class="muted">${U.esc(n.homeLocationName||'Unassigned')}<br>${U.esc(n.householdRole||'resident')}</span></div></div><div class="box" style="margin-top:8px"><strong>Traits and Rumors</strong><br><span class="muted">Traits: ${U.esc((n.traits||[]).join(', '))}<br>Rumors: ${U.esc((n.rumors||[]).join('; '))}</span></div><div class="box" style="margin-top:8px"><strong>Family tree</strong><br><span class="muted">${familyTreeSummary(n)}</span></div><div class="box" style="margin-top:8px"><strong>Daily schedule</strong><ul class="list">${scheduleSummary(n)}</ul></div><div class="widegrid" style="margin-top:8px">${relationshipSummary(n)}</div><div class="box" style="margin-top:8px"><strong>Alignment axes</strong><ul class="list">${axes.map(a=>`<li>${U.esc(a.label)}: ${a.score} (${U.esc(a.phase)})</li>`).join('')||'<li>No alignment axes.</li>'}</ul></div><div class="box" style="margin-top:8px"><strong>Relationship count</strong><br><span class="muted">${allRels.length} layered ties across family, romance, work, and personal history.</span></div></article>`;}
function renderSearch(s){const box=U.$('itemSearchResults'); if(!box)return; const q=U.normal(U.$('itemSearch')?.value||''); if(!s){box.innerHTML='<div class="empty">Select a settlement first.</div>';return;} if(!q){box.innerHTML='<div class="empty">Start typing an item or service. Example: breakfast, armor, room, dagger.</div>';return;} const matches=(s.locations||[]).filter(l=>(l.itemsForSale||[]).some(i=>U.normal(i).includes(q))); box.innerHTML=matches.length?matches.map(l=>locationCard(s,l)).join(''):`<div class="empty">No locations in ${U.esc(s.settlementName)} specifically sell “${U.esc(U.$('itemSearch').value)}”.</div>`;}
function renderNPCs(s){const box=U.$('npcList'); if(!box)return; if(!s){box.innerHTML='<div class="empty">Select a settlement first.</div>';return;} const q=U.normal(U.$('npcSearch')?.value||''); const list=(s.npcs||[]).filter(n=>!q||U.normal(JSON.stringify(n)).includes(q)); box.innerHTML=list.length?list.map(n=>npcCard(s,n)).join(''):'<div class="empty">No NPCs match that filter.</div>';}
function render(app){const s=app.currentSettlement(); U.$('settlementInfo').innerHTML=settlementInfoHTML(s); U.$('selectedChip').textContent=s?`${s.province} / ${s.settlementName}`:'No settlement selected'; BelMap.renderPlayer(s,loc=>showLocation(s,loc)); renderSearch(s); renderNPCs(s);}
function init(app){U.$('closeDrawer')?.addEventListener('click',()=>U.$('locationDrawer').classList.remove('open')); U.$('itemSearch')?.addEventListener('input',()=>renderSearch(app.currentSettlement())); U.$('npcSearch')?.addEventListener('input',()=>renderNPCs(app.currentSettlement()));}
window.BelPlayer={init,render,showLocation,npcCard,locationCard};
})();
