
(function(){
const {$,esc,parseUTC}=BelUtils;
function isLeap(y){return (y%4===0&&y%100!==0)||y%400===0;}
function dayOfYear(d){return Math.floor((Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate())-Date.UTC(d.getUTCFullYear(),0,0))/86400000);}
function shiftedDate(date,utcLabel){const offset=parseUTC(utcLabel); return new Date(date.getTime()+offset*60000);}
function belavados(date, data){const y=date.getUTCFullYear(); const days=isLeap(y)?366:365; const start=Date.UTC(y,0,1); const progress=(date.getTime()-start)/(86400000*days); const solar=((progress%1+1)%1)*330.15; const civil=((progress%1+1)%1)*330; const monthIndex=Math.max(0,Math.min(10,Math.floor(civil/30))); const month=(data.months||[])[monthIndex]||{name:'Month '+(monthIndex+1),theme:''}; const day=Math.floor(civil%30)+1; const belHour=Math.floor((solar%1)*24); const belMin=Math.floor((((solar%1)*24)%1)*60); const belSec=Math.floor(((((solar%1)*24)%1)*60%1)*60); const weekday=(data.weekdays||[])[date.getUTCDay()===0?6:date.getUTCDay()-1]||{}; const moonA=((solar%19.20)/19.20*100).toFixed(1); const moonB=((solar%2.02)/2.02*100).toFixed(1); return {month,day,weekday,solarDay:solar,civilDay:civil,time:`${String(belHour).padStart(2,'0')}:${String(belMin).padStart(2,'0')}:${String(belSec).padStart(2,'0')}`,moonA,moonB};}
function fmtEarth(d, label){return `${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,'0')}-${String(d.getUTCDate()).padStart(2,'0')} ${String(d.getUTCHours()).padStart(2,'0')}:${String(d.getUTCMinutes()).padStart(2,'0')}:${String(d.getUTCSeconds()).padStart(2,'0')} ${label}`;}
function render(data, settlement){const now=new Date(); const local=now; const dmLabel=local.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'}); const utcLabel=settlement?.timeZone||'UTC'; const shifted=shiftedDate(now,utcLabel); const b=belavados(shifted,data.timeData||data); const panel=$('timePanel'); if(panel){panel.innerHTML=`<div class="clock-card"><h3>Player Local Time</h3><div class="clock-main">${esc(dmLabel)}</div><p class="muted">Earth-first table play.</p></div><div class="clock-card"><h3>DM / Browser Time</h3><div class="clock-main">${esc(local.toLocaleDateString())}</div><p class="muted">${esc(local.toString().replace(/\(.+\)/,''))}</p></div><div class="clock-card"><h3>Settlement Time</h3><div class="clock-main">${esc(fmtEarth(shifted,utcLabel))}</div><p class="muted">Province/settlement UTC auto-switch.</p></div><div class="clock-card"><h3>Belavadös Time</h3><div class="clock-main">${esc(b.time)}</div><p class="muted">${esc(b.month.name)} ${b.day}, ${esc(b.weekday.belavadosWeekday||'Belavadös weekday')}<br/>Solar day ${b.solarDay.toFixed(2)} / 330.15<br/>${esc(b.month.theme||'')}</p></div><div class="clock-card"><h3>Night Sky</h3><p class="muted">Chandratecu-Seleneš phase ${b.moonA}%<br/>Mictlindra-Nannara phase ${b.moonB}%<br/>Calculated from Belavadös solar progress.</p></div>`;} const chip=$('timeChip'); if(chip) chip.textContent=`${b.month.name} ${b.day} • ${b.time}`;}
function init(app){setInterval(()=>render(app.data,app.currentSettlement()),1000); render(app.data,app.currentSettlement());}
window.BelTime={init,render,belavados};
})();
