'use strict';
/* TableGate v5 NPC Life Simulator — original campaign-scoped implementation.
 * Conceptual research references, not copied code: ShiJbey/neighborly and
 * TownGeneratorOS. See Data & Sources for exact provenance and license status.
 */
(()=>{
const FIRST=['Avery','Maren','Tamsin','Ilyan','Rowan','Sora','Nico','Juniper','Cassian','Elara','Mika','Riven','Noor','Sage','Kestrel','Tarin','Liora','Perrin','Zuri','Callan','Vesper','Amari','Quinn','Remy','Dara','Ash','Theo','Mina','Luca','Cleo'];
const LAST=['Vale','Thorn','Marrow','Kestrel','Dawn','Rook','Moss','Ember','Grey','Hollow','Wren','Stone','Lark','River','North','Bright','Fen','Wolf','Oak','Gale','Reed','Hart','Cinder','Moon'];
const PRONOUNS=[['they','them','their'],['she','her','her'],['he','him','his'],['ze','zir','zir'],['she/they','her/them','her/their'],['he/they','him/them','his/their']];
const GENDERS=['nonbinary','woman','man','genderfluid','agender','demigirl','demiboy','two-spirit-inspired fantasy identity'];
const ORIENTATIONS=['bisexual','pansexual','lesbian','gay','queer','asexual','demisexual','aromantic','biromantic asexual','panromantic demisexual','straight'];
const STRUCTURES=['monogamous','polyamorous','relationship-anarchist','open relationship','solo polyamorous','not currently seeking romance'];
const JOBS=['apothecary','archivist','baker','blacksmith','boatwright','caravan guide','carpenter','cartographer','city watch officer','courier','diplomat','dockworker','farmer','fisher','glassworker','healer','innkeeper','librarian','mason','midwife','musician','scribe','tailor','teacher','temple caretaker','trader','weaver','woodworker','street-food vendor','magical researcher'];
const HOBBIES=['astronomy','birdwatching','board games','bookbinding','brewing tea','calligraphy','community theater','cooking','dance','fishing','flower arranging','folk music','gardening','glass painting','historical reenactment','knitting','map collecting','mechanical puzzles','mushroom foraging','painting miniatures','poetry','pottery','rock collecting','stargazing','storytelling','swimming','wood carving','writing letters'];
const TRAITS=['affectionate','ambitious','anxious','bold','careful','charming','compassionate','curious','dryly funny','earnest','eccentric','generous','guarded','idealistic','impatient','loyal','methodical','mischievous','observant','optimistic','patient','practical','protective','quiet','restless','romantic','scholarly','skeptical','stubborn','warm'];
const VALUES=['chosen family','community care','craft excellence','curiosity','fairness','freedom','hospitality','honesty','knowledge','loyalty','mercy','mutual aid','personal growth','protection','tradition'];
const FEARS=['being forgotten','failing someone who depends on them','fire','deep water','losing their home','public humiliation','repeating a parent’s mistakes','storms','uncontrolled magic','war returning'];
const SECRETS=['They quietly fund a local mutual-aid pantry.','They use a different name in a former city.','They witnessed a politically dangerous meeting.','They are protecting someone accused of a crime they did not commit.','They possess an heirloom tied to a vanished family.','They can read a script believed to be extinct.','They owe a life-debt to a rival faction.','They are the anonymous author of popular protest songs.','They know a hidden route beneath the settlement.','They are considering leaving their profession for an artistic calling.'];
const RUMORS=['keeps a tame spirit in the cellar','once won a duel without drawing a weapon','knows where the old road truly ends','is secretly related to local nobility','can predict rain by taste','has a second workshop nobody can find','shelters travelers without asking questions','writes love letters for people too shy to write their own','heard voices beneath the western well','was seen meeting a rival after midnight'];
const LOCATIONS=['home','market square','workplace','community hall','riverside','garden district','temple commons','library','favorite café','friend’s home','public baths','night market'];
function hash(v){let h=2166136261>>>0;for(const c of String(v)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
class RNG{constructor(seed){this.s=hash(seed)||1}next(){let x=this.s;x^=x<<13;x^=x>>>17;x^=x<<5;this.s=x>>>0;return this.s/4294967296}int(a,b){return Math.floor(this.next()*(b-a+1))+a}pick(a){return a[this.int(0,a.length-1)]}shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=this.int(0,i);[a[i],a[j]]=[a[j],a[i]]}return a}}
function storeKey(){return`npcLives.v5.${CampaignIsolation.serverId()}`}
function blank(){return{version:5,settlement:'',day:1,hour:8,npcs:[],events:[],activeId:'',updatedAt:new Date().toISOString()}}
function load(){const d=Store.get(storeKey(),null);return d&&Array.isArray(d.npcs)?d:blank()}
function save(d){d.updatedAt=new Date().toISOString();Store.set(storeKey(),d);try{API.call('saveNpcLives',{serverId:CampaignIsolation.serverId(),data:d}).catch(()=>{})}catch(_){}}
function unique(rng,list,count){return rng.shuffle(list).slice(0,count)}
function makeSchedule(rng,job,hobbies){const sleepStart=rng.pick([21,22,23,0]),wake=(sleepStart+rng.pick([7,8,9]))%24;const entries=[];for(let h=0;h<24;h++){let activity,location;if((sleepStart<=wake?(h>=sleepStart&&h<wake):(h>=sleepStart||h<wake))){activity='Sleeping';location='home'}else if(h===wake){activity='Morning routine and breakfast';location='home'}else if(h>=8&&h<12){activity=`Working as ${job}`;location='workplace'}else if(h===12){activity='Lunch and neighborhood conversation';location=rng.pick(['market square','workplace','favorite café'])}else if(h>=13&&h<17){activity=`Working as ${job}`;location='workplace'}else if(h===17){activity='Errands, correspondence, and household tasks';location=rng.pick(['market square','home','community hall'])}else if(h>=18&&h<21){activity=rng.pick([`Practicing ${rng.pick(hobbies)}`,`Spending time with friends or partners`,`Attending a community gathering`,`Walking and reflecting`]);location=rng.pick(['home','friend’s home','community hall','riverside','night market'])}else{activity='Quiet personal time';location='home'}entries.push({hour:h,activity,location})}return entries}
function createNPC(rng,settlement,index){const pronouns=rng.pick(PRONOUNS),job=rng.pick(JOBS),hobbies=unique(rng,HOBBIES,rng.int(2,4)),traits=unique(rng,TRAITS,rng.int(3,5));return{id:uid(),serverId:CampaignIsolation.serverId(),settlement,name:`${rng.pick(FIRST)} ${rng.pick(LAST)}`,age:rng.int(18,86),gender:rng.pick(GENDERS),pronouns:{subject:pronouns[0],object:pronouns[1],possessive:pronouns[2]},orientation:rng.pick(ORIENTATIONS),relationshipStructure:rng.pick(STRUCTURES),job,workplace:`${rng.pick(['The','Old','Golden','Blue','Copper','Mossy','Moonlit'])} ${rng.pick(['Lantern','Bridge','Kettle','Anvil','Archive','Garden','Wheel','Harbor'])}`,traits,hobbies,values:unique(rng,VALUES,3),fear:rng.pick(FEARS),goal:rng.pick(['save enough to open a cooperative','repair a strained friendship','master a difficult craft technique','learn what happened to a missing mentor','protect the neighborhood from exploitation','finish a map of forgotten roads','organize a public festival','build a safer future for their chosen family']),secret:rng.pick(SECRETS),rumor:`People say ${pronouns[0]} ${rng.pick(RUMORS)}.`,publicNotes:'',relationships:[],schedule:makeSchedule(rng,job,hobbies),memories:[{day:0,text:`Moved into ${settlement} and began working as ${job}.`}],createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),index}}
function compatibleRomance(a,b){if(a.id===b.id||a.age<18||b.age<18)return false;const unavailable=x=>['aromantic','not currently seeking romance'].includes(x.orientation)||x.relationshipStructure==='not currently seeking romance';return !unavailable(a)&&!unavailable(b)}
function link(a,b,type,label,strength,rng){const shared={id:uid(),otherId:b.id,type,label,strength,trust:rng.int(25,95),tension:rng.int(0,55),history:rng.pick(['childhood connection','met through work','introduced by mutual friends','became close during a crisis','bonded through a shared hobby','neighbors who slowly became important to each other'])};a.relationships.push(shared);b.relationships.push({...shared,id:uid(),otherId:a.id})}
function buildRelationships(npcs,rng){
 for(const n of npcs)n.relationships=[];
 for(let i=0;i<npcs.length;i++){const a=npcs[i],candidates=rng.shuffle(npcs.filter(n=>n.id!==a.id&&!a.relationships.some(r=>r.otherId===n.id)));for(const b of candidates.slice(0,rng.int(2,4))){if(a.relationships.some(r=>r.otherId===b.id))continue;const type=rng.pick(['friendship','professional','personal','family-like']);const labels={friendship:rng.pick(['close friend','gaming friend','confidant','old friend']),professional:rng.pick(['coworker','supplier','mentor','apprentice','business rival']),personal:rng.pick(['neighbor','chosen sibling','community organizer','creative collaborator']),'family-like':rng.pick(['chosen parent','chosen sibling','cousin-like bond','household member'])};link(a,b,type,labels[type],rng.int(35,95),rng)}}
 const romanticCandidates=rng.shuffle(npcs.filter(n=>!['aromantic','asexual'].includes(n.orientation)||n.orientation.includes('romantic')));for(const a of romanticCandidates){if(a.relationships.some(r=>r.type==='romantic')&&a.relationshipStructure==='monogamous')continue;const options=rng.shuffle(romanticCandidates.filter(b=>compatibleRomance(a,b)&&!a.relationships.some(r=>r.otherId===b.id)&&(b.relationshipStructure!=='monogamous'||!b.relationships.some(r=>r.type==='romantic'))));if(options.length&&rng.next()<.55){const max=a.relationshipStructure.includes('poly')||a.relationshipStructure==='relationship-anarchist'?rng.int(1,3):1;for(const b of options.slice(0,max)){if(a.relationships.some(r=>r.otherId===b.id))continue;link(a,b,'romantic',rng.pick(['partner','sweetheart','spouse','datefriend','beloved']),rng.int(55,98),rng)}}}
}
function generate(settlement,count,seed){const rng=new RNG(seed),npcs=Array.from({length:count},(_,i)=>createNPC(rng,settlement,i));buildRelationships(npcs,rng);return npcs}
function currentActivity(npc,hour){return npc.schedule.find(x=>x.hour===hour)||npc.schedule[0]}
function simulate(d,hours=1){const rng=new RNG(`${d.day}:${d.hour}:${d.settlement}:${d.events.length}`);for(let step=0;step<hours;step++){d.hour++;if(d.hour>=24){d.hour=0;d.day++}for(const npc of d.npcs){const rel=npc.relationships.length?rng.pick(npc.relationships):null,other=rel&&d.npcs.find(n=>n.id===rel.otherId);if(rng.next()<.07){const act=currentActivity(npc,d.hour),text=other&&rng.next()<.55?`${npc.name} spent time with ${other.name}; their ${rel.label} relationship ${rng.pick(['grew warmer','became more complicated','settled after an honest conversation','sparked a new shared plan'])}.`:`${npc.name} ${rng.pick(['heard a new version of a local rumor','made progress toward a private goal','had an unexpectedly good day at work','found something curious near '+act.location,'changed tomorrow’s plans after a surprising message'])}`;const event={id:uid(),day:d.day,hour:d.hour,npcId:npc.id,text,at:new Date().toISOString()};d.events.unshift(event);npc.memories.unshift({day:d.day,text});npc.memories=npc.memories.slice(0,80)}}}d.events=d.events.slice(0,500);save(d)}
function relationHtml(npc,d){return npc.relationships.map(r=>{const other=d.npcs.find(n=>n.id===r.otherId);return`<div class="relationship-card"><b>${esc(other?.name||'Unknown')}</b><small>${esc(r.label)} · ${esc(r.type)} · trust ${r.trust}% · tension ${r.tension}%</small><p>${esc(r.history)}</p></div>`}).join('')||'<p>No established relationships yet.</p>'}
function scheduleHtml(npc){return npc.schedule.map(s=>`<div class="hour">${String(s.hour).padStart(2,'0')}:00</div><div><b>${esc(s.activity)}</b><small>${esc(s.location)}</small></div>`).join('')}
function detail(npc,d){if(!npc)return`<div class="empty-state"><h2>Select an NPC</h2><p>Generate or choose a resident to inspect their complete life.</p></div>`;const activity=currentActivity(npc,d.hour);return`<div class="npc-detail-grid"><section class="v5-card"><span class="eyebrow">${esc(npc.gender)} · ${esc(npc.pronouns.subject)}/${esc(npc.pronouns.object)}</span><h2>${esc(npc.name)}</h2><p><b>${npc.age}</b> · ${esc(npc.job)} at ${esc(npc.workplace)}</p><div class="npc-tags">${npc.traits.map(x=>`<span>${esc(x)}</span>`).join('')}</div><p><b>Orientation:</b> ${esc(npc.orientation)}<br><b>Relationship style:</b> ${esc(npc.relationshipStructure)}</p><p><b>Values:</b> ${npc.values.map(esc).join(', ')}</p><p><b>Goal:</b> ${esc(npc.goal)}</p><p><b>Fear:</b> ${esc(npc.fear)}</p></section><section class="v5-card"><h3>Current life</h3><p><b>Day ${d.day}, ${String(d.hour).padStart(2,'0')}:00</b></p><p>${esc(activity.activity)} at ${esc(activity.location)}.</p><h3>Hobbies</h3><div class="npc-tags">${npc.hobbies.map(x=>`<span>${esc(x)}</span>`).join('')}</div><h3>Public rumor</h3><p>${esc(npc.rumor)}</p><details><summary>Creator-only secret</summary><p>${esc(npc.secret)}</p></details></section><section class="v5-card"><h3>Relationships</h3><div class="v5-list">${relationHtml(npc,d)}</div></section><section class="v5-card"><h3>24-hour schedule</h3><div class="schedule-grid">${scheduleHtml(npc)}</div></section><section class="v5-card v5-span-12" style="grid-column:1/-1"><h3>Life memory</h3><div class="life-timeline">${npc.memories.map(m=>`<div class="life-event"><b>Day ${m.day}</b> · ${esc(m.text)}</div>`).join('')}</div></section></div>`}
function render(){const d=load(),active=d.npcs.find(n=>n.id===d.activeId)||d.npcs[0];return`<div class="npc-life-shell"><section class="v5-hero"><div><span class="eyebrow">CAMPAIGN-SCOPED SOCIAL SIMULATION</span><h2>NPC Lives</h2><p>Generate adult residents with full schedules, traits, goals, secrets, rumors, hobbies, jobs, memories, and professional, personal, family-like, and romantic networks. Queerness, chosen family, and consensual polyamory are ordinary parts of the social model rather than special cases.</p></div><div class="v5-actions"><button data-npc-hour>Advance 1 hour</button><button data-npc-day>Advance 1 day</button></div></section><div class="npc-layout"><aside class="v5-card"><h3>Settlement population</h3><div class="v5-form-grid"><div class="v5-field"><label>Settlement</label><input id="npc-settlement" value="${esc(d.settlement||'')}" placeholder="Settlement name"></div><div class="v5-field"><label>Residents</label><input id="npc-count" type="number" min="2" max="200" value="${d.npcs.length||24}"></div><div class="v5-field"><label>Seed</label><input id="npc-seed" value="${esc(d.seed||Math.floor(Math.random()*1e9))}"></div></div><div class="v5-actions" style="margin:10px 0"><button class="primary" data-npc-generate>Generate population</button><button data-npc-export>Export JSON</button></div><div class="v5-note">Day ${d.day} · ${String(d.hour).padStart(2,'0')}:00 · ${d.npcs.length} residents · stored only in ${esc(State.server.name)}</div><div class="npc-roster">${d.npcs.map(n=>{const act=currentActivity(n,d.hour);return`<button class="${n.id===active?.id?'active':''}" data-npc-id="${n.id}"><b>${esc(n.name)}</b><small>${esc(n.job)} · ${esc(act.location)}</small></button>`}).join('')||'<p>No residents generated.</p>'}</div></aside><main>${detail(active,d)}</main></div><section class="v5-card"><h3>Recent settlement events</h3><div class="life-timeline">${d.events.slice(0,80).map(e=>`<div class="life-event"><b>Day ${e.day}, ${String(e.hour).padStart(2,'0')}:00</b> · ${esc(e.text)}</div>`).join('')||'<p>Advance time to begin the living timeline.</p>'}</div></section></div>`}
function download(d){const blob=new Blob([JSON.stringify(d,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${(d.settlement||'settlement').replace(/[^a-z0-9]+/gi,'_')}_npc_lives.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function bind(shell){shell.querySelector('[data-npc-generate]')?.addEventListener('click',()=>{const settlement=$('#npc-settlement').value.trim()||'Unnamed Settlement',count=Math.max(2,Math.min(200,Number($('#npc-count').value)||24)),seed=$('#npc-seed').value||Date.now(),d=blank();d.settlement=settlement;d.seed=String(seed);d.npcs=generate(settlement,count,seed);d.activeId=d.npcs[0]?.id||'';save(d);Workspace.render();toast(`${count} residents generated for ${settlement}.`,'success')});shell.querySelectorAll('[data-npc-id]').forEach(b=>b.addEventListener('click',()=>{const d=load();d.activeId=b.dataset.npcId;save(d);Workspace.render()}));shell.querySelector('[data-npc-hour]')?.addEventListener('click',()=>{const d=load();simulate(d,1);Workspace.render()});shell.querySelector('[data-npc-day]')?.addEventListener('click',()=>{const d=load();simulate(d,24);Workspace.render()});shell.querySelector('[data-npc-export]')?.addEventListener('click',()=>download(load()))}
window.TableGateNpcLives={render,bind,load,save,generate,simulate,currentActivity};
})();
