'use strict';
/* TableGate v5 campaign character vault and dice-on-sheet session surface. */
(()=>{
const SHEETS=()=>window.TABLEGATE_CHARACTER_SHEETS||[];
const e=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clone=v=>JSON.parse(JSON.stringify(v));
const now=()=>new Date().toISOString();
function sid(){return CampaignIsolation.serverId()}
function uid5(){return `char_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,10)}`}
function key(){return `characterVault.v5.${sid()}`}
function selectedKey(){return `characterVault.selected.${sid()}.${State.user?.id||'local'}`}
function defaults(){return{version:5,serverId:sid(),policy:{defaultLimit:0,perUser:{},allowPlayerCreate:true,allowPlayerImport:true},characters:[],rollLog:[],updatedAt:now()}}
function load(){const d=Store.get(key(),null);if(!d||d.serverId!==sid())return defaults();d.policy=d.policy||defaults().policy;d.characters=Array.isArray(d.characters)?d.characters:[];d.rollLog=Array.isArray(d.rollLog)?d.rollLog:[];return d}
function save(d,sync=true){d.serverId=sid();d.updatedAt=now();Store.set(key(),d);if(sync)try{API.call('saveCampaignCharacterVault',{serverId:sid(),vault:d}).catch(()=>{})}catch(_){}return d}
function creator(){return CampaignIsolation.canCreate()}
function ownerId(){return State.user?.id||'local'}
function memberName(id){const m=(State.members||[]).find(x=>x.userId===id);return m?.nickname||m?.user?.username||(id===ownerId()?State.user?.username:'Player')||id}
function visible(d=load()){return creator()?d.characters:d.characters.filter(c=>c.ownerId===ownerId())}
function mine(d=load()){return d.characters.filter(c=>c.ownerId===ownerId())}
function limitFor(d,userId){const v=d.policy?.perUser?.[userId];return Number.isFinite(Number(v))?Number(v):Number(d.policy?.defaultLimit||0)}
function canAdd(d,userId){const limit=limitFor(d,userId),count=d.characters.filter(c=>c.ownerId===userId).length;return limit<=0||count<limit}
function selected(d=load()){const id=Store.get(selectedKey(),'');const allowed=visible(d);return allowed.find(c=>c.id===id)||allowed[0]||null}
function setSelected(id){Store.set(selectedKey(),id)}
function sheetById(id){return SHEETS().find(x=>x.id===id)||SHEETS()[0]}
function blankCharacter(owner=ownerId(),sheetId=SHEETS()[0]?.id||''){return{id:uid5(),serverId:sid(),ownerId:owner,ownerName:memberName(owner),name:'New Character',sheetId,state:{},appearance:{},portraitDataUrl:'',createdAt:now(),updatedAt:now()}}
function sheetSrcdoc(character,sessionMode=true){const sheet=sheetById(character?.sheetId),record=character?{...character,sheetState:character.sheetState||character.state||{},appearance:character.appearance||{}}:null;return String(sheet?.html||'').replaceAll('__TABLEGATE_CAMPAIGN_ID_JSON__',JSON.stringify(sid())).replaceAll('__TABLEGATE_SHEET_ID_JSON__',JSON.stringify(sheet?.id||'')).replaceAll('__TABLEGATE_CHARACTER_ID_JSON__',JSON.stringify(character?.id||'preview')).replaceAll('__TABLEGATE_USER_ID_JSON__',JSON.stringify(character?.ownerId||ownerId())).replaceAll('__TABLEGATE_CHARACTER_RECORD_JSON__',JSON.stringify(record).replace(/<\//g,'<\\/')).replaceAll('__TABLEGATE_SESSION_MODE_JSON__',JSON.stringify(!!sessionMode))}
function diceSrcdoc(){const base=new URL('assets/dice-session/',document.baseURI).href;return `<!doctype html><html><head><meta charset="utf-8"><base href="${e(base)}"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="styles.css"><style>html,body,#diceRoller{width:100%;height:100%;margin:0;overflow:hidden;background:transparent!important}body{font-family:system-ui}#diceRoller{position:absolute;inset:0}#diceRollerUI{position:absolute;inset:0;pointer-events:none}.top_field,.bottom_field,#numPad,#instructions{display:none!important}#diceLimit{position:absolute;left:50%;top:10px;transform:translateX(-50%);background:#500d;color:#fff;padding:8px;border-radius:10px}</style></head><body onload="bootDice()"><div id="diceRoller"></div><main id="diceRollerUI"><input id="textInput" value="1d20" hidden><div id="diceLimit" style="display:none">20-die 3D limit</div><div id="center_div"></div><div id="numPad"></div><span id="result"></span><span id="instructions"></span></main><script src="libs/three.min.js"><\/script><script src="libs/cannon.min.js"><\/script><script src="libs/teal.js"><\/script><script src="dice.js"><\/script><script src="dice-main-bot.js"><\/script><script>function bootDice(){let gl=null;try{const c=document.createElement('canvas');gl=c.getContext('webgl')||c.getContext('experimental-webgl')}catch(_){}if(!gl){document.body.dataset.webglError='true';try{parent.postMessage({type:'DICEBOT_DICE_MAIN_ERROR',message:'WebGL unavailable; textual results remain active.'},'*')}catch(_){}return}try{main.init()}catch(err){document.body.dataset.webglError='true';try{parent.postMessage({type:'DICEBOT_DICE_MAIN_ERROR',message:err.message},'*')}catch(_){}}}<\/script></body></html>`}
function notation(expr){const clean=String(expr||'1d20').toLowerCase().replace(/\s+/g,''),re=/([+-]?)(\d*)d(4|6|8|9|10|12|20|100)|([+-]?\d+)/g;let m,totalMod=0,dice=[],match='';while((m=re.exec(clean))){match+=m[0];if(m[3]){const sign=m[1]==='-'?-1:1,count=Math.max(1,Math.min(100,Number(m[2]||1))),sides=Number(m[3]);dice.push({sign,count,sides})}else totalMod+=Number(m[4]||0)}if(!dice.length)return{expression:'1d20',dice:[{sign:1,count:1,sides:20}],modifier:0};return{expression:clean,dice,modifier:totalMod}}
function localRoll(expr){const n=notation(expr),detail=[],requested=[],renderParts=[];let total=n.modifier;for(const group of n.dice){const rolls=[];for(let i=0;i<group.count;i++){const v=crypto?.getRandomValues?(()=>{const a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]%group.sides+1})():Math.floor(Math.random()*group.sides)+1;rolls.push(v);requested.push(v);total+=v*group.sign}detail.push({type:'dice',count:group.count,sides:group.sides,rolls,subtotal:rolls.reduce((a,b)=>a+b,0)*group.sign});renderParts.push(`${Math.min(group.count,20)}d${group.sides}`)}if(n.modifier)detail.push({type:'modifier',subtotal:n.modifier});return{total,detail,requestedResults:requested.slice(0,20),renderExpression:renderParts.join('+')||'1d20'}}
function inferredExpression(sheetId,label=''){const t=(label+' '+sheetId).toLowerCase();if(t.includes('fate'))return'4d6';if(t.includes('gurps'))return'3d6';if(t.includes('cthulhu')||t.includes('percent'))return'1d100';if(t.includes('daggerheart'))return'2d12';if(t.includes('pbta'))return'2d6';if(t.includes('blades'))return'1d6';if(t.includes('swade'))return'1d6+1d6';return'1d20'}
async function authoritativeRoll(expression,label,postPublic){let result=null;if(State.channel&&postPublic){try{result=await API.call('rollDice',{channelId:State.channel.id,expression,label,personaId:Store.get(`persona.${sid()}`,''),postMessage:true})}catch(err){console.warn('Backend roll unavailable; using local roll',err)}}if(!result)result=localRoll(expression);if(!result.renderExpression){const n=notation(expression);result.renderExpression=n.dice.map(g=>`${Math.min(g.count,20)}d${g.sides}`).join('+')||'1d20';result.requestedResults=(result.detail||[]).filter(x=>x.type==='dice').flatMap(x=>x.rolls||[]).slice(0,20)}return result}
function addLog(d,entry){d.rollLog.unshift(entry);d.rollLog=d.rollLog.slice(0,250);save(d,false)}
function quotaHtml(d,userId){const count=d.characters.filter(c=>c.ownerId===userId).length,limit=limitFor(d,userId),pct=limit>0?Math.min(100,count/limit*100):Math.min(100,count*8);return`<div class="quota-meter"><div><div class="bar"><span style="width:${pct}%"></span></div><small>${count} saved · ${limit>0?`${limit} permitted`:'unlimited by campaign policy'}</small></div><b>${limit>0?`${count}/${limit}`:'∞'}</b></div>`}
const CharacterVault={
 render(){const d=load(),list=visible(d),sheets=SHEETS();return`<div class="vault-shell"><section class="v5-hero"><div><span class="eyebrow">CAMPAIGN-OWNED CHARACTER LIBRARY</span><h2>My Character Sheets</h2><p>Characters are owned by a player and isolated to ${e(State.server.name)}. The campaign runner controls creation/import permissions and may use an unlimited policy or a per-player cap.</p></div><div class="v5-actions"><button data-char-import ${(!creator()&&!d.policy.allowPlayerImport)?'disabled':''}>Import character</button><button class="primary" data-char-new ${(!creator()&&!d.policy.allowPlayerCreate)?'disabled':''}>New character</button></div></section><section class="v5-card"><h3>Your campaign quota</h3>${quotaHtml(d,ownerId())}</section>${creator()?`<section class="v5-card"><h3>DM / GM / MOL character policy</h3><div class="v5-form-grid"><div class="v5-field"><label>Default sheets per player</label><input id="char-default-limit" type="number" min="0" value="${Number(d.policy.defaultLimit||0)}"><small>0 means unlimited.</small></div><label><input id="char-allow-create" type="checkbox" ${d.policy.allowPlayerCreate?'checked':''}> Players may create sheets</label><label><input id="char-allow-import" type="checkbox" ${d.policy.allowPlayerImport?'checked':''}> Players may import sheets</label></div><div class="v5-actions"><button data-policy-save>Save campaign policy</button><button data-policy-users>Set player-specific caps</button><button data-sync-characters>Sync account characters</button></div></section>`:''}<section class="v5-grid"><div class="v5-card v5-span-12"><div class="card-head"><h3>${creator()?'Campaign characters':'Characters you own'}</h3><span>${list.length}</span></div><div class="v5-list">${list.map(c=>`<article class="character-card"><div class="portrait">${c.portraitDataUrl?`<img src="${e(c.portraitDataUrl)}" alt="">`:e((c.name||'?').slice(0,2).toUpperCase())}</div><div class="character-meta"><b>${e(c.name)}</b><small>${e(sheetById(c.sheetId)?.name||c.sheetId)} · owner: ${e(memberName(c.ownerId))}</small></div><div class="character-actions"><button data-char-play="${e(c.id)}">Play</button><button data-char-edit="${e(c.id)}">Edit</button><button data-char-port="${e(c.id)}">Import / Port</button><button data-char-export="${e(c.id)}">Export</button><button data-char-delete="${e(c.id)}">Delete</button></div></article>`).join('')||'<div class="empty-workspace">No saved characters are available in this campaign.</div>'}</div></div></section><section class="v5-card"><h3>Available sheet systems</h3><div class="npc-tags">${sheets.map(s=>`<span>${e(s.name)}</span>`).join('')}</div></section></div>`},
 bind(shell){const d=load();shell.querySelector('[data-char-new]')?.addEventListener('click',()=>this.openEditor());shell.querySelector('[data-char-import]')?.addEventListener('click',()=>this.importDialog());shell.querySelectorAll('[data-char-play]').forEach(b=>b.onclick=()=>{setSelected(b.dataset.charPlay);Workspace.open('session')});shell.querySelectorAll('[data-char-edit]').forEach(b=>b.onclick=()=>this.openEditor(d.characters.find(c=>c.id===b.dataset.charEdit)));shell.querySelectorAll('[data-char-port]').forEach(b=>b.onclick=()=>window.TableGateCharacterImporter?.open({characterId:b.dataset.charPort}));shell.querySelectorAll('[data-char-export]').forEach(b=>b.onclick=()=>this.exportOne(d.characters.find(c=>c.id===b.dataset.charExport)));shell.querySelectorAll('[data-char-delete]').forEach(b=>b.onclick=()=>{const c=d.characters.find(x=>x.id===b.dataset.charDelete);if(!c||(!creator()&&c.ownerId!==ownerId()))return;if(confirm(`Delete ${c.name}?`)){d.characters=d.characters.filter(x=>x.id!==c.id);save(d);Workspace.render()}});shell.querySelector('[data-policy-save]')?.addEventListener('click',()=>{d.policy.defaultLimit=Math.max(0,Number($('#char-default-limit').value)||0);d.policy.allowPlayerCreate=$('#char-allow-create').checked;d.policy.allowPlayerImport=$('#char-allow-import').checked;save(d);Workspace.render();toast('Character policy saved for this campaign.','success')});shell.querySelector('[data-policy-users]')?.addEventListener('click',()=>this.playerCaps(d));shell.querySelector('[data-sync-characters]')?.addEventListener('click',()=>this.sync())},
 openEditor(existing=null){const d=load(),owner=existing?.ownerId||ownerId();if(!existing&&!canAdd(d,owner))return toast('This player has reached the campaign character-sheet limit.','error');const c=existing?clone(existing):blankCharacter(owner);const owners=creator()?(State.members||[]).map(m=>({id:m.userId,name:memberName(m.userId)})):[{id:ownerId(),name:memberName(ownerId())}];modal(existing?'Edit character':'Create character',`<div class="v5-form-grid"><div class="field"><label>Character name</label><input id="cv-name" value="${e(c.name)}"></div><div class="field"><label>Sheet system</label><select id="cv-sheet">${SHEETS().map(s=>`<option value="${e(s.id)}" ${s.id===c.sheetId?'selected':''}>${e(s.name)}</option>`).join('')}</select></div><div class="field"><label>Owner</label><select id="cv-owner" ${creator()?'':'disabled'}>${owners.map(o=>`<option value="${e(o.id)}" ${o.id===c.ownerId?'selected':''}>${e(o.name)}</option>`).join('')}</select></div><div class="field"><label>Portrait data URL (optional)</label><input id="cv-portrait" value="${e(c.portraitDataUrl||'')}"></div></div><p>The full interactive sheet opens in the session surface. Stat generation and randomization remain inside the sheet.</p>`,`<button data-close-modal>Cancel</button><button class="primary" data-cv-save>Save character</button>`);$('#modal-root').querySelector('[data-cv-save]').onclick=()=>{const owner2=$('#cv-owner').value||ownerId();if(!existing&&!canAdd(d,owner2))return toast('That player has reached their campaign limit.','error');c.name=$('#cv-name').value.trim()||'Unnamed Character';c.sheetId=$('#cv-sheet').value;c.ownerId=owner2;c.ownerName=memberName(owner2);c.portraitDataUrl=$('#cv-portrait').value.trim();c.updatedAt=now();const idx=d.characters.findIndex(x=>x.id===c.id);if(idx>=0)d.characters[idx]=c;else d.characters.push(c);save(d);setSelected(c.id);closeModal();Workspace.render();toast('Character saved to this campaign.','success')};},
 playerCaps(d){modal('Player-specific character limits',`<p>Use 0 to inherit the campaign default. The campaign default may itself be unlimited.</p><div class="v5-list">${(State.members||[]).map(m=>`<label class="v5-list-row"><span>${e(memberName(m.userId))}</span><input data-cap-user="${e(m.userId)}" type="number" min="0" value="${Number(d.policy.perUser?.[m.userId]||0)}"><small>saved: ${d.characters.filter(c=>c.ownerId===m.userId).length}</small></label>`).join('')}</div>`,`<button data-close-modal>Cancel</button><button class="primary" data-caps-save>Save caps</button>`,true);$('#modal-root').querySelector('[data-caps-save]').onclick=()=>{d.policy.perUser=d.policy.perUser||{};$('#modal-root').querySelectorAll('[data-cap-user]').forEach(i=>{const n=Math.max(0,Number(i.value)||0);if(n)d.policy.perUser[i.dataset.capUser]=n;else delete d.policy.perUser[i.dataset.capUser]});save(d);closeModal();Workspace.render();toast('Player limits saved.','success')}},
 importDialog(){const d=load();if(!creator()&&!d.policy.allowPlayerImport)return;if(window.TableGateCharacterImporter)return window.TableGateCharacterImporter.open();toast('Universal importer is unavailable.','error')},
 exportOne(c){if(!c)return;const a=document.createElement('a'),blob=new Blob([JSON.stringify(c,null,2)],{type:'application/json'});a.href=URL.createObjectURL(blob);a.download=`${c.name.replace(/[^a-z0-9]+/gi,'_')}_tablegate_character.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)},
 async sync(){try{const response=await API.call('listOwnedCharacters',{serverId:sid()});const incoming=response?.characters||response||[],d=load();let count=0;for(const raw of incoming){if(d.characters.some(c=>c.backendId===raw.id||c.id===raw.id))continue;d.characters.push({...blankCharacter(ownerId(),raw.sheetId),...raw,id:raw.localId||uid5(),backendId:raw.id,serverId:sid(),ownerId:raw.ownerId||ownerId(),createdAt:raw.createdAt||now(),updatedAt:now()});count++}save(d,false);Workspace.render();toast(`${count} account character${count===1?'':'s'} imported.`,'success')}catch(err){toast('The current backend does not expose account character sync; local campaign characters remain available.','error')}}
};
const SessionPlay={diceReady:false,pending:[],
 render(){const d=load(),chars=visible(d),c=selected(d);if(!c)return`<div class="session-shell"><section class="v5-hero"><div><h2>Live Dice & Character Sheet</h2><p>Create or import a campaign character first.</p></div><button class="primary" data-go-vault>Open Character Sheets</button></section></div>`;return`<div class="session-shell"><section class="v5-hero"><div><span class="eyebrow">PUBLIC SESSION ROLLS</span><h2>Dice on Character Sheet</h2><p>The selected sheet sits directly beneath the transparent 3D dice table. Attacks, initiative, skills, saves, moves, and other play rolls route through the shared dice; only stat generation/randomization remains on the sheet itself.</p></div><div class="v5-actions"><button data-go-vault>Manage characters</button>${creator()?'<button data-private-dice>Private admin dice</button>':''}</div></section><div class="session-toolbar v5-card"><div class="v5-field"><label>Active owned character in ${e(State.server.name)}</label><select id="session-character">${chars.map(x=>`<option value="${e(x.id)}" ${x.id===c.id?'selected':''}>${e(x.name)} — ${e(sheetById(x.sheetId)?.name||x.sheetId)}${creator()?` — ${e(memberName(x.ownerId))}`:''}</option>`).join('')}</select></div><div class="v5-note">Public rolls post to ${State.channel?`#${e(State.channel.name)}`:'the local session log until a text channel is selected'}.</div></div><div class="session-dice-controls"><div class="v5-field"><label>Roll expression</label><input id="session-expression" value="${e(inferredExpression(c.sheetId))}" placeholder="1d20+5"></div><div class="v5-field"><label>Label</label><input id="session-label" placeholder="Perception, attack, initiative…"></div><label><input id="session-public" type="checkbox" checked> Public</label><button class="primary" data-session-roll>Roll 3D dice</button></div><div class="session-table"><iframe class="session-sheet-frame" id="session-sheet-frame" title="${e(c.name)} character sheet"></iframe><iframe class="session-dice-frame" id="session-dice-frame" title="3D dice table" aria-hidden="true"></iframe><div class="session-result" id="session-result"></div></div><section class="v5-card"><div class="card-head"><h3>Campaign dice log</h3><span>${d.rollLog.length}</span></div><div class="dice-log">${d.rollLog.slice(0,60).map(r=>`<div class="dice-log-row ${r.private?'private':''}"><span class="total">${e(r.total)}</span><div><b>${e(r.label||r.expression)}</b><small>${e(r.characterName||r.rollerName)} · ${e(r.expression)} · ${new Date(r.at).toLocaleString()}</small></div><span>${r.private?'Private':'Public'}</span></div>`).join('')||'<p>No rolls in this campaign yet.</p>'}</div></section></div>`},
 bind(shell){const d=load(),c=selected(d);shell.querySelectorAll('[data-go-vault]').forEach(b=>b.onclick=()=>Workspace.open('characters'));shell.querySelector('[data-private-dice]')?.addEventListener('click',()=>Workspace.open('privateDice'));const sel=shell.querySelector('#session-character');if(sel)sel.onchange=()=>{setSelected(sel.value);Workspace.render()};if(!c)return;const sheet=shell.querySelector('#session-sheet-frame'),dice=shell.querySelector('#session-dice-frame');this.diceReady=false;this.pending=[];sheet.srcdoc=sheetSrcdoc(c,true);dice.srcdoc=diceSrcdoc();shell.querySelector('[data-session-roll]')?.addEventListener('click',()=>this.roll($('#session-expression').value,$('#session-label').value,$('#session-public').checked,c));},
 async roll(expr,label,post,c=selected()){expr=String(expr||'').trim()||inferredExpression(c?.sheetId,label);const result=await authoritativeRoll(expr,label||'Character roll',post);const payload={expression:result.renderExpression||expr,displayExpression:expr,displayTotal:Number(result.total),requestedResults:result.requestedResults||[]};const frame=$('#session-dice-frame');if(frame?.contentWindow)frame.contentWindow.postMessage({type:'DICEBOT_DICE_MAIN_ROLL',payload},'*');const out=$('#session-result');if(out)out.textContent=`${c?.name||memberName(ownerId())}: ${label||expr} = ${result.total}`;const d=load();addLog(d,{id:uid5(),serverId:sid(),characterId:c?.id||'',characterName:c?.name||'',rollerId:ownerId(),rollerName:memberName(ownerId()),expression:expr,label,total:result.total,detail:result.detail||[],private:false,at:now()});setTimeout(()=>{if(Workspace.current==='session')Workspace.render()},2200)},
 handleMessage(event){const data=event.data||{};if(data.type==='TABLEGATE_SHEET_ROLL_REQUEST'&&Workspace.current==='session'){const c=selected(),label=data.label||data.action||'Character roll',expr=data.expression||data.roll||inferredExpression(c?.sheetId,label);this.roll(expr,label,true,c)}else if(data.type==='TABLEGATE_SHEET_STATE'){const d=load(),characterId=data.characterId||data.context?.characterId,c=d.characters.find(x=>x.id===characterId);if(c&&c.serverId===sid()&&(c.ownerId===ownerId()||creator())){c.state=data.sheetState||data.state||data.payload||c.state;c.appearance=data.appearance||c.appearance;c.updatedAt=now();save(d)}}}
};
const PrivateDice={
 render(){if(!creator())return'<div class="empty-workspace">Creator permission required.</div>';const d=load(),privateLog=d.rollLog.filter(r=>r.private);return`<div class="private-dice-shell"><section class="v5-hero"><div><span class="eyebrow">RUNNER-ONLY CHANNEL</span><h2>Private Dice Bot</h2><p>DM, GM, MOL, Master of Lore, Storyteller, Keeper, Referee, and equivalent campaign runners may make hidden checks here. Results stay in the private runner log unless explicitly posted to the selected admin channel.</p></div></section><div class="private-bot-grid"><section class="v5-card"><iframe id="private-dice-frame" class="private-dice-frame" title="Private 3D dice"></iframe><div class="v5-form-grid"><div class="v5-field"><label>Expression</label><input id="private-expression" value="1d20"></div><div class="v5-field"><label>Purpose</label><input id="private-label" placeholder="Secret perception, encounter clock…"></div><div class="v5-field"><label>Admin channel</label><select id="private-channel"><option value="">Do not post</option>${(State.serverDetail?.channels||[]).filter(ch=>['TEXT','ANNOUNCEMENT'].includes(ch.type)).map(ch=>`<option value="${e(ch.id)}">#${e(ch.name)}</option>`).join('')}</select></div></div><button class="primary" data-private-roll>Ask dice bot to roll</button></section><aside class="v5-card"><h3>Private campaign log</h3><div class="dice-log">${privateLog.slice(0,80).map(r=>`<div class="dice-log-row private"><span class="total">${e(r.total)}</span><div><b>${e(r.label||r.expression)}</b><small>${e(r.expression)} · ${new Date(r.at).toLocaleString()}</small></div><span>Private</span></div>`).join('')||'<p>No private checks yet.</p>'}</div></aside></div></div>`},
 bind(shell){const f=shell.querySelector('#private-dice-frame');if(f)f.srcdoc=diceSrcdoc();shell.querySelector('[data-private-roll]')?.addEventListener('click',async()=>{const expr=$('#private-expression').value||'1d20',label=$('#private-label').value||'Private check',channelId=$('#private-channel').value;let result=null;if(channelId)try{result=await API.call('rollDice',{channelId,expression:expr,label:`[Runner private channel] ${label}`,personaId:'',postMessage:true})}catch(_){}if(!result)result=localRoll(expr);const payload={expression:result.renderExpression||expr,displayExpression:expr,displayTotal:Number(result.total),requestedResults:result.requestedResults||[]};f.contentWindow?.postMessage({type:'DICEBOT_DICE_MAIN_ROLL',payload},'*');const d=load();addLog(d,{id:uid5(),serverId:sid(),rollerId:ownerId(),rollerName:memberName(ownerId()),expression:expr,label,total:result.total,detail:result.detail||[],private:true,postedChannelId:channelId,at:now()});setTimeout(()=>Workspace.render(),1800)})}
};
window.addEventListener('message',ev=>SessionPlay.handleMessage(ev));
window.TableGateCharacterVault=CharacterVault;window.TableGateSessionPlay=SessionPlay;window.TableGatePrivateDice=PrivateDice;window.TableGateCharacterData={load,save,visible,mine,selected,setSelected,sheetSrcdoc,diceSrcdoc,limitFor,canAdd,ownerId,memberName,sheetById,blankCharacter,sid};
})();
