
(function(){
  'use strict';
  const LS = window.LifeSim;
  const familyTypes = ['biological','adoptive','foster','chosen','clan','noble house','hidden bloodline','magical lineage','divine ancestry','cursed ancestry','unknown parentage','polyamorous parent group','blended household'];
  const parentTypes = ['Parent','Adoptive Parent','Foster Parent','Guardian','Household Elder','Chosen Family Member','Secret Relative'];
  const childTypes = ['Child','Adoptive Child','Foster Child','Ward','Household Dependent','Chosen Family Member','Secret Relative'];
  LS.generateHouseholds = (npcs, locations, config) => {
    const groups=new Map(); npcs.forEach(n=>{ const key=n.residenceId||'unassigned'; if(!groups.has(key)) groups.set(key,[]); groups.get(key).push(n); });
    const households=[]; let index=1;
    groups.forEach((members, locId)=>{ if(!members.length) return; const location=locations.find(l=>l.id===locId)||{name:'Unassigned Housing'}; const name=`${LS.choose(['Household','Kinship','Ledger','Hearth','Rooming Circle','Chosen Family','Clan Hearth','Lineage House'])} ${index}: ${members[0].name.split(' ').slice(-1)[0]}`; const hhId=LS.uid('hh'); const roles=LS.data.rules.householdRoles||['Household Member']; members.forEach((m,idx)=>{ m.householdId=hhId; m.householdName=name; m.householdRole=idx===0?'Household Head':(idx===1&&members.length>2?'Co-Head of Household':LS.choose(roles)); });
      const tree=LS.makeFamilyTreeForHousehold(hhId, name, members, config);
      members.forEach(m=>{ m.familyTree={householdId:hhId, householdName:name, labels:'gender-neutral', nodes:tree.nodes, edges:tree.edges.filter(e=>e.from===m.id||e.to===m.id || e.householdWide), notes:tree.notes}; });
      households.push({id:hhId, name, residenceId:locId, residenceName:location.name, style:config.householdStyle, familyTypes:LS.shuffle(familyTypes).slice(0,3), members:members.map(m=>({id:m.id,name:m.name,role:m.householdRole,genderIdentity:m.genderIdentity,pronouns:m.pronouns,publicTitle:m.publicTitle})), relationshipWeb:tree, incomeLevel:LS.choose(['poor','modest','comfortable','wealthy','noble','precarious but proud']), socialClass:LS.choose(['working class','guild class','merchant class','religious household','civic household','noble-adjacent','criminally entangled','mixed class']), reputation:LS.choose(['warm but crowded','politely tense','deeply loyal','publicly respectable, privately complicated','chosen-family supportive','economically fragile','kept together by secrets']), secrets:[LS.choose(['one member is missing from official records','the household shelters a fugitive','a marriage contract is contested','a hidden inheritance affects them','a faction watches their mail','a secret parentage record is hidden in a temple ledger'])], conflicts:[LS.choose(['inheritance dispute','romantic jealousy','transit debt','faction pressure','religious disagreement','workplace rivalry','secret guardianship'])], religiousTies:config.primaryDeities||[], factionTies:[], raceComposition:Array.from(new Set(members.map(m=>m.race))), cultureTags:config.tags||[], businessOwnership:LS.choose(['none','shared stall','small shop share','guild stake','transport license','hidden safehouse deed']), debts:LS.choose(['none','modest','serious','politically dangerous','owed to a faction']), inheritanceIssues:LS.choose(['none','unclear heir','adoption record dispute','secret lineage clause','noble house claim']), plotHooks:[LS.choose(['A family tree record proves someone has a hidden claim.','A chosen-family member is omitted from civic records.','A secret relative arrives by transit with bad news.','A household debt is tied to a faction quest.'])]}); index++; });
    return households;
  };
  LS.makeFamilyTreeForHousehold = (householdId, householdName, members, config) => {
    const nodes=members.map((m,i)=>({id:m.id, name:m.name, genderIdentity:m.genderIdentity, pronouns:m.pronouns, role:m.householdRole, age:m.age, race:m.race, generation:i<2?0:(m.age<25?2:1)}));
    const edges=[]; const elders=members.filter(m=>m.age>=45).slice(0,2); const children=members.filter(m=>m.age<26).slice(0,4); const adults=members.filter(m=>m.age>=26&&m.age<65); const partners=LS.shuffle(adults).slice(0, config.includePoly?Math.min(4,adults.length):Math.min(2,adults.length));
    for(let i=0;i<partners.length-1;i++){ edges.push({from:partners[i].id,to:partners[i+1].id,type:LS.choose(config.includePoly?['Romantic Partner','Spouse','Polyamorous Partner','Courting Partner']:['Romantic Partner','Spouse','Courting Partner']),category:'romantic',householdWide:false}); }
    const guardians=elders.length?elders:adults.slice(0,2); children.forEach(ch=>{ const gs=LS.shuffle(guardians).slice(0, config.includePoly?Math.min(3,guardians.length):Math.min(2,guardians.length)); gs.forEach(g=>edges.push({from:g.id,to:ch.id,type:LS.choose(parentTypes),reverseType:LS.choose(childTypes),category:'familial',legalRelationship:LS.choose(['legal','customary','informal','secret','temple-recorded']),biologicalRelationship:LS.choose(['unknown','yes','no','not relevant']),chosenRelationship:LS.choose(['yes','no','partial']),guardianshipStatus:LS.choose(['active','contested','secret','expired','customary']),publicKnowledge:LS.choose(['public','private','selectively known','rumored']),familyConflict:LS.choose(['none','low','moderate','high']),unresolvedFamilySecret:LS.choose(['none','secret parentage','cursed ancestry','hidden inheritance','unknown bloodline'])})); });
    for(let i=0;i<members.length-1;i++){ if(LS.rng()<.38) edges.push({from:members[i].id,to:members[i+1].id,type:LS.choose(['Sibling','Chosen Family Member','Household Member','Clan Member','Lineage Member']),category:'familial',householdWide:true}); }
    return {householdId, householdName, labelMode:'gender-neutral', supports:['biological families','adoptive families','foster families','chosen families','clan families','noble houses','hidden bloodlines','magical lineages','divine ancestry','cursed ancestry','secret parentage','unknown parentage','multiple guardians','polyamorous parent groups','blended households'], nodes, edges, notes:['Family tree labels use parent, child, sibling, guardian, ward, spouse, partner, and family member by default.','Gender identity and pronouns override sex assumptions in every exported tree.']};
  };
  LS.familyTreeCSV = (household) => { const rows=[['ID','Full name','First names','Surname now','Gender Descriptor','Pronouns','Parent/Guardian IDs','Partner IDs','Household Role','Residence','Profession','Bio notes']]; const web=household.relationshipWeb||{}; const nodes=web.nodes||[]; const edges=web.edges||[]; const byId=Object.fromEntries(nodes.map(n=>[n.id,n])); nodes.forEach(n=>{ const parents=edges.filter(e=>e.to===n.id && e.category==='familial').map(e=>e.from).join(';'); const partners=edges.filter(e=>(e.from===n.id||e.to===n.id)&&e.category==='romantic').map(e=>e.from===n.id?e.to:e.from).join(';'); const parts=String(n.name||'').split(' '); rows.push([n.id,n.name,parts.slice(0,-1).join(' '),parts.slice(-1)[0]||'',n.genderIdentity,n.pronouns,parents,partners,n.role,household.residenceName,'',`Gender-neutral ${household.name} tree record.`]); }); return rows.map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\n'); };
  LS.downloadFamilyCSV = (householdId) => { const h=(LS.state.households||[]).find(x=>x.id===householdId); if(h) LS.download(`${LS.slug(h.name)}_family_tree.csv`,'text/csv',LS.familyTreeCSV(h)); };
  LS.downloadFamilyJSON = (householdId) => { const h=(LS.state.households||[]).find(x=>x.id===householdId); if(h) LS.download(`${LS.slug(h.name)}_family_tree.json`,'application/json',JSON.stringify(h.relationshipWeb,null,2)); };
  LS.familyTreeSVG = (household) => { const web=household.relationshipWeb||{}; const nodes=web.nodes||[]; const edges=web.edges||[]; if(!nodes.length) return '<div class="notice">No tree nodes.</div>'; const cx=360, cy=220; const radius=150; const pos={}; nodes.forEach((n,i)=>{ const angle=(-Math.PI/2)+(i/nodes.length)*Math.PI*2; const r=60+(n.generation||1)*45+(i%2)*18; pos[n.id]={x:cx+Math.cos(angle)*Math.min(radius,r), y:cy+Math.sin(angle)*Math.min(radius,r)}; }); const lineHtml=edges.map(edge=>{ const a=pos[edge.from], b=pos[edge.to]; if(!a||!b) return ''; return `<line x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}" class="tree-line ${edge.category||''}"><title>${LS.escape(edge.type||'relationship')}</title></line>`; }).join(''); const nodeHtml=nodes.map(n=>{ const p=pos[n.id]; return `<g class="tree-node"><circle cx="${p.x}" cy="${p.y}" r="24"><title>${LS.escape(n.name)} — ${LS.escape(n.genderIdentity)} (${LS.escape(n.pronouns)})</title></circle><text x="${p.x}" y="${p.y+40}" text-anchor="middle">${LS.escape(n.name.split(' ')[0])}</text><text x="${p.x}" y="${p.y+53}" text-anchor="middle" class="tiny-svg">${LS.escape(n.role||'member')}</text></g>`; }).join(''); return `<svg class="family-tree-svg" viewBox="0 0 720 440" role="img" aria-label="Gender-neutral family tree for ${LS.escape(household.name)}"><defs><filter id="glow"><feGaussianBlur stdDeviation="2" result="blur"/><feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs><text x="360" y="28" text-anchor="middle" class="tree-title">${LS.escape(household.name)}</text>${lineHtml}${nodeHtml}</svg>`; };
})();
