
(function(){
  'use strict';
  const LS = window.LifeSim;
  const densityMap = {light:2, standard:4, dense:6, veryDense:9};
  const relPools = {
    familial:['Parent','Child','Sibling','Grandparent','Grandchild','Cousin','Parent’s Sibling','Sibling’s Child','Half-Sibling','Step-Parent','Step-Child','Step-Sibling','Adoptive Parent','Adoptive Child','Foster Parent','Foster Child','Guardian','Ward','Chosen Family Member','Clan Member','Lineage Member','Bloodline Relative','Estranged Family Member','Unknown Relative','Secret Relative'],
    romantic:['Romantic Partner','Spouse','Fiancé','Courting Partner','Casual Partner','Long-Term Partner','Primary Partner','Secondary Partner','Polyamorous Partner','Secret Partner','Political Spouse','Arranged Spouse','Ex-Partner','Ex-Spouse','Widowed Partner','Estranged Partner','Former Betrothed','Unrequited Love Interest'],
    household:['Household Head','Co-Head of Household','Household Member','Dependent','Guardian','Ward','Elder','Caregiver','Apprentice Resident','Renter','Boarder','Servant','Household Guard','Hidden Resident','Guest','Secret Partner','Chosen Family Member'],
    professional:['Employer','Employee','Manager','Assistant','Apprentice','Mentor','Student','Teacher','Guild Superior','Guild Member','Guild Rival','Business Partner','Investor','Supplier','Customer','Regular Customer','Patron','Client','Debtor','Creditor','Rival Merchant','Supervisor','Subordinate','Contractor','Consultant','Courier Contact','Transit Operator','Station Worker','Criminal Contact','Smuggling Contact'],
    personal:['Friend','Best Friend','Close Friend','Childhood Friend','Drinking Companion','Neighbor','Rival','Enemy','Former Friend','Protector','Dependent','Idolized Figure','Obsessed Admirer','Blackmailer','Informant','Secret Keeper','Confidant','Gossip Source','Training Partner','Travel Companion','Gambling Partner','Religious Companion','Estranged Friend','Betrayed Friend','Friendly Acquaintance','Suspicious Acquaintance'],
    faction:['Faction Leader','Faction Officer','Faction Member','Faction Recruit','Faction Ally','Faction Enemy','Faction Rival','Faction Informant','Faction Patron','Faction Agent','Secret Contact','Defector','Spy','Double Agent','Smuggler Contact','Religious Ally','Political Ally','Political Rival','Guild Contact','Transportation Contact','Military Contact','Criminal Contact'],
    civic:['Civic Superior','Permit Contact','Registry Witness','Court Witness','Watch Contact','Tax Record Contact'],
    religious:['Religious Superior','Temple Assistant','Pilgrim Companion','Confessor','Omen Witness','Shrine Rival'],
    'customer-service':['Customer','Regular Customer','Supplier','Client','Patron','Service Debtor'],
    'criminal-secret':['Blackmailer','Informant','Smuggling Contact','Secret Keeper','Fence','Debt Enforcer','Hidden Accomplice'],
    'travel-transit':['Transit Operator','Station Worker','Travel Companion','Passenger Contact','Route Rival','Ticket Witness','ATA Inspector Contact']
  };
  const reciprocal = {'Parent':'Child','Child':'Parent','Adoptive Parent':'Adoptive Child','Adoptive Child':'Adoptive Parent','Foster Parent':'Foster Child','Foster Child':'Foster Parent','Step-Parent':'Step-Child','Step-Child':'Step-Parent','Grandparent':'Grandchild','Grandchild':'Grandparent','Guardian':'Ward','Ward':'Guardian','Employer':'Employee','Employee':'Employer','Supervisor':'Subordinate','Subordinate':'Supervisor','Teacher':'Student','Student':'Teacher','Mentor':'Apprentice','Apprentice':'Mentor','Debtor':'Creditor','Creditor':'Debtor','Protector':'Dependent','Primary Partner':'Secondary Partner','Secondary Partner':'Primary Partner'};
  LS.relationshipStatusFor = (category, type) => category==='romantic' ? LS.choose(LS.data.rules.romanticStatuses||['Complicated']) : LS.choose(['Current','Past','Public','Private','Rumored','Secret','Tense','Stable']);
  LS.addRelation = (from, to, category, type, history, config, extra={}) => { if(!from||!to||from.id===to.id) return null; const rel={id:LS.uid('rel'), fromId:from.id, fromName:from.name, toId:to.id, toName:to.name, category, type, relationshipStrength:extra.strength||LS.choose(['weak','moderate','strong','deep']), relationshipStatus:extra.status||LS.relationshipStatusFor(category,type), publicVisibility:extra.visibility||LS.choose(['public','private','known to close contacts','rumored','officially recorded','secret']), privateTruth:extra.privateTruth||LS.choose(['matches public record','more affectionate than public','more hostile than public','bound by debt','protected by silence','recorded incorrectly']), emotionalTone:extra.tone||LS.choose(['supportive','warm','neutral','respectful','tense','complicated','suspicious','hostile','affectionate','loyal']), conflictLevel:extra.conflict||LS.choose(['none','low','moderate','high']), loyaltyLevel:extra.loyalty||LS.choose(['low','guarded','moderate','high','absolute']), trustLevel:extra.trust||LS.choose(['low','guarded','moderate','high','absolute']), dependencyLevel:extra.dependency||LS.choose(['none','low','moderate','high']), historyNote:history, currentTension:extra.currentTension||LS.choose(['none','money pressure','family expectation','political disagreement','romantic uncertainty','faction suspicion','travel schedule strain']), secretConnection:extra.secretConnection||LS.choose(['none','hidden debt','shared crime','secret lineage clue','unauthorized transit favor','temple confession']), plotHook:extra.plotHook||LS.choose(['A rumor could expose this tie.','A shared debt comes due.','A faction demands they choose sides.','A transit delay traps them together.','A family record contradicts their story.']), workplace:from.workplace===to.workplace?from.workplace:'', scheduleOverlap:from.workplace===to.workplace?'work shift overlap':(from.residence===to.residence?'home overlap':'occasional'), sharedLocation:from.workplace===to.workplace?from.workplace:(from.residence===to.residence?from.residence:''), layers:extra.layers||[type]}; from.relationships=from.relationships||[]; from.relationships.push({id:rel.id,npcId:to.id,npcName:to.name,category,type,history:history,relationshipStatus:rel.relationshipStatus,publicVisibility:rel.publicVisibility,trustLevel:rel.trustLevel,plotHook:rel.plotHook,layers:rel.layers}); return rel; };
  LS.generateRelationships = (npcs, config) => { const rels=[]; const per=densityMap[config.socialDensity]||4; const cats=['personal','professional','familial','household','personal','professional','travel-transit','customer-service']; for(const npc of npcs){ const possible=LS.shuffle(npcs.filter(n=>n.id!==npc.id)); const count=Math.min(possible.length, Math.floor(per/2+LS.rng()*per)); for(let i=0;i<count;i++){ const other=possible[i]; let category=LS.choose(cats); if(config.includePoly && LS.rng()<.13) category='romantic'; if(npc.workplaceId && npc.workplaceId===other.workplaceId && LS.rng()<.55) category='professional'; if(npc.residenceId && npc.residenceId===other.residenceId && LS.rng()<.65) category='household'; if(npc.publicTransitHabit?.mode===other.publicTransitHabit?.mode && LS.rng()<.25) category='travel-transit'; const pool=relPools[category]||relPools.personal; let type=LS.choose(pool); if(config.includeLayered && LS.rng()<.18){ type += ' + ' + LS.choose(category==='familial'?relPools.professional:relPools.personal); } const history=LS.choose(['They trust each other because of a past crisis.','Their connection is useful but tense.','A secret favor binds them together.','They disagree about faction loyalty.','A family or household obligation keeps them in contact.','They share a route, workplace, or household pressure.','They are warmer in private than in public.','Their transit habits keep putting them in the same place.']); const rel=LS.addRelation(npc,other,category,type,history,config); if(rel) rels.push(rel); if(['familial','romantic','household'].includes(category)){ const mirrorType=reciprocal[type]||type; const mirror=LS.addRelation(other,npc,category,mirrorType,'Mirror tie: '+history,config,{status:rel.relationshipStatus,visibility:rel.publicVisibility}); if(mirror) rels.push(mirror); } } } return rels; };
})();
