'use strict';
const CONFIG=Object.freeze({
  backendUrl:'https://script.google.com/macros/s/AKfycbylmceRVx5UcgMvMDkwym_9h0wv8gM5B9Msuui7-7Z6lqoYlqZBR6Y47hmsauQgoGXY/exec',
  libraryUrl:'https://script.google.com/macros/library/d/18ET55A9uVNx3IUzoAM_eRj8v7jqagPgjVdxil3P1SoUqrFnnAJp6CjVr/6',
  libraryId:'18ET55A9uVNx3IUzoAM_eRj8v7jqagPgjVdxil3P1SoUqrFnnAJp6CjVr',libraryVersion:'6',
  hostingMode:'portable-current-folder',deploymentLocked:true,
  storagePrefix:'tablegate.v3',defaultPollMs:1500,defaultRtcPollMs:800
});
const PERM={ADMIN:1,MANAGE_TABLEGATE:2,MANAGE_SERVER:2,MANAGE_CHANNELS:4,MANAGE_MESSAGES:8,KICK_MEMBERS:16,BAN_MEMBERS:32,SEND_MESSAGES:64,READ_MESSAGES:128,CONNECT_VOICE:256,SPEAK:512,CREATE_INVITE:1024,MANAGE_ROLES:2048,ATTACH_FILES:4096,MENTION_EVERYONE:8192,MANAGE_NICKNAMES:16384,VIEW_AUDIT_LOG:32768,STREAM:65536,USE_PERSONAS:131072,ROLL_DICE:262144,MANAGE_HANDOUTS:524288,MANAGE_SYSTEMS:1048576,MANAGE_ORGANIZER:1048576,MANAGE_CHARACTERS:2097152,APPROVE_CALENDAR:2097152,USE_MECHANICS:4194304,UPLOAD_SYSTEM_FILES:4194304,MANAGE_SYSTEM_LIBRARY:1048576,VIEW_PRIVATE_AVAILABILITY:2,USE_RULES_ASSISTANT:4194304};
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const uid=()=>crypto.randomUUID?.()||('id_'+Date.now()+'_'+Math.random().toString(36).slice(2));
const fmtTime=v=>{try{return new Intl.DateTimeFormat(undefined,{hour:'numeric',minute:'2-digit'}).format(new Date(v))}catch{return ''}};
const fmtDate=v=>{try{return new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric',year:new Date(v).getFullYear()!==new Date().getFullYear()?'numeric':undefined}).format(new Date(v))}catch{return ''}};
const bytes=n=>{if(!Number.isFinite(+n))return '';const u=['B','KB','MB','GB'];let i=0;while(n>=1024&&i<u.length-1){n/=1024;i++}return `${n.toFixed(i?1:0)} ${u[i]}`};
const initials=n=>String(n||'?').split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase();
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
class ApiError extends Error{constructor(code,message,details){super(message||code);this.code=code;this.details=details}}
const BACKEND_ACTION_ALIASES=Object.freeze({
  listServers:'listTablegates',createServer:'createTablegate',getServer:'getTablegate',updateServer:'updateTablegate',
  deleteServer:'deleteTablegate',leaveServer:'leaveTablegate',requestPasswordReset:'forgotPassword',listOwnedCharacters:'listCharacters'
});
const BACKEND_PUBLIC_ACTIONS=new Set(['health','capabilities','previewInvite','register','login','requestEmailVerification','verifyEmail','forgotPassword','resetPassword']);
const BACKEND_VIRTUAL_ACTIONS=new Set([
  'getTablegateStudio','saveTablegateStudio','saveMapFoundry','saveNpcLives','saveCampaignCharacterVault',
  'getCampaignHubState','saveCampaignHubState','listCampaignAssets','createCampaignAsset','deleteCampaignAsset','broadcastDiceRoll',
  'listOrganizerTasks','createOrganizerTask','updateOrganizerTask','deleteOrganizerTask',
  'listCalendarItems','submitCalendarItem','updateCalendarItem','deleteCalendarItem','approveCalendarItem','rejectCalendarItem',
  'listRuleNotes','createRuleNote','askRulesAssistant','reindexSystemDocument',
  'publishCampaignItems','unpublishCampaignItems'
]);
function backendPayload(payload={}){
  const out={...payload};
  if(out.serverId!==undefined&&out.tablegateId===undefined)out.tablegateId=out.serverId;
  if(out.targetServerId!==undefined&&out.targetTablegateId===undefined)out.targetTablegateId=out.targetServerId;
  if(out.serverIds!==undefined&&out.tablegateIds===undefined)out.tablegateIds=out.serverIds;
  delete out.serverId;delete out.targetServerId;delete out.serverIds;
  return out;
}
function backendResponse(alias,data){
  if(alias==='createServer')return {...data,server:data?.tablegate||data?.server};
  if(alias==='getServer')return {...data,server:data?.tablegate||data?.server};
  if(alias==='listOwnedCharacters')return {characters:Array.isArray(data)?data:(data?.characters||[])};
  if(alias==='previewInvite'&&data?.tablegate)return {...data,server:data.tablegate};
  if(alias==='pollEvents'&&data?.events){return {...data,events:data.events.map(event=>({...event,eventType:String(event.eventType||'').replace(/^TABLEGATE_/,'SERVER_'),audienceType:event.audienceType==='TABLEGATE'?'SERVER':event.audienceType}))}}
  return data;
}
async function rawBackendCall(action,payload={},auth=true){
  const body={action,...backendPayload(payload),userAgent:navigator.userAgent};
  if(auth&&State.token)body.token=State.token;
  let res,text,json;
  try{res=await fetch(CONFIG.backendUrl,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(body),redirect:'follow'});text=await res.text();json=JSON.parse(text)}
  catch(err){throw new ApiError('NETWORK_ERROR','Could not reach the TableGate backend.',String(err?.message||err))}
  if(!json?.ok)throw new ApiError(json?.error?.code||'API_ERROR',json?.error?.message||'The backend rejected the request.',json?.error?.details);
  return json.data;
}
function slotProjectName(kind){return `__TABLEGATE_SLOT_${String(kind).toUpperCase()}__`}
async function findSlotProject(kind,tablegateId,create=false){
  const list=await rawBackendCall('listProjects',{tablegateId});
  let project=(list||[]).find(item=>item.name===slotProjectName(kind));
  if(!project&&create)project=await rawBackendCall('createProject',{tablegateId,name:slotProjectName(kind),projectType:'TABLEGATE_SLOT',description:`TableGate synchronized ${kind} data.`,settings:{slotKind:kind,managedBy:'TableGate frontend'}});
  return project||null;
}
async function loadBackendSlot(kind,tablegateId,fallback){
  const project=await findSlotProject(kind,tablegateId,false);if(!project)return fallback;
  const detail=await rawBackendCall('getProject',{projectId:project.id});
  const chunks=(detail?.items||[]).filter(item=>item.itemType==='SLOT_CHUNK').sort((a,b)=>(+a.orderIndex||0)-(+b.orderIndex||0));
  if(!chunks.length)return fallback;
  try{return JSON.parse(chunks.map(item=>item.data?.chunk||'').join(''))}catch(_){return fallback}
}
async function saveBackendSlot(kind,tablegateId,value){
  const project=await findSlotProject(kind,tablegateId,true),serialized=JSON.stringify(value??null),size=28000;
  const chunks=[];for(let i=0;i<serialized.length;i+=size)chunks.push(serialized.slice(i,i+size));if(!chunks.length)chunks.push('null');
  const existing=await rawBackendCall('listProjectItems',{projectId:project.id});
  const old=(existing||[]).filter(item=>item.itemType==='SLOT_CHUNK').sort((a,b)=>(+a.orderIndex||0)-(+b.orderIndex||0));
  for(let i=0;i<chunks.length;i++){
    const payload={name:`${kind} chunk ${String(i+1).padStart(4,'0')}`,itemType:'SLOT_CHUNK',status:'ACTIVE',orderIndex:i,data:{chunk:chunks[i],slotKind:kind,index:i,total:chunks.length}};
    if(old[i])await rawBackendCall('updateProjectItem',{itemId:old[i].id,...payload});else await rawBackendCall('createProjectItem',{projectId:project.id,...payload});
  }
  for(let i=chunks.length;i<old.length;i++)await rawBackendCall('deleteProjectItem',{itemId:old[i].id});
  await rawBackendCall('updateProject',{projectId:project.id,settings:{slotKind:kind,chunkCount:chunks.length,characters:serialized.length,updatedAt:new Date().toISOString()}});
  return {saved:true,updatedAt:new Date().toISOString(),projectId:project.id,chunkCount:chunks.length};
}
function makeRecord(prefix,payload={}){return {id:`${prefix}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,9)}`,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),...payload}}
async function mutateCollectionSlot(kind,tablegateId,operation,payload,idKey){
  const list=await loadBackendSlot(kind,tablegateId,[]);let result;
  if(operation==='create'){result=makeRecord(kind.slice(0,4),payload);list.push(result)}
  else if(operation==='update'){const id=payload[idKey];const index=list.findIndex(item=>item.id===id);if(index<0)throw new ApiError('NOT_FOUND',`${kind} record not found.`);result={...list[index],...payload,updatedAt:new Date().toISOString()};list[index]=result}
  else if(operation==='delete'){const id=payload[idKey];const index=list.findIndex(item=>item.id===id);if(index>=0)list.splice(index,1);result={deleted:true,id}}
  await saveBackendSlot(kind,tablegateId,list);return result;
}
async function attachedSystems(tablegateId){
  const links=await rawBackendCall('listTablegateSystems',{tablegateId});
  return Array.isArray(links)?links:links?.systems||[];
}
function normalizeSystemDocument(doc,link){
  const meta=doc?.metadata||{};
  return {...doc,serverId:doc?.tablegateId||'',systemName:meta.systemName||link?.label||link?.system?.name||doc?.systemId||'',fileType:meta.fileType||doc?.documentType||'RULES_REFERENCE',mimeType:meta.mimeType||'',tags:Array.isArray(meta.tags)?meta.tags:[],extractionStatus:meta.extractionStatus||'STORED_ONLY',extractedText:meta.extractedText||''};
}
async function listAttachedSystemDocuments(tablegateId){
  const links=await attachedSystems(tablegateId),out=[];
  for(const link of links){
    const docs=await rawBackendCall('listSystemDocuments',{tablegateId,systemId:link.systemId});
    (Array.isArray(docs)?docs:docs?.documents||[]).forEach(doc=>out.push(normalizeSystemDocument(doc,link)));
  }
  return out;
}
async function resolveSystemLink(tablegateId,requestedName=''){
  const links=await attachedSystems(tablegateId),needle=String(requestedName||'').trim().toLowerCase();
  return links.find(link=>link.systemId===requestedName)||links.find(link=>String(link.label||link.system?.name||'').toLowerCase()===needle)||links.find(link=>link.isPrimary)||links[0]||{systemId:'sys_tablegate_generic',system:{name:'TableGate Generic'}};
}
async function createCompatibleSystemDocument(payload){
  const p=backendPayload(payload),tablegateId=String(p.tablegateId||State.server?.id||''),link=await resolveSystemLink(tablegateId,p.systemName||p.systemId);
  const metadata={...(p.metadata||{}),systemName:p.systemName||link.system?.name||link.label||'',fileType:p.fileType||p.documentType||'',mimeType:p.mimeType||'',tags:p.tags||[]};
  const doc=await rawBackendCall('createSystemDocument',{tablegateId,systemId:link.systemId,attachmentId:p.attachmentId,title:p.title,documentType:p.documentType||p.fileType||'RULES_REFERENCE',version:p.version||'',visibility:p.visibility||'TABLEGATE',metadata});
  return normalizeSystemDocument(doc,link);
}
async function virtualBackendAction(action,payload={}){
  const p=backendPayload(payload),tablegateId=String(p.tablegateId||State.server?.id||'');
  if(action==='getTablegateStudio')return {studio:await loadBackendSlot('studio',tablegateId,null),updatedAt:new Date().toISOString()};
  if(action==='saveTablegateStudio')return saveBackendSlot('studio',tablegateId,p.studio);
  if(action==='saveMapFoundry')return saveBackendSlot('map-foundry',tablegateId,p.data);
  if(action==='saveNpcLives')return saveBackendSlot('npc-lives',tablegateId,p.data);
  if(action==='saveCampaignCharacterVault')return saveBackendSlot('character-vault',tablegateId,p.vault);
  if(action==='getCampaignHubState')return loadBackendSlot('campaign-hub',tablegateId,null);
  if(action==='saveCampaignHubState')return saveBackendSlot('campaign-hub',tablegateId,p.state);
  if(action==='listCampaignAssets'){const list=await rawBackendCall('listAssets',{tablegateId,assetType:p.kind||p.assetType||'MAP',limit:500});return list||[]}
  if(action==='createCampaignAsset')return rawBackendCall('organizeAttachment',{attachmentId:p.attachmentId,assetType:p.kind||'MAP',title:p.title,tags:p.tags||[],metadata:{mimeType:p.mimeType,visibility:p.visibility,tablegateId}});
  if(action==='deleteCampaignAsset'){const assets=await rawBackendCall('listAssets',{tablegateId,limit:500});const asset=(assets||[]).find(item=>item.id===p.assetId);if(!asset)throw new ApiError('ASSET_NOT_FOUND','Campaign asset not found.');return rawBackendCall('deleteAttachment',{attachmentId:asset.attachmentId})}
  if(action==='broadcastDiceRoll')return rawBackendCall('rollDice',{channelId:p.channelId,expression:p.roll?.expression||'1d20',label:p.roll?.label||'Session roll',personaId:p.roll?.personaId||'',postMessage:false});
  if(action==='listOrganizerTasks')return loadBackendSlot('organizer-tasks',tablegateId,[]);
  if(action==='createOrganizerTask')return mutateCollectionSlot('organizer-tasks',tablegateId,'create',{...p,tablegateId,createdBy:State.user?.id||''},'taskId');
  if(action==='updateOrganizerTask')return mutateCollectionSlot('organizer-tasks',tablegateId,'update',p,'taskId');
  if(action==='deleteOrganizerTask')return mutateCollectionSlot('organizer-tasks',tablegateId,'delete',p,'taskId');
  if(action==='listCalendarItems')return loadBackendSlot('calendar-items',tablegateId,[]);
  if(action==='submitCalendarItem')return mutateCollectionSlot('calendar-items',tablegateId,'create',{...p,tablegateId,submittedBy:State.user?.id||'',approvalStatus:(hasPerm(PERM.ADMIN)||hasPerm(PERM.MANAGE_TABLEGATE))?'APPROVED':'PENDING'},'calendarItemId');
  if(action==='updateCalendarItem')return mutateCollectionSlot('calendar-items',tablegateId,'update',{...p,approvalStatus:p.approvalStatus||'PENDING'},'calendarItemId');
  if(action==='deleteCalendarItem')return mutateCollectionSlot('calendar-items',tablegateId,'delete',p,'calendarItemId');
  if(action==='approveCalendarItem'||action==='rejectCalendarItem')return mutateCollectionSlot('calendar-items',tablegateId,'update',{calendarItemId:p.calendarItemId,approvalStatus:action==='approveCalendarItem'?'APPROVED':'REJECTED',approvedBy:action==='approveCalendarItem'?(State.user?.id||''):'',rejectionReason:p.reason||''},'calendarItemId');
  if(action==='listRuleNotes')return loadBackendSlot('rule-notes',tablegateId,[]);
  if(action==='createRuleNote')return mutateCollectionSlot('rule-notes',tablegateId,'create',{...p,tablegateId,createdBy:State.user?.id||''},'noteId');
  if(action==='publishCampaignItems')return saveBackendSlot('published-items',tablegateId,p.items||[]);
  if(action==='unpublishCampaignItems'){const current=await loadBackendSlot('published-items',tablegateId,[]),remove=new Set((p.items||[]).map(item=>item.key));return saveBackendSlot('published-items',tablegateId,current.filter(item=>!remove.has(item.key)))}
  if(action==='askRulesAssistant'){
    const query=p.query||p.question||'',matches=await rawBackendCall('searchKnowledge',{tablegateId,query,limit:p.limit||6});
    const sources=(matches||[]).map(item=>({id:item.id,title:item.title,systemName:item.metadata?.system||item.metadata?.systemName||'',excerpt:item.snippet||'',score:item.score,sourceUrl:item.sourceUrl||''}));
    return {answer:sources.length?`Found ${sources.length} grounded backend knowledge match${sources.length===1?'':'es'}. Review the excerpts before applying a ruling.`:'No synchronized backend knowledge source matched this question. Use the embedded Knowledge Pack workspace to ingest the relevant files.',suggestedRoll:(String(query).match(/\b\d*d\d+(?:\s*[+\-]\s*\d+)?\b/i)||[])[0]||'',sources};
  }
  if(action==='reindexSystemDocument'){
    const docs=await listAttachedSystemDocuments(tablegateId),doc=docs.find(item=>item.id===p.documentId);
    if(!doc)return {id:p.documentId,extractionStatus:'STORED_ONLY',updatedAt:new Date().toISOString()};
    try{const parsed=await rawBackendCall('parseAttachment',{attachmentId:doc.attachmentId});return {...doc,extractionStatus:parsed?.result?.text?'INDEXED':'STORED_ONLY',extractedText:String(parsed?.result?.text||'').slice(0,250000),updatedAt:new Date().toISOString()}}
    catch(_){return {...doc,extractionStatus:'STORED_ONLY',updatedAt:new Date().toISOString()}}
  }
  throw new ApiError('UNKNOWN_ACTION','Unknown frontend compatibility action: '+action);
}
const API={
  async call(action,payload={},auth=true){
    if(BACKEND_VIRTUAL_ACTIONS.has(action))return virtualBackendAction(action,payload);
    const adapted=backendPayload(payload),tablegateId=String(adapted.tablegateId||State.server?.id||'');
    if(action==='listSystemDocuments'&&!adapted.systemId)return listAttachedSystemDocuments(tablegateId);
    if(action==='createSystemDocument'&&!adapted.systemId)return createCompatibleSystemDocument(adapted);
    const backendAction=BACKEND_ACTION_ALIASES[action]||action;
    const useAuth=auth!==false&&!BACKEND_PUBLIC_ACTIONS.has(backendAction);
    const data=await rawBackendCall(backendAction,adapted,useAuth);
    return backendResponse(action,data);
  }
};
const Store={get(k,f=null){try{const v=localStorage.getItem(`${CONFIG.storagePrefix}.${k}`);return v===null?f:JSON.parse(v)}catch{return f}},set(k,v){localStorage.setItem(`${CONFIG.storagePrefix}.${k}`,JSON.stringify(v))},del(k){localStorage.removeItem(`${CONFIG.storagePrefix}.${k}`)}};
const State={token:Store.get('token',''),user:null,servers:[],server:null,serverDetail:null,channel:null,scopeType:'CHANNEL',dm:null,dms:[],messages:[],hasMore:false,nextCursor:'',members:[],presence:[],voiceStates:[],personas:[],clientConfig:null,health:null,registrationMode:'UNKNOWN',eventCursor:new Date(Date.now()-60000).toISOString(),pollTimer:null,heartbeatTimer:null,typingTimer:null,rtcTimer:null,replyTo:null,editing:null,pendingFiles:[],sidebarOpen:false,searchQuery:'',incomingCall:null};
function toast(message,type='info',ms=4200){const el=document.createElement('div');el.className=`toast ${type}`;el.innerHTML=esc(message);$('#toasts').append(el);setTimeout(()=>el.remove(),ms)}
function showError(err){console.error(err);toast(err?.message||String(err),'error',6500)}
function hasPerm(bit){return !!((Number(State.serverDetail?.permissions||State.server?.permissions||0)&bit)===bit)}
function canRollInChat(){return !!(State.server&&(State.server?.ownerId===State.user?.id||hasPerm(PERM.ADMIN)||hasPerm(PERM.MANAGE_SERVER)||hasPerm(PERM.MANAGE_MESSAGES)||hasPerm(PERM.MANAGE_ORGANIZER)));}
function avatarHtml(user,size='avatar'){const name=user?.username||user?.nickname||'Unknown';return `<span class="${size}">${user?.avatarDataUrl?`<img src="${esc(user.avatarDataUrl)}" alt="">`:esc(initials(name))}</span>`}
function roleColor(member){return [...(member?.roles||[])].sort((a,b)=>(+b.position||0)-(+a.position||0))[0]?.color||''}
function statusFor(userId){const p=State.presence.find(x=>x.userId===userId);return (p?.status||'OFFLINE').toLowerCase()}
function markdown(text){
  let s=esc(text||'');
  s=s.replace(/```([\s\S]*?)```/g,(_,x)=>`<pre><code>${x}</code></pre>`);
  s=s.replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/\*([^*]+)\*/g,'<em>$1</em>').replace(/~~([^~]+)~~/g,'<s>$1</s>');
  s=s.replace(/(^|\s)(https?:\/\/[^\s<]+)/g,(m,p,u)=>`${p}<a href="${u}" target="_blank" rel="noopener" style="color:#8dc4bd">${u}</a>`);
  s=s.replace(/@([A-Za-z0-9_. -]{2,32})/g,'<span class="mention">@$1</span>').replace(/\n/g,'<br>');return s;
}
function setView(view){$('#boot').classList.toggle('hidden',view!=='boot');$('#auth').classList.toggle('hidden',view!=='auth');$('#app').classList.toggle('hidden',view!=='app')}
function handleModalClose(e){if(e.target.matches('[data-close-modal]'))closeModal()}
function modal(title,body,foot='',large=false){const root=$('#modal-root');root.onclick=null;delete root.dataset.voiceRoom;root.removeEventListener('click',handleModalClose,true);root.addEventListener('click',handleModalClose,true);root.innerHTML=`<div class="modal-layer" data-close-modal><div class="modal ${large?'large':''}" role="dialog" aria-modal="true"><header class="modal-head"><h2>${esc(title)}</h2><button data-close-modal aria-label="Close">×</button></header><div class="modal-body">${body}</div>${foot?`<footer class="modal-foot">${foot}</footer>`:''}</div></div>`}
function closeModal(){const root=$('#modal-root');if(root.dataset.voiceRoom==='true'&&typeof Voice!=='undefined')Voice.roomModalOpen=false;root.innerHTML='';delete root.dataset.voiceRoom}
function contextMenu(x,y,items){const root=$('#context-root');root.innerHTML=`<div class="context-menu" style="left:${Math.min(x,innerWidth-200)}px;top:${Math.min(y,innerHeight-280)}px">${items.map(i=>`<button data-key="${esc(i.key)}" class="${i.danger?'danger-text':''}">${esc(i.label)}</button>`).join('')}</div>`;root.onclick=e=>{const b=e.target.closest('button');if(!b)return;const item=items.find(i=>i.key===b.dataset.key);root.innerHTML='';item?.run()};setTimeout(()=>document.addEventListener('pointerdown',function h(e){if(!root.contains(e.target)){root.innerHTML='';document.removeEventListener('pointerdown',h)}},{once:false}),0)}
async function boot(){
  setView('boot');bindAuth();const pageUrl=new URL(location.href);const resetToken=pageUrl.searchParams.get('resetToken')||'';if(resetToken&&typeof window.openResetPassword==='function'){setView('auth');await window.openResetPassword(resetToken);return}const invite=pageUrl.searchParams.get('invite')||'';if(invite){$('#register-invite').value=invite;await previewInvite(invite)}
  try{State.health=await API.call('health',{},false);State.registrationMode=String(State.health?.registrationMode||'UNKNOWN').toUpperCase()}catch(err){setView('auth');$('#auth-error').textContent=err.message;$('#auth-error').classList.remove('hidden');return}
  if(State.token){try{await restoreSession();return}catch(err){Store.del('token');State.token='';if(err.code!=='SESSION_EXPIRED')showError(err)}}
  setView('auth');
}
function bindAuth(){
  $('#tab-login').onclick=()=>showAuthTab('login');$('#tab-register').onclick=()=>showAuthTab('register');
  $('#login-form').onsubmit=async e=>{e.preventDefault();authError('');try{const d=await API.call('login',{email:$('#login-email').value,password:$('#login-password').value},false);await acceptAuth(d)}catch(err){authError(err.message)}};
  $('#register-form').onsubmit=async e=>{e.preventDefault();authError('');const inviteCode=$('#register-invite').value.trim();const payload={username:$('#register-name').value,email:$('#register-email').value,password:$('#register-password').value};if(inviteCode)payload.inviteCode=inviteCode;try{const d=await API.call('register',payload,false);await acceptAuth(d)}catch(err){if(err.code==='INVITE_REQUIRED')authError('This deployed backend is still set to invite-only registration. Set its existing TABLEGATE_REGISTRATION_MODE property to OPEN; no backend code replacement is required.');else authError(err.message)}};
  $('#register-invite').addEventListener('change',e=>previewInvite(e.target.value.trim()));
}
function showAuthTab(t){const login=t==='login',invite=$('#register-invite').value.trim();$('#tab-login').classList.toggle('active',login);$('#tab-register').classList.toggle('active',!login);$('#login-form').classList.toggle('hidden',!login);$('#register-form').classList.toggle('hidden',login);$('#auth-title').textContent=login?'Welcome back':(invite?'Join this campaign':'Create your TableGate account');$('#auth-subtitle').textContent=login?'Sign in to your campaigns, messages, and live tables.':(invite?'Create an account, then TableGate will join you to the campaign from this link.':'Anyone can create an account, create campaigns, invite people, and build or run games.');authError('')}
function authError(s){$('#auth-error').textContent=s;$('#auth-error').classList.toggle('hidden',!s)}
async function previewInvite(code){if(!code){$('#invite-preview').classList.add('hidden');return}try{const d=await API.call('previewInvite',{code},false);const s=d.server||d;$('#invite-preview').innerHTML=`Invitation to <b>${esc(s.name||'a campaign')}</b>${s.description?` — ${esc(s.description)}`:''}`;$('#invite-preview').classList.remove('hidden');showAuthTab('register')}catch(err){$('#invite-preview').textContent=err.message;$('#invite-preview').classList.remove('hidden')}}
async function acceptAuth(d){State.token=d.token;Store.set('token',State.token);State.user=d.user;await enterApp(d.joinedServerId)}
async function restoreSession(){const d=await API.call('me');State.user=d.user;State.servers=d.servers||[];await enterApp()}
async function enterApp(preferredServer=''){
  setView('app');try{State.clientConfig=await API.call('getClientConfig')}catch{}
  await refreshServers();await refreshDms();renderRail();
  const urlInvite=new URL(location.href).searchParams.get('invite');if(urlInvite){try{await API.call('joinInvite',{code:urlInvite});history.replaceState({},'',location.pathname);await refreshServers();toast('Campaign joined.','success')}catch(err){if(!['ALREADY_MEMBER','INVITE_ALREADY_USED'].includes(err.code))showError(err)}}
  const last=preferredServer||Store.get('lastServer','');const server=State.servers.find(s=>s.id===last)||State.servers[0];if(server)await selectServer(server.id);else selectHome();startPolling();
}
async function logout(){try{await Voice.leave();await API.call('logout')}catch{}Store.del('token');location.reload()}
async function refreshServers(){State.servers=await API.call('listServers')||[];renderRail()}
async function refreshDms(){try{State.dms=await API.call('listDms')||[]}catch{State.dms=[]}}
function renderRail(){const rail=$('#server-rail');rail.innerHTML=`<button class="rail-btn ${!State.server?'active':''}" data-home title="Direct messages">✦</button><div class="rail-sep"></div>${State.servers.map(s=>`<button class="rail-btn server-initial ${State.server?.id===s.id?'active':''}" data-server="${s.id}" title="${esc(s.name)}"><span>${esc(initials(s.name))}</span></button>`).join('')}<button class="rail-btn add" data-add-server title="Create campaign">+</button>`;rail.onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.home!==undefined)selectHome();else if(b.dataset.server)selectServer(b.dataset.server);else if(b.dataset.addServer!==undefined)openCreateServer()}}
function selectHome(){State.server=null;State.serverDetail=null;State.channel=null;State.dm=null;State.messages=[];State.scopeType='DM';Store.del('lastServer');renderAll();refreshDms().then(renderSidebar)}
async function selectServer(id){try{const summary=State.servers.find(s=>s.id===id);if(!summary)return;State.server=summary;Store.set('lastServer',id);State.scopeType='CHANNEL';State.dm=null;State.serverDetail=await API.call('getServer',{serverId:id});State.members=State.serverDetail.members||[];await Promise.all([refreshPresence(),refreshVoiceStates(),refreshPersonas()]);const last=Store.get(`lastChannel.${id}`,'');const ch=State.serverDetail.channels.find(c=>c.id===last)||State.serverDetail.channels.find(c=>['TEXT','ANNOUNCEMENT','HANDOUTS'].includes(c.type))||State.serverDetail.channels[0];renderAll();if(ch)await selectChannel(ch.id)}catch(err){showError(err)}}
async function selectChannel(id){const ch=State.serverDetail?.channels?.find(c=>c.id===id);if(!ch)return;if(['VOICE','VIDEO'].includes(ch.type)){await Voice.joinChannel(ch);return}State.scopeType='CHANNEL';State.channel=ch;State.dm=null;Store.set(`lastChannel.${State.server.id}`,id);State.replyTo=null;State.editing=null;await loadMessages();renderAll();try{await API.call('markRead',{channelId:id})}catch{}}
async function selectDm(id){const dm=State.dms.find(d=>d.id===id);if(!dm)return;State.scopeType='DM';State.dm=dm;State.channel=null;State.replyTo=null;State.editing=null;await loadMessages();renderAll()}
function renderAll(){renderRail();renderSidebar();renderTopbar();renderMessages();renderComposer();renderMembers()}
function renderSidebar(){
  const head=$('#server-head'),scroll=$('#channel-scroll'),bottom=$('#side-bottom');
  if(!State.server){
    head.innerHTML=`<span class="server-title">Direct Messages</span><div class="head-actions"><button class="icon-btn" data-new-dm title="New direct message">＋</button></div>`;
    head.onclick=e=>{if(e.target.closest('[data-new-dm]'))openNewDm()};
    const dmRows=State.dms.map(dm=>{
      const other=dm.displayUser||(dm.participants||[]).find(p=>p.userId!==State.user.id)?.user;
      const participantNames=(dm.participants||[]).filter(p=>p.userId!==State.user.id).map(p=>p.user?.username).filter(Boolean).join(', ');
      const title=dm.name||dm.displayName||dm.displayUser?.username||participantNames||'Direct message';
      return `<div class="dm-item ${State.dm?.id===dm.id?'active':''}" data-dm="${dm.id}">${avatarHtml(other,'dm-avatar')}<div style="min-width:0"><b>${esc(title)}</b><small style="display:block;color:var(--muted)">${dm.type==='GROUP'?'Group DM':'Private conversation'}</small></div></div>`;
    }).join('');
    scroll.innerHTML=`<div class="category-head"><span>Conversations</span></div>${dmRows||'<div class="empty-state" style="height:auto"><p>No direct messages yet.</p></div>'}`;
    scroll.onclick=e=>{const d=e.target.closest('[data-dm]');if(d)selectDm(d.dataset.dm)};
    bottom.innerHTML=userPanel();bindUserPanel();return;
  }
  const canManage=hasPerm(PERM.MANAGE_SERVER)||hasPerm(PERM.MANAGE_CHANNELS)||hasPerm(PERM.CREATE_INVITE);
  head.innerHTML=`<span class="server-title">${esc(State.server.name)}</span><div class="head-actions">${canManage?`<button class="icon-btn" data-server-menu title="Campaign menu">⋮</button>`:''}</div>`;
  head.onclick=e=>{if(e.target.closest('[data-server-menu]'))openServerMenu(e.clientX,e.clientY)};
  const cats=State.serverDetail?.categories||[];const channels=State.serverDetail?.channels||[];
  scroll.innerHTML=cats.map(cat=>{const list=channels.filter(c=>c.categoryId===cat.id);return `<section class="category"><header class="category-head"><span>${esc(cat.name)}</span>${hasPerm(PERM.MANAGE_CHANNELS)?`<button data-add-channel="${cat.id}" title="Add channel">＋</button>`:''}</header>${list.map(channelHtml).join('')}</section>`}).join('')+channels.filter(c=>!c.categoryId).map(channelHtml).join('');
  scroll.onclick=e=>{const add=e.target.closest('[data-add-channel]');if(add){openChannelModal(add.dataset.addChannel);return}const c=e.target.closest('[data-channel]');if(c)selectChannel(c.dataset.channel)};
  scroll.oncontextmenu=e=>{const c=e.target.closest('[data-channel]');if(c&&hasPerm(PERM.MANAGE_CHANNELS)){e.preventDefault();const ch=channels.find(x=>x.id===c.dataset.channel);contextMenu(e.clientX,e.clientY,[{key:'edit',label:'Edit channel',run:()=>openChannelModal(ch.categoryId,ch)},{key:'delete',label:'Delete channel',danger:true,run:()=>deleteChannel(ch)}])}};
  bottom.innerHTML=(Voice.active?voicePanel():'')+userPanel();bindVoiceControls();bindUserPanel();
}
function channelHtml(c){const icon={TEXT:'#',ANNOUNCEMENT:'📣',HANDOUTS:'▣',VOICE:'◉',VIDEO:'▣'}[c.type]||'#';const states=State.voiceStates.filter(v=>v.channelId===c.id);return `<button class="channel ${State.channel?.id===c.id?'active':''} ${Voice.channel?.id===c.id?'voice-connected':''}" data-channel="${c.id}"><span class="type">${icon}</span><span class="name">${esc(c.name)}</span>${c.userLimit?`<span class="badge">${states.length}/${c.userLimit}</span>`:''}</button>${['VOICE','VIDEO'].includes(c.type)&&states.length?`<div class="voice-users">${states.map(v=>`<div class="voice-user ${Voice.speakingUsers.has(v.userId)?'speaking':''}">${avatarHtml(v.user,'mini-avatar')}<span>${esc(v.user?.username||'Player')}</span>${v.muted?' 🔇':''}${v.deafened?' 🎧':''}</div>`).join('')}</div>`:''}`}
function userPanel(){return `<div class="user-panel">${avatarHtml(State.user)}<div class="user-ident"><b>${esc(State.user?.username)}</b><span>#${esc(State.user?.discriminator||'0000')}</span></div><button class="icon-btn" data-user-settings title="Settings">⚙</button><button class="icon-btn" data-logout title="Sign out">↪</button></div>`}
function bindUserPanel(){const b=$('#side-bottom');b?.querySelector('[data-logout]')?.addEventListener('click',logout);b?.querySelector('[data-user-settings]')?.addEventListener('click',openUserSettings)}
function voicePanel(){return `<div class="voice-panel"><div class="voice-status"><div><b>Voice connected</b><small>${esc(Voice.channel?.name||State.dm?.name||'Call')}</small></div><button class="icon-btn" data-voice-disconnect title="Disconnect">☎</button></div><div class="voice-controls"><button class="icon-btn ${Voice.muted?'danger-active':''}" data-mute title="Mute">${Voice.muted?'🔇':'🎙'}</button><button class="icon-btn ${Voice.deafened?'danger-active':''}" data-deafen title="Deafen">🎧</button><button class="icon-btn ${Voice.pushToTalk?'active':''}" data-ptt title="Push to talk">PTT</button><button class="icon-btn ${Voice.videoEnabled?'active':''}" data-video title="Camera">▣</button><button class="icon-btn ${Voice.screenSharing?'active':''}" data-screen title="Share screen">▤</button><button class="icon-btn" data-open-room title="Open room">↗</button></div></div>`}
function bindVoiceControls(){const b=$('#side-bottom');b?.querySelector('[data-voice-disconnect]')?.addEventListener('click',()=>Voice.leave());b?.querySelector('[data-mute]')?.addEventListener('click',()=>Voice.toggleMute());b?.querySelector('[data-deafen]')?.addEventListener('click',()=>Voice.toggleDeafen());b?.querySelector('[data-ptt]')?.addEventListener('click',()=>Voice.togglePtt());b?.querySelector('[data-video]')?.addEventListener('click',()=>Voice.toggleVideo());b?.querySelector('[data-screen]')?.addEventListener('click',()=>Voice.toggleScreen());b?.querySelector('[data-open-room]')?.addEventListener('click',()=>Voice.openRoom())}
function renderTopbar(){const top=$('#topbar');let title='Direct Messages',topic='Private conversations with your party.';if(State.channel){title=`${['VOICE','VIDEO'].includes(State.channel.type)?'◉':'#'} ${State.channel.name}`;topic=State.channel.topic||''}else if(State.dm){title=State.dm.name||State.dm.displayName||'Direct message';topic=State.dm.type==='GROUP'?'Group direct message':'Private direct message'}top.innerHTML=`<button class="icon-btn mobile-only" data-mobile-menu>☰</button><div class="topic"><h2>${esc(title)}</h2><p>${esc(topic)}</p></div>${State.channel?`<button class="icon-btn" data-search title="Search messages">⌕</button><button class="icon-btn" data-pins title="Pinned messages">⌖</button><button class="icon-btn member-toggle hidden" data-members title="Members">♟</button>`:''}${State.dm?`<button class="icon-btn" data-call title="Start or join call">☎</button>`:''}`;top.onclick=e=>{if(e.target.closest('[data-mobile-menu]')){$('#sidebar').classList.toggle('open')}else if(e.target.closest('[data-members]')){$('#members').classList.toggle('open')}else if(e.target.closest('[data-search]'))openSearch();else if(e.target.closest('[data-pins]'))openPins();else if(e.target.closest('[data-call]'))startOrJoinDmCall()}}
async function loadMessages(before=''){if(!(State.channel||State.dm)){State.messages=[];return}try{const d=await API.call('listMessages',{scopeType:State.scopeType,scopeId:State.channel?.id||State.dm?.id,limit:60,before});if(before)State.messages=[...(d.messages||[]),...State.messages];else State.messages=d.messages||[];State.hasMore=!!d.hasMore;State.nextCursor=d.nextCursor||''}catch(err){showError(err)}}
function renderMessages(){const area=$('#message-area');if(!(State.channel||State.dm)){area.innerHTML=`<div class="empty-state"><div><h2>${State.server?'Choose a channel':'Choose a conversation'}</h2><p>${State.server?'Select a text channel or join a voice room.':'Start a direct message with another campaign player.'}</p></div></div>`;return}const scopeName=State.channel?.name||State.dm?.name||'conversation';let html=`${State.hasMore?`<div style="text-align:center"><button class="secondary" data-load-more>Load older messages</button></div>`:''}<div class="welcome"><div class="big-icon">${State.channel?'#':'✉'}</div><h2>Welcome to ${esc(scopeName)}</h2><p>${esc(State.channel?.topic||'This is the beginning of this conversation.')}</p></div>`;let prev=null;for(const m of State.messages){const compact=prev&&prev.authorId===m.authorId&&(new Date(m.createdAt)-new Date(prev.createdAt)<5*60*1000);html+=messageHtml(m,compact);prev=m}area.innerHTML=html;area.querySelector('[data-load-more]')?.addEventListener('click',async()=>{await loadMessages(State.nextCursor);renderMessages()});area.onclick=handleMessageClick;if(!State.searchQuery)requestAnimationFrame(()=>area.scrollTop=area.scrollHeight)}
function messageHtml(m,compact){const author=m.persona?.name||m.author?.username||'Unknown';const color=m.persona?.color||roleColor(State.members.find(x=>x.userId===m.authorId));const type=String(m.messageType||'CHAT').toLowerCase();const reactions=groupReactions(m.reactions||[]);return `<article class="message ${compact?'compact':''}" data-message="${m.id}">${avatarHtml(m.persona?{username:m.persona.name}:m.author)}<div><div class="msg-head"><span class="msg-author" style="${color?`color:${esc(color)}`:''}">${esc(author)}</span>${m.persona?`<span class="pill">character</span>`:''}${m.messageType&&m.messageType!=='CHAT'?`<span class="msg-type ${type==='in_character'?'ic':type==='out_of_character'?'ooc':type}">${esc(type.replaceAll('_',' '))}</span>`:''}<time class="msg-time" title="${esc(new Date(m.createdAt).toLocaleString())}">${compact?fmtTime(m.createdAt):fmtDate(m.createdAt)+' '+fmtTime(m.createdAt)}</time></div>${m.replyToId?`<div class="reply-line">↪ Reply to message</div>`:''}<div class="msg-body ${m.deletedAt?'deleted':''}">${markdown(m.content)}${m.editedAt?` <span class="edited">(edited)</span>`:''}</div>${attachmentsHtml(m.attachments||[])}${reactions.length?`<div class="reactions">${reactions.map(r=>`<button class="reaction ${r.users.includes(State.user.id)?'mine':''}" data-react="${esc(r.emoji)}">${esc(r.emoji)} ${r.users.length}</button>`).join('')}</div>`:''}</div><div class="msg-actions"><button data-action="react" title="React">☺</button><button data-action="reply" title="Reply">↩</button>${m.authorId===State.user.id&&!m.deletedAt?`<button data-action="edit" title="Edit">✎</button>`:''}${(m.authorId===State.user.id||hasPerm(PERM.MANAGE_MESSAGES))&&!m.deletedAt?`<button data-action="delete" title="Delete">🗑</button>`:''}${State.server&&hasPerm(PERM.MANAGE_MESSAGES)&&!m.deletedAt?`<button data-action="pin" title="${m.isPinned?'Unpin':'Pin'}">⌖</button>`:''}</div></article>`}
function groupReactions(list){const map=new Map;for(const r of list){if(!map.has(r.emoji))map.set(r.emoji,{emoji:r.emoji,users:[]});map.get(r.emoji).users.push(r.userId)}return [...map.values()]}
function attachmentsHtml(list){if(!list.length)return '';return `<div class="attachments">${list.map(a=>`<div class="attachment"><span>📎</span><div><b>${esc(a.originalName)}</b><small style="display:block;color:var(--muted)">${esc(a.mimeType)} · ${bytes(a.sizeBytes)}</small></div><button data-download="${a.id}">Download</button></div>`).join('')}</div>`}
async function handleMessageClick(e){const art=e.target.closest('[data-message]');if(!art)return;const m=State.messages.find(x=>x.id===art.dataset.message);const dl=e.target.closest('[data-download]');if(dl){await downloadAttachment(dl.dataset.download);return}const react=e.target.closest('[data-react]');if(react){await toggleReaction(m,react.dataset.react);return}const action=e.target.closest('[data-action]')?.dataset.action;if(!action)return;if(action==='reply'){State.replyTo=m;State.editing=null;renderComposer()}if(action==='edit'){State.editing=m;State.replyTo=null;renderComposer();setTimeout(()=>$('#message-input')?.focus(),0)}if(action==='delete'&&confirm('Delete this message?')){try{await API.call('deleteMessage',{messageId:m.id});await loadMessages();renderMessages()}catch(err){showError(err)}}if(action==='pin'){try{await API.call('pinMessage',{messageId:m.id,pinned:!m.isPinned});await loadMessages();renderMessages()}catch(err){showError(err)}}if(action==='react')openReactionPicker(m)}
function openReactionPicker(m){const choices=['👍','❤️','😂','🎲','⚔️','🛡️','✨','👀','✅','❌','🔥','🐉'];contextMenu(innerWidth/2,innerHeight/2,choices.map(x=>({key:x,label:x,run:()=>toggleReaction(m,x)})))}
async function toggleReaction(m,emoji){const mine=(m.reactions||[]).some(r=>r.emoji===emoji&&r.userId===State.user.id);try{await API.call(mine?'removeReaction':'addReaction',{messageId:m.id,emoji});await loadMessages();renderMessages()}catch(err){showError(err)}}
function renderComposer(){const root=$('#composer-area');if(!(State.channel||State.dm)){root.innerHTML='';return}const canSend=!State.server||hasPerm(PERM.SEND_MESSAGES);if(!canSend){root.innerHTML=`<div class="composer-wrap"><div class="info-box">You do not have permission to send messages here.</div></div>`;return}const types=State.channel?`<select id="message-type"><option value="CHAT">Player</option><option value="IN_CHARACTER">In character</option><option value="OUT_OF_CHARACTER">Out of character</option>${State.channel.type==='HANDOUTS'&&hasPerm(PERM.MANAGE_HANDOUTS)?`<option value="HANDOUT">Handout</option>`:''}</select>`:'';root.innerHTML=`<div class="typing" id="typing-line"></div><div class="composer-wrap">${State.replyTo?`<div class="reply-banner"><span>Replying to <b>${esc(State.replyTo.persona?.name||State.replyTo.author?.username)}</b></span><button data-cancel-reply>×</button></div>`:''}${State.editing?`<div class="reply-banner"><span>Editing message</span><button data-cancel-edit>×</button></div>`:''}${State.pendingFiles.length?`<div class="upload-banner"><span>${State.pendingFiles.length} attachment${State.pendingFiles.length===1?'':'s'} ready</span><button data-clear-files>×</button></div>`:''}<div class="composer ${(State.replyTo||State.editing||State.pendingFiles.length)?'has-banner':''}"><div class="composer-tools"><button class="icon-btn" data-attach title="Attach file">＋</button>${State.server?`${canRollInChat()?'<button class="icon-btn" data-dice title="Roll dice in chat">🎲</button>':''}<button class="icon-btn" data-persona title="Character personas">♟</button>`:''}</div>${types}<textarea id="message-input" rows="1" maxlength="8000" placeholder="Message ${esc(State.channel?'#'+State.channel.name:State.dm?.name||'conversation')}">${State.editing?esc(State.editing.content):''}</textarea><button class="primary send" data-send>➤</button><input id="file-input" type="file" multiple hidden></div></div>`;const input=$('#message-input');input.addEventListener('input',()=>{input.style.height='auto';input.style.height=Math.min(input.scrollHeight,160)+'px';notifyTyping()});input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendMessage()}});root.onclick=e=>{if(e.target.closest('[data-send]'))sendMessage();else if(e.target.closest('[data-attach]'))$('#file-input').click();else if(e.target.closest('[data-dice]'))openDice();else if(e.target.closest('[data-persona]'))openPersonas();else if(e.target.closest('[data-cancel-reply]')){State.replyTo=null;renderComposer()}else if(e.target.closest('[data-cancel-edit]')){State.editing=null;renderComposer()}else if(e.target.closest('[data-clear-files]')){State.pendingFiles=[];renderComposer()}};$('#file-input').onchange=e=>queueFiles(e.target.files);refreshTyping()}
async function sendMessage(){
  const input=$('#message-input'),content=input?.value.trim()||'';
  if(State.editing){
    if(!content)return;
    try{await API.call('editMessage',{messageId:State.editing.id,content});State.editing=null;await loadMessages();renderAll()}
    catch(err){showError(err)}
    return;
  }
  if(!content&&!State.pendingFiles.length)return;
  const btn=$('[data-send]'),uploadedAttachmentIds=[];
  if(btn)btn.disabled=true;
  try{
    const attachmentIds=[];
    for(const file of State.pendingFiles){
      const base64=await fileToBase64(file);
      const attachment=await API.call('uploadAttachment',{fileName:file.name,mimeType:file.type||'application/octet-stream',base64,serverId:State.server?.id||'',dmId:State.dm?.id||''});
      attachmentIds.push(attachment.id);
      uploadedAttachmentIds.push(attachment.id);
    }
    const type=$('#message-type')?.value||'CHAT';
    let personaId='';
    if(type==='IN_CHARACTER')personaId=Store.get(`persona.${State.server.id}`,'');
    const mentions=parseMentions(content);
    await API.call('sendMessage',{scopeType:State.scopeType,scopeId:State.channel?.id||State.dm?.id,content,attachmentIds,replyToId:State.replyTo?.id||'',messageType:type,personaId,mentionUserIds:mentions.users,mentionRoleIds:mentions.roles,mentionsEveryone:mentions.everyone});
    uploadedAttachmentIds.length=0;
    State.replyTo=null;
    State.pendingFiles=[];
    input.value='';
    await loadMessages();
    renderAll();
  }catch(err){
    if(uploadedAttachmentIds.length)await Promise.allSettled(uploadedAttachmentIds.map(attachmentId=>API.call('deleteAttachment',{attachmentId})));
    showError(err);
  }finally{if(btn)btn.disabled=false}
}
function parseMentions(text){const users=[],roles=[];for(const m of State.members){const name=m.nickname||m.user?.username;if(name&&new RegExp(`(^|\\s)@${name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}(?=\\s|$|[.,!?])`,'i').test(text))users.push(m.userId)}for(const r of State.serverDetail?.roles||[]){if(new RegExp(`(^|\\s)@${r.name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}(?=\\s|$|[.,!?])`,'i').test(text))roles.push(r.id)}return{users,roles,everyone:/@everyone\b/i.test(text)}}
async function queueFiles(files){for(const f of files){if(f.size>(State.clientConfig?.maxUploadBytes||5*1024*1024)){toast(`${f.name} is too large.`,'error');continue}State.pendingFiles.push(f)}renderComposer()}
function fileToBase64(file){return new Promise((resolve,reject)=>{const r=new FileReader;r.onload=()=>resolve(String(r.result).split(',')[1]||'');r.onerror=reject;r.readAsDataURL(file)})}
async function downloadAttachment(id){try{const d=await API.call('downloadAttachment',{attachmentId:id});const a=d.attachment;const bin=atob(d.base64);const bytesArr=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytesArr[i]=bin.charCodeAt(i);const url=URL.createObjectURL(new Blob([bytesArr],{type:a.mimeType}));const link=document.createElement('a');link.href=url;link.download=a.originalName;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(err){showError(err)}}
let typingDebounce=0;function notifyTyping(){clearTimeout(typingDebounce);typingDebounce=setTimeout(()=>API.call('startTyping',{scopeType:State.scopeType,scopeId:State.channel?.id||State.dm?.id}).catch(()=>{}),250)}
async function refreshTyping(){try{const list=await API.call('listTyping',{scopeType:State.scopeType,scopeId:State.channel?.id||State.dm?.id});const el=$('#typing-line');if(el)el.textContent=list.length?`${list.map(x=>x.user?.username).join(', ')} ${list.length===1?'is':'are'} typing…`:''}catch{}}
function renderMembers(){const root=$('#members-list');if(!State.server){root.innerHTML='';return}const members=[...State.members].sort((a,b)=>statusFor(a.userId)==='offline'&&statusFor(b.userId)!=='offline'?1:-1);const groups=new Map;for(const m of members){const top=[...(m.roles||[])].sort((a,b)=>(+b.position||0)-(+a.position||0))[0];const key=top?.name||'Players';if(!groups.has(key))groups.set(key,[]);groups.get(key).push(m)}root.innerHTML=[...groups.entries()].map(([role,list])=>`<div class="role-heading">${esc(role)} — ${list.length}</div>${list.map(memberHtml).join('')}`).join('');root.onclick=e=>{const m=e.target.closest('[data-member]');if(m)openMemberCard(State.members.find(x=>x.userId===m.dataset.member))}}
function memberHtml(m){const st=statusFor(m.userId);return `<div class="member ${st==='offline'?'offline':''}" data-member="${m.userId}">${avatarHtml(m.user)}<span class="status-dot ${st}"></span><div class="member-name" style="${roleColor(m)?`color:${roleColor(m)}`:''}">${esc(m.nickname||m.user?.username)}${m.userId===State.server?.ownerId?' 👑':''}<small>${esc(m.user?.customStatus||'')}</small></div></div>`}
function openMemberCard(m){if(!m)return;const canManage=m.userId!==State.user.id&&(hasPerm(PERM.KICK_MEMBERS)||hasPerm(PERM.BAN_MEMBERS)||hasPerm(PERM.MANAGE_ROLES));modal(m.nickname||m.user?.username,`<div class="row">${avatarHtml(m.user)}<div><b>${esc(m.user?.displayTag)}</b><p style="margin:2px 0;color:var(--muted)">${esc(m.user?.bio||'No profile text.')}</p></div></div><div class="row wrap" style="margin-top:14px">${(m.roles||[]).map(r=>`<span class="pill" style="border:1px solid ${esc(r.color||'#555')}">${esc(r.name)}</span>`).join('')}</div>${canManage?`<div class="row wrap" style="margin-top:18px"><button class="secondary" data-manage-roles>Manage roles</button>${hasPerm(PERM.KICK_MEMBERS)?`<button class="danger" data-kick>Kick</button>`:''}${hasPerm(PERM.BAN_MEMBERS)?`<button class="danger" data-ban>Ban</button>`:''}</div>`:''}`);const r=$('#modal-root');r.querySelector('[data-manage-roles]')?.addEventListener('click',()=>openRoleAssignment(m));r.querySelector('[data-kick]')?.addEventListener('click',()=>moderateMember('kickMember',m));r.querySelector('[data-ban]')?.addEventListener('click',()=>moderateMember('banMember',m))}
async function moderateMember(action,m){const reason=prompt(`Reason to ${action==='kickMember'?'kick':'ban'} ${m.user?.username}:`,'');if(reason===null)return;try{await API.call(action,{serverId:State.server.id,userId:m.userId,reason});closeModal();await selectServer(State.server.id);toast('Member updated.','success')}catch(err){showError(err)}}
function openRoleAssignment(m){const roles=State.serverDetail.roles.filter(r=>r.managedKey!=='CREATOR');modal(`Roles for ${m.user?.username}`,roles.map(r=>`<label class="list-row"><input type="checkbox" data-role="${r.id}" ${(m.roles||[]).some(x=>x.id===r.id)?'checked':''}><span class="pill" style="border:1px solid ${esc(r.color)}">${esc(r.name)}</span></label>`).join(''),`<button class="secondary" data-close-modal>Cancel</button><button class="primary" data-save-roles>Save roles</button>`);$('#modal-root').querySelector('[data-save-roles]').onclick=async()=>{try{for(const r of roles){const checked=$(`[data-role="${r.id}"]`).checked;const has=(m.roles||[]).some(x=>x.id===r.id);if(checked&&!has)await API.call('assignRole',{serverId:State.server.id,userId:m.userId,roleId:r.id});if(!checked&&has)await API.call('removeRole',{serverId:State.server.id,userId:m.userId,roleId:r.id})}closeModal();await selectServer(State.server.id)}catch(err){showError(err)}}}
function openServerMenu(x,y){const items=[];if(hasPerm(PERM.CREATE_INVITE))items.push({key:'invite',label:'Invite players',run:openInvites});if(hasPerm(PERM.MANAGE_CHANNELS))items.push({key:'channel',label:'Create channel',run:()=>openChannelModal('')});if(hasPerm(PERM.MANAGE_ROLES))items.push({key:'roles',label:'Roles and permissions',run:openRoles});if(hasPerm(PERM.MANAGE_SERVER))items.push({key:'settings',label:'Campaign settings',run:openServerSettings});if(hasPerm(PERM.VIEW_AUDIT_LOG))items.push({key:'audit',label:'Audit log',run:openAudit});items.push({key:'about',label:'Connection details',run:openConnectionInfo});if(State.server.ownerId!==State.user.id)items.push({key:'leave',label:'Leave campaign',danger:true,run:leaveServer});contextMenu(x||330,y||55,items)}
function openCreateServer(){modal('Create a campaign',`<div class="field"><label>Campaign name</label><input id="server-name" maxlength="80" value="New TTRPG Campaign"></div><div class="field"><label>Description</label><textarea id="server-desc" maxlength="1000" rows="4"></textarea></div><div class="split"><div class="field"><label>Invite expires after</label><select id="server-expiry"><option value="24">24 hours</option><option value="168" selected>7 days</option><option value="720">30 days</option></select></div><div class="field"><label>Maximum uses</label><input id="server-uses" type="number" min="0" max="1000" value="0"><small>0 means unlimited.</small></div></div>`,`<button class="secondary" data-close-modal>Cancel</button><button class="primary" data-create-server>Create campaign</button>`);$('#modal-root').querySelector('[data-create-server]').onclick=async()=>{try{const d=await API.call('createServer',{name:$('#server-name').value,description:$('#server-desc').value,expiresInHours:+$('#server-expiry').value,maxUses:+$('#server-uses').value});closeModal();await refreshServers();await selectServer(d.server.id);showInviteResult(d.invite)}catch(err){showError(err)}}}
function showInviteResult(invite){const link=inviteLink(invite.code);modal('Campaign created',`<p>Your private campaign is ready. Share this link only with the players you are inviting.</p><div class="copy-box"><input value="${esc(link)}" readonly><button class="primary" data-copy>Copy</button></div>`);$('#modal-root').querySelector('[data-copy]').onclick=()=>copyText(link)}
function inviteLink(code){const u=new URL(location.href);u.search='';u.hash='';u.searchParams.set('invite',code);return u.toString()}
async function copyText(t){try{await navigator.clipboard.writeText(t);toast('Copied.','success')}catch{prompt('Copy this link:',t)}}
async function openInvites(){try{const list=await API.call('listInvites',{serverId:State.server.id});modal('Invite players',`<div class="card"><div class="split"><div class="field"><label>Expires after</label><select id="invite-expiry"><option value="24">24 hours</option><option value="168" selected>7 days</option><option value="720">30 days</option><option value="8760">1 year</option></select></div><div class="field"><label>Maximum uses</label><input id="invite-uses" type="number" min="0" max="1000" value="0"></div></div><button class="primary" data-create-invite>Create invite link</button></div><div id="invite-list">${list.map(inviteRow).join('')||'<p>No active invites.</p>'}</div>`);const root=$('#modal-root');root.querySelector('[data-create-invite]').onclick=async()=>{try{const i=await API.call('createInvite',{serverId:State.server.id,expiresInHours:+$('#invite-expiry').value,maxUses:+$('#invite-uses').value});openInvites();setTimeout(()=>copyText(inviteLink(i.code)),50)}catch(err){showError(err)}};root.onclick=e=>{const copy=e.target.closest('[data-copy-invite]');if(copy)copyText(inviteLink(copy.dataset.copyInvite));const revoke=e.target.closest('[data-revoke-invite]');if(revoke)API.call('revokeInvite',{inviteId:revoke.dataset.revokeInvite}).then(openInvites).catch(showError)}}catch(err){showError(err)}}
function inviteRow(i){return `<div class="list-row"><div class="grow"><b>${esc(i.code)}</b><small style="display:block;color:var(--muted)">${i.uses||0}${i.maxUses?'/'+i.maxUses:''} uses · expires ${esc(new Date(i.expiresAt).toLocaleString())}</small></div><button class="secondary" data-copy-invite="${i.code}">Copy</button><button class="danger" data-revoke-invite="${i.id}">Revoke</button></div>`}
function openChannelModal(categoryId='',ch=null){const cats=State.serverDetail.categories;modal(ch?'Edit channel':'Create channel',`<div class="split"><div class="field"><label>Name</label><input id="channel-name" maxlength="80" value="${esc(ch?.name||'new-channel')}"></div><div class="field"><label>Type</label><select id="channel-type" ${ch?'disabled':''}><option value="TEXT">Text</option><option value="ANNOUNCEMENT">Announcement</option><option value="HANDOUTS">Handouts</option><option value="VOICE">Voice</option><option value="VIDEO">Video</option></select></div></div><div class="field"><label>Category</label><select id="channel-category"><option value="">No category</option>${cats.map(c=>`<option value="${c.id}" ${c.id===(ch?.categoryId||categoryId)?'selected':''}>${esc(c.name)}</option>`).join('')}</select></div><div class="field"><label>Topic</label><textarea id="channel-topic" maxlength="1024" rows="3">${esc(ch?.topic||'')}</textarea></div><div class="split"><div class="field"><label>Voice user limit</label><input id="channel-limit" type="number" min="0" max="99" value="${ch?.userLimit||0}"></div><div class="field"><label>Slow mode seconds</label><input id="channel-slow" type="number" min="0" max="21600" value="${ch?.slowmodeSeconds||0}"></div></div>`,`<button class="secondary" data-close-modal>Cancel</button><button class="primary" data-save-channel>${ch?'Save':'Create'}</button>`);if(ch)$('#channel-type').value=ch.type;$('#modal-root').querySelector('[data-save-channel]').onclick=async()=>{try{const p={serverId:State.server.id,name:$('#channel-name').value,type:$('#channel-type').value,categoryId:$('#channel-category').value,topic:$('#channel-topic').value,userLimit:+$('#channel-limit').value,slowmodeSeconds:+$('#channel-slow').value};await API.call(ch?'updateChannel':'createChannel',ch?{...p,channelId:ch.id}:p);closeModal();await selectServer(State.server.id)}catch(err){showError(err)}}}
async function deleteChannel(ch){if(ch.isSystem){toast('The system general channel cannot be deleted.','error');return}if(!confirm(`Delete #${ch.name}?`))return;try{await API.call('deleteChannel',{channelId:ch.id});await selectServer(State.server.id)}catch(err){showError(err)}}
function openServerSettings(){const s=State.serverDetail.server;modal('Campaign settings',`<div class="field"><label>Name</label><input id="edit-server-name" value="${esc(s.name)}" maxlength="80"></div><div class="field"><label>Description</label><textarea id="edit-server-desc" maxlength="1000" rows="5">${esc(s.description||'')}</textarea></div><label class="list-row"><input id="edit-invite-only" type="checkbox" ${s.inviteOnly?'checked':''}> Invite-only membership</label>${s.ownerId===State.user.id?`<div class="card"><h3>Creator controls</h3><p>Ownership can be transferred to another current member.</p><button class="danger" data-delete-server style="margin-top:10px">Delete campaign</button></div>`:''}`,`<button class="secondary" data-close-modal>Cancel</button><button class="primary" data-save-server>Save</button>`);const root=$('#modal-root');root.querySelector('[data-save-server]').onclick=async()=>{try{await API.call('updateServer',{serverId:State.server.id,name:$('#edit-server-name').value,description:$('#edit-server-desc').value,inviteOnly:$('#edit-invite-only').checked});closeModal();await refreshServers();await selectServer(State.server.id)}catch(err){showError(err)}};root.querySelector('[data-delete-server]')?.addEventListener('click',async()=>{if(!confirm('Permanently delete this campaign server?'))return;try{await API.call('deleteServer',{serverId:State.server.id});closeModal();State.server=null;await refreshServers();State.servers[0]?selectServer(State.servers[0].id):selectHome()}catch(err){showError(err)}})}
async function leaveServer(){if(!confirm(`Leave ${State.server.name}?`))return;try{await API.call('leaveServer',{serverId:State.server.id});State.server=null;await refreshServers();State.servers[0]?selectServer(State.servers[0].id):selectHome()}catch(err){showError(err)}}
async function openRoles(){try{const roles=await API.call('listRoles',{serverId:State.server.id});modal('Roles and permissions',`<button class="primary" data-new-role>Create role</button><div style="margin-top:12px">${roles.map(r=>`<div class="list-row"><span class="pill" style="border:1px solid ${esc(r.color)}">${esc(r.name)}</span><div class="grow"><small style="color:var(--muted)">${r.managedKey||'Custom role'} · ${r.permissions} permission mask</small></div>${!r.isManaged?`<button class="secondary" data-edit-role="${r.id}">Edit</button><button class="danger" data-delete-role="${r.id}">Delete</button>`:''}</div>`).join('')}</div>`);const root=$('#modal-root');root.querySelector('[data-new-role]').onclick=()=>openRoleEditor();root.onclick=e=>{const edit=e.target.closest('[data-edit-role]');if(edit)openRoleEditor(roles.find(r=>r.id===edit.dataset.editRole));const del=e.target.closest('[data-delete-role]');if(del&&confirm('Delete this role?'))API.call('deleteRole',{roleId:del.dataset.deleteRole}).then(openRoles).catch(showError)}}catch(err){showError(err)}}
function openRoleEditor(role=null){const perms=Object.entries(PERM).filter(([k])=>k!=='ADMIN');modal(role?'Edit role':'Create role',`<div class="split"><div class="field"><label>Name</label><input id="role-name" maxlength="64" value="${esc(role?.name||'Adventurer')}"></div><div class="field"><label>Color</label><input id="role-color" type="color" value="${esc(role?.color||'#7ba05b')}"></div></div><div class="permission-grid">${perms.map(([k,v])=>`<label><input type="checkbox" data-perm="${v}" ${role&&((role.permissions&v)===v)?'checked':''}> ${esc(k.toLowerCase().replaceAll('_',' '))}</label>`).join('')}</div>`,`<button class="secondary" data-close-modal>Cancel</button><button class="primary" data-save-role>Save</button>`);$('#modal-root').querySelector('[data-save-role]').onclick=async()=>{let permissions=0;$$('[data-perm]:checked').forEach(x=>permissions|=+x.dataset.perm);try{await API.call(role?'updateRole':'createRole',role?{roleId:role.id,name:$('#role-name').value,color:$('#role-color').value,permissions}:{serverId:State.server.id,name:$('#role-name').value,color:$('#role-color').value,permissions});openRoles();await selectServer(State.server.id)}catch(err){showError(err)}}}
async function openAudit(){try{const rows=await API.call('listAuditLog',{serverId:State.server.id,limit:100});modal('Campaign audit log',rows.map(a=>`<div class="list-row"><div class="grow"><b>${esc(a.action.replaceAll('_',' '))}</b><small style="display:block;color:var(--muted)">${esc(a.targetType)} ${esc(a.targetId)} · ${esc(new Date(a.createdAt).toLocaleString())}</small></div></div>`).join('')||'<p>No audit events.</p>','',true)}catch(err){showError(err)}}
function openConnectionInfo(){modal('Connection details',`<div class="card"><h3>Backend</h3><p>${esc(CONFIG.backendUrl)}</p></div><div class="card"><h3>Apps Script library</h3><p>${esc(CONFIG.libraryId)} · version ${esc(CONFIG.libraryVersion)}</p></div><div class="card"><h3>API</h3><p>${esc(State.clientConfig?.apiVersion||'1.0.0')} · schema ${esc(State.clientConfig?.schemaVersion||'')}</p></div><div class="card"><h3>Voice transport</h3><p>Peer-to-peer WebRTC with backend-authorized signaling. A TURN server may be required for players behind strict networks.</p></div>`)}
function openUserSettings(){modal('Player settings',`<div class="field"><label>Display name</label><input id="profile-name" maxlength="32" value="${esc(State.user.username)}"></div><div class="field"><label>Profile text</label><textarea id="profile-bio" maxlength="1000" rows="5">${esc(State.user.bio||'')}</textarea></div><div class="field"><label>Custom status</label><input id="profile-status" maxlength="128" value="${esc(State.user.customStatus||'')}"></div><label class="list-row"><input id="profile-discoverable" type="checkbox" ${State.user.discoverable?'checked':''}> Allow other registered players to find me for direct messages</label>`,`<button class="secondary" data-close-modal>Cancel</button><button class="primary" data-save-profile>Save</button>`);$('#modal-root').querySelector('[data-save-profile]').onclick=async()=>{try{State.user=await API.call('updateProfile',{username:$('#profile-name').value,bio:$('#profile-bio').value,customStatus:$('#profile-status').value,discoverable:$('#profile-discoverable').checked});closeModal();renderAll()}catch(err){showError(err)}}}
function openSearch(){modal('Search this channel',`<div class="field"><label>Search terms</label><input id="search-text" autocomplete="off"></div><div id="search-results"></div>`,`<button class="secondary" data-close-modal>Close</button><button class="primary" data-run-search>Search</button>`);$('#modal-root').querySelector('[data-run-search]').onclick=async()=>{try{const d=await API.call('searchMessages',{scopeType:State.scopeType,scopeId:State.channel?.id||State.dm?.id,query:$('#search-text').value,limit:100});const list=d.messages||d;$('#search-results').innerHTML=list.map(m=>`<div class="card"><b>${esc(m.persona?.name||m.author?.username)}</b><small style="color:var(--muted)"> · ${esc(new Date(m.createdAt).toLocaleString())}</small><p>${markdown(m.content)}</p></div>`).join('')||'<p>No matches.</p>'}catch(err){showError(err)}}}
async function openPins(){try{const list=await API.call('listPins',{scopeType:State.scopeType,scopeId:State.channel?.id||State.dm?.id});modal('Pinned messages',list.map(m=>`<div class="card"><b>${esc(m.persona?.name||m.author?.username)}</b><small style="color:var(--muted)"> · ${esc(new Date(m.createdAt).toLocaleString())}</small><p>${markdown(m.content)}</p></div>`).join('')||'<p>No pinned messages.</p>')}catch(err){showError(err)}}
function openDice(){if(!canRollInChat()){toast('Chat dice are limited to campaign runners and moderators. Use Session Dice for participant rolls.','error');return}modal('Auditable dice roll',`<div class="field"><label>Expression</label><input id="dice-expression" value="1d20" placeholder="1d20+5"></div><div class="field"><label>Label</label><input id="dice-label" maxlength="200" placeholder="Perception check"></div><label class="list-row"><input id="dice-post" type="checkbox" checked> Post result in this channel</label><div id="dice-output"></div>`,`<button class="secondary" data-close-modal>Close</button><button class="primary" data-roll>Roll dice</button>`);$('#modal-root').querySelector('[data-roll]').onclick=async()=>{try{const d=await API.call('rollDice',{channelId:State.channel.id,expression:$('#dice-expression').value,label:$('#dice-label').value,personaId:Store.get(`persona.${State.server.id}`,''),postMessage:$('#dice-post').checked});$('#dice-output').innerHTML=`<div class="dice-result">${d.total}</div><div class="card">${d.detail.map(t=>t.type==='dice'?`${t.count}d${t.sides}: [${t.rolls.join(', ')}] = ${t.subtotal}`:`Modifier: ${t.subtotal}`).join('<br>')}</div>`;if($('#dice-post').checked){await loadMessages();renderMessages()}}catch(err){showError(err)}}}
async function refreshPersonas(){if(!State.server)return;try{State.personas=await API.call('listPersonas',{serverId:State.server.id,ownOnly:true})||[]}catch{State.personas=[]}}
function openPersonas(){modal('Character personas',`<div class="card"><div class="field"><label>Active character</label><select id="active-persona"><option value="">Player account</option>${State.personas.map(p=>`<option value="${p.id}" ${Store.get(`persona.${State.server.id}`,'')===p.id?'selected':''}>${esc(p.name)}</option>`).join('')}</select></div><button class="primary" data-new-persona>Create character persona</button></div>${State.personas.map(p=>`<div class="list-row"><span class="avatar" style="background:${esc(p.color)}">${esc(initials(p.name))}</span><div class="grow"><b>${esc(p.name)}</b><small style="display:block;color:var(--muted)">${esc(p.description||'')}</small></div><button class="secondary" data-edit-persona="${p.id}">Edit</button><button class="danger" data-delete-persona="${p.id}">Delete</button></div>`).join('')}`);const root=$('#modal-root');root.querySelector('#active-persona').onchange=e=>Store.set(`persona.${State.server.id}`,e.target.value);root.querySelector('[data-new-persona]').onclick=()=>openPersonaEditor();root.onclick=e=>{const edit=e.target.closest('[data-edit-persona]');if(edit)openPersonaEditor(State.personas.find(p=>p.id===edit.dataset.editPersona));const del=e.target.closest('[data-delete-persona]');if(del&&confirm('Delete this persona?'))API.call('deletePersona',{personaId:del.dataset.deletePersona}).then(async()=>{await refreshPersonas();openPersonas()}).catch(showError)}}
function openPersonaEditor(p=null){modal(p?'Edit character':'Create character',`<div class="split"><div class="field"><label>Name</label><input id="persona-name" maxlength="80" value="${esc(p?.name||'')}"></div><div class="field"><label>Color</label><input id="persona-color" type="color" value="${esc(p?.color||'#7ba05b')}"></div></div><div class="field"><label>Description</label><textarea id="persona-desc" maxlength="1000" rows="4">${esc(p?.description||'')}</textarea></div><label class="list-row"><input id="persona-default" type="checkbox" ${p?.isDefault?'checked':''}> Default character for this campaign</label>`,`<button class="secondary" data-close-modal>Cancel</button><button class="primary" data-save-persona>Save</button>`);$('#modal-root').querySelector('[data-save-persona]').onclick=async()=>{try{const d=await API.call(p?'updatePersona':'createPersona',p?{personaId:p.id,name:$('#persona-name').value,color:$('#persona-color').value,description:$('#persona-desc').value,isDefault:$('#persona-default').checked}:{serverId:State.server.id,name:$('#persona-name').value,color:$('#persona-color').value,description:$('#persona-desc').value,isDefault:$('#persona-default').checked});if($('#persona-default').checked)Store.set(`persona.${State.server.id}`,d.id);await refreshPersonas();openPersonas()}catch(err){showError(err)}}}
async function openNewDm(){modal('Start a direct message',`<div class="field"><label>Find a player</label><input id="user-search" placeholder="Username or display tag"></div><button class="primary" data-find-user>Search</button><div id="user-results" style="margin-top:12px"></div>`);$('#modal-root').querySelector('[data-find-user]').onclick=async()=>{try{const list=await API.call('searchUsers',{query:$('#user-search').value,limit:30});$('#user-results').innerHTML=list.map(u=>`<button class="dm-item wide" data-user-id="${u.id}">${avatarHtml(u,'dm-avatar')}<span>${esc(u.displayTag)}</span></button>`).join('')||'<p>No players found.</p>';$('#user-results').onclick=e=>{const b=e.target.closest('[data-user-id]');if(b)createDm(b.dataset.userId)}}catch(err){showError(err)}}}
async function createDm(userId){try{const dm=await API.call('createDm',{userId});closeModal();await refreshDms();await selectDm(dm.id)}catch(err){showError(err)}}
async function startOrJoinDmCall(){if(!State.dm)return;try{let call=await API.call('getActiveCall',{dmId:State.dm.id}),iceServers=State.clientConfig?.iceServers||[];if(!call)call=await API.call('startCall',{dmId:State.dm.id});const mine=(call.participants||[]).find(p=>p.userId===State.user.id);if(call.initiatorId!==State.user.id&&mine?.status!=='JOINED'){const a=await API.call('joinCall',{dmId:State.dm.id});call=a.call;iceServers=a.iceServers||iceServers}const peers=(call.participants||[]).filter(p=>p.status==='JOINED'&&p.userId!==State.user.id).map(p=>({userId:p.userId,user:p.user}));await Voice.joinRoom({roomType:'DM_CALL',roomId:State.dm.id,label:State.dm.name||'Direct call',peers,iceServers})}catch(err){showError(err)}}
async function refreshPresence(){if(!State.server)return;try{State.presence=await API.call('listPresence',{serverId:State.server.id})||[]}catch{}}
async function refreshVoiceStates(){if(!State.server)return;try{State.voiceStates=await API.call('listVoiceStates',{serverId:State.server.id})||[];Voice.reconcile(State.voiceStates);renderSidebar()}catch{}}
function startPolling(){clearInterval(State.pollTimer);clearInterval(State.heartbeatTimer);State.pollTimer=setInterval(pollEvents,State.clientConfig?.polling?.eventsMs||CONFIG.defaultPollMs);State.heartbeatTimer=setInterval(()=>API.call('heartbeat',{status:'ONLINE',customStatus:State.user?.customStatus||''}).catch(()=>{}),State.clientConfig?.polling?.presenceHeartbeatMs||45000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)pollEvents()})}
async function pollEvents(){if(!State.token)return;try{const d=await API.call('pollEvents',{after:State.eventCursor,serverIds:State.server?[State.server.id]:[],channelIds:State.channel?[State.channel.id]:[],dmIds:State.dm?[State.dm.id]:[],limit:100});State.eventCursor=d.cursor||new Date().toISOString();let reloadMessages=false,reloadServer=false,reloadDms=false,reloadVoice=false;for(const ev of d.events||[]){if(ev.eventType.startsWith('MESSAGE_')||ev.eventType==='MESSAGES_PURGED')reloadMessages=true;if(ev.eventType.includes('CHANNEL')||ev.eventType.includes('MEMBER')||ev.eventType.includes('ROLE')||ev.eventType.includes('SERVER_'))reloadServer=true;if(ev.audienceType==='DM'||ev.eventType.includes('DM_'))reloadDms=true;if(ev.eventType.includes('VOICE_'))reloadVoice=true;if(ev.eventType==='INCOMING_CALL'){State.incomingCall=ev.payload?.call;showIncomingCall(State.incomingCall)}}if(reloadMessages&&(State.channel||State.dm)){await loadMessages();renderMessages()}if(reloadDms){await refreshDms();renderSidebar()}if(reloadServer&&State.server){State.serverDetail=await API.call('getServer',{serverId:State.server.id});State.members=State.serverDetail.members||[];renderAll()}if(reloadVoice){await refreshVoiceStates()}await refreshTyping();if(State.server)await refreshPresence();renderMembers()}catch(err){if(err.code==='SESSION_EXPIRED'){Store.del('token');location.reload()}}}
function showIncomingCall(call){if(!call||Voice.active)return;const dm=State.dms.find(d=>d.id===call.dmId);modal('Incoming call',`<p><b>${esc(dm?.name||'A player')}</b> is calling.</p>`,`<button class="danger" data-decline-call>Decline</button><button class="primary" data-accept-call>Accept</button>`);const root=$('#modal-root');root.querySelector('[data-decline-call]').onclick=()=>API.call('declineCall',{dmId:call.dmId}).then(closeModal).catch(showError);root.querySelector('[data-accept-call]').onclick=async()=>{try{const a=await API.call('acceptCall',{dmId:call.dmId});closeModal();const peers=(a.call.participants||[]).filter(p=>p.status==='JOINED'&&p.userId!==State.user.id).map(p=>({userId:p.userId,user:p.user}));await Voice.joinRoom({roomType:'DM_CALL',roomId:call.dmId,label:dm?.name||'Direct call',peers,iceServers:a.iceServers})}catch(err){showError(err)}}}
const Voice={active:false,roomType:'',roomId:'',channel:null,label:'',localStream:null,screenStream:null,peers:new Map,peerUsers:new Map,remoteStreams:new Map,muted:false,deafened:false,pushToTalk:false,videoEnabled:false,screenSharing:false,speakingUsers:new Set,signalCursor:new Date(Date.now()-60000).toISOString(),poll:null,roomModalOpen:false,
  async joinChannel(ch){try{const needVideo=ch.type==='VIDEO';const media=await this.getMedia(needVideo);const d=await API.call('joinVoice',{channelId:ch.id,muted:false,deafened:false,videoEnabled:needVideo,pushToTalk:false});await this.start({roomType:'VOICE',roomId:ch.id,label:ch.name,channel:ch,peers:d.peers||[],iceServers:d.iceServers,media})}catch(err){showError(err)}},
  async joinRoom(o){try{const media=await this.getMedia(false);await this.start({...o,media})}catch(err){showError(err)}},
  async getMedia(video=false){if(!navigator.mediaDevices?.getUserMedia)throw new ApiError('MEDIA_UNAVAILABLE','Voice requires HTTPS or localhost and a browser with microphone access.');return navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:video?{width:{ideal:1280},height:{ideal:720}}:false})},
  async start(o){if(this.active)await this.leave();Object.assign(this,{active:true,roomType:o.roomType,roomId:o.roomId,label:o.label||'',channel:o.channel||null,localStream:o.media,muted:false,deafened:false,pushToTalk:false,videoEnabled:o.media.getVideoTracks().length>0,screenSharing:false,signalCursor:new Date(Date.now()-5000).toISOString()});this.iceServers=o.iceServers||State.clientConfig?.iceServers||[];this.peerUsers.clear();for(const p of o.peers||[])this.peerUsers.set(p.userId,p.user||p);for(const p of o.peers||[]){if(this.roomType==='DM_CALL'||State.user.id.localeCompare(p.userId)<0)await this.ensurePeer(p.userId,true)}clearInterval(this.poll);this.poll=setInterval(()=>this.pollSignals(),State.clientConfig?.polling?.rtcSignalsMs||CONFIG.defaultRtcPollMs);this.installPtt();renderAll();this.openRoom();toast(`Connected to ${this.label}.`,'success')},
  async ensurePeer(userId,offer=false){if(userId===State.user.id)return null;let rec=this.peers.get(userId);if(rec)return rec.pc;const pc=new RTCPeerConnection({iceServers:this.iceServers||[]});rec={pc,makingOffer:false,ignoreOffer:false};this.peers.set(userId,rec);for(const track of this.localStream?.getTracks()||[])pc.addTrack(track,this.localStream);pc.onicecandidate=e=>{if(e.candidate)this.sendSignal(userId,'ICE',e.candidate.toJSON()).catch(()=>{})};pc.ontrack=e=>{const stream=e.streams[0]||new MediaStream([e.track]);this.remoteStreams.set(userId,stream);this.attachRemote(userId,stream);this.renderRoomIfOpen()};pc.onconnectionstatechange=()=>{if(['failed','closed','disconnected'].includes(pc.connectionState)){if(pc.connectionState==='failed')pc.restartIce?.();if(pc.connectionState==='closed'){this.peers.delete(userId);this.remoteStreams.delete(userId)}this.renderRoomIfOpen()}};pc.onnegotiationneeded=async()=>{try{rec.makingOffer=true;await pc.setLocalDescription();await this.sendSignal(userId,'OFFER',pc.localDescription)}catch(e){console.warn(e)}finally{rec.makingOffer=false}};if(offer){try{rec.makingOffer=true;await pc.setLocalDescription(await pc.createOffer());await this.sendSignal(userId,'OFFER',pc.localDescription)}finally{rec.makingOffer=false}}return pc},
  async sendSignal(toUserId,signalType,signal){return API.call('sendRtcSignal',{roomType:this.roomType,roomId:this.roomId,toUserId,signalType,signal})},
  async pollSignals(){if(!this.active)return;try{const d=await API.call('pollRtcSignals',{roomType:this.roomType,roomId:this.roomId,after:this.signalCursor});this.signalCursor=d.cursor||new Date().toISOString();if(d.iceServers?.length)this.iceServers=d.iceServers;const ack=[];for(const s of d.signals||[]){await this.handleSignal(s);ack.push(s.id)}if(ack.length)await API.call('ackRtcSignals',{signalIds:ack})}catch(err){if(!['BUSY','NETWORK_ERROR'].includes(err.code))console.warn(err)}},
  async handleSignal(s){this.peerUsers.set(s.fromUserId,this.peerUsers.get(s.fromUserId)||State.members.find(m=>m.userId===s.fromUserId)?.user||{id:s.fromUserId,username:'Player'});const pc=await this.ensurePeer(s.fromUserId,false);const rec=this.peers.get(s.fromUserId);try{if(s.signalType==='OFFER'){const collision=rec.makingOffer||pc.signalingState!=='stable';rec.ignoreOffer=State.user.id.localeCompare(s.fromUserId)<0&&collision;if(rec.ignoreOffer)return;await pc.setRemoteDescription(s.signal);await pc.setLocalDescription(await pc.createAnswer());await this.sendSignal(s.fromUserId,'ANSWER',pc.localDescription)}else if(s.signalType==='ANSWER'){if(pc.signalingState==='have-local-offer')await pc.setRemoteDescription(s.signal)}else if(s.signalType==='ICE'){try{await pc.addIceCandidate(s.signal)}catch(e){if(!rec.ignoreOffer)throw e}}else if(s.signalType==='HANGUP'){pc.close();this.peers.delete(s.fromUserId);this.remoteStreams.delete(s.fromUserId);this.renderRoomIfOpen()}}catch(e){console.warn('RTC signal error',e)}},
  attachRemote(userId,stream){let audio=document.querySelector(`audio[data-remote="${CSS.escape(userId)}"]`);if(!audio){audio=document.createElement('audio');audio.autoplay=true;audio.dataset.remote=userId;$('#remote-media').append(audio)}audio.srcObject=stream;audio.muted=this.deafened},
  async updateBackend(patch){if(this.roomType==='VOICE')try{await API.call('updateVoice',{channelId:this.roomId,...patch})}catch(err){showError(err)}},
  async toggleMute(){this.muted=!this.muted;for(const t of this.localStream?.getAudioTracks()||[])t.enabled=!this.muted&&!this.pushToTalk;await this.updateBackend({muted:this.muted});renderSidebar();this.renderRoomIfOpen()},
  async toggleDeafen(){this.deafened=!this.deafened;$$('audio[data-remote]').forEach(a=>a.muted=this.deafened);await this.updateBackend({deafened:this.deafened});renderSidebar();this.renderRoomIfOpen()},
  async togglePtt(){this.pushToTalk=!this.pushToTalk;if(this.pushToTalk){for(const t of this.localStream?.getAudioTracks()||[])t.enabled=false}else{for(const t of this.localStream?.getAudioTracks()||[])t.enabled=!this.muted}await this.updateBackend({pushToTalk:this.pushToTalk});renderSidebar();this.renderRoomIfOpen()},
  installPtt(){if(this._pttInstalled)return;this._pttInstalled=true;window.addEventListener('keydown',e=>{if(!this.active||!this.pushToTalk||e.code!=='Space'||['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))return;e.preventDefault();for(const t of this.localStream?.getAudioTracks()||[])t.enabled=!this.muted});window.addEventListener('keyup',e=>{if(!this.active||!this.pushToTalk||e.code!=='Space')return;for(const t of this.localStream?.getAudioTracks()||[])t.enabled=false})},
  async toggleVideo(){if(!this.active)return;if(this.videoEnabled){const tracks=this.localStream.getVideoTracks();tracks.forEach(t=>{t.stop();this.localStream.removeTrack(t);for(const {pc} of this.peers.values()){const sender=pc.getSenders().find(s=>s.track===t);if(sender)sender.replaceTrack(null)}});this.videoEnabled=false}else{const s=await navigator.mediaDevices.getUserMedia({video:{width:{ideal:1280},height:{ideal:720}},audio:false});const t=s.getVideoTracks()[0];this.localStream.addTrack(t);for(const {pc} of this.peers.values()){const sender=pc.getSenders().find(x=>x.track?.kind==='video');sender?await sender.replaceTrack(t):pc.addTrack(t,this.localStream)}this.videoEnabled=true}await this.updateBackend({videoEnabled:this.videoEnabled});renderSidebar();this.renderRoomIfOpen()},
  async toggleScreen(){if(!this.active)return;if(this.screenSharing){this.screenStream?.getTracks().forEach(t=>t.stop());this.screenStream=null;const cam=this.localStream.getVideoTracks()[0]||null;for(const {pc} of this.peers.values()){const sender=pc.getSenders().find(s=>s.track?.kind==='video'||(!s.track&&s.__screen));if(sender)await sender.replaceTrack(cam)}this.screenSharing=false}else{if(!navigator.mediaDevices?.getDisplayMedia)throw new ApiError('SCREEN_UNAVAILABLE','Screen sharing is not supported in this browser.');this.screenStream=await navigator.mediaDevices.getDisplayMedia({video:true,audio:true});const t=this.screenStream.getVideoTracks()[0];t.onended=()=>{if(this.screenSharing)this.toggleScreen().catch(showError)};for(const {pc} of this.peers.values()){let sender=pc.getSenders().find(s=>s.track?.kind==='video');if(!sender){sender=pc.addTrack(t,this.screenStream);sender.__screen=true}else await sender.replaceTrack(t)}this.screenSharing=true}await this.updateBackend({screenSharing:this.screenSharing});renderSidebar();this.renderRoomIfOpen()},
  reconcile(states){if(!this.active||this.roomType!=='VOICE')return;const peers=states.filter(v=>v.channelId===this.roomId&&v.userId!==State.user.id);for(const p of peers){this.peerUsers.set(p.userId,p.user);if(!this.peers.has(p.userId)&&State.user.id.localeCompare(p.userId)<0)this.ensurePeer(p.userId,true)}const ids=new Set(peers.map(p=>p.userId));for(const [id,rec] of this.peers){if(!ids.has(id)){rec.pc.close();this.peers.delete(id);this.remoteStreams.delete(id)}}this.renderRoomIfOpen()},
  openRoom(){this.roomModalOpen=true;this.renderRoom()},
  renderRoomIfOpen(){if(this.roomModalOpen&&$('#voice-room-grid'))this.renderRoom()},
  renderRoom(){const localUser=State.user;const participants=[{id:State.user.id,user:localUser,stream:this.localStream,local:true},...[...this.peerUsers.entries()].map(([id,user])=>({id,user,stream:this.remoteStreams.get(id),local:false}))];modal(this.label||'Voice room',`${!window.isSecureContext?'<div class="secure-note">Microphone, camera, and screen sharing require HTTPS or localhost.</div>':''}<div class="video-grid" id="voice-room-grid">${participants.map(p=>this.tileHtml(p)).join('')}</div>`,`<button class="secondary ${this.muted?'danger':''}" data-room-mute>${this.muted?'Unmute':'Mute'}</button><button class="secondary" data-room-deafen>${this.deafened?'Undeafen':'Deafen'}</button><button class="secondary" data-room-video>${this.videoEnabled?'Camera off':'Camera on'}</button><button class="secondary" data-room-screen>${this.screenSharing?'Stop share':'Share screen'}</button><button class="danger" data-room-leave>Disconnect</button>`,true);const root=$('#modal-root');root.dataset.voiceRoom='true';root.querySelector('[data-room-mute]').onclick=()=>this.toggleMute();root.querySelector('[data-room-deafen]').onclick=()=>this.toggleDeafen();root.querySelector('[data-room-video]').onclick=()=>this.toggleVideo().catch(showError);root.querySelector('[data-room-screen]').onclick=()=>this.toggleScreen().catch(showError);root.querySelector('[data-room-leave]').onclick=()=>this.leave();requestAnimationFrame(()=>{for(const p of participants){const v=document.querySelector(`video[data-stream-id="${CSS.escape(p.id)}"]`);if(v&&p.stream){v.srcObject=p.stream;v.muted=p.local;v.play().catch(()=>{})}}})},
  tileHtml(p){const hasVideo=p.stream?.getVideoTracks().some(t=>t.readyState==='live');return `<div class="video-tile">${hasVideo?`<video autoplay playsinline data-stream-id="${esc(p.id)}"></video>`:`<div class="placeholder">${avatarHtml(p.user)}<div style="margin-top:8px">${esc(p.user?.username||'Player')}</div></div>`}<span class="label">${esc(p.user?.username||'Player')}${p.local?' (you)':''}</span></div>`},
  async leave(){if(!this.active)return;for(const id of this.peers.keys())this.sendSignal(id,'HANGUP',{}).catch(()=>{});clearInterval(this.poll);for(const {pc} of this.peers.values())pc.close();this.peers.clear();this.remoteStreams.clear();this.localStream?.getTracks().forEach(t=>t.stop());this.screenStream?.getTracks().forEach(t=>t.stop());try{if(this.roomType==='VOICE')await API.call('leaveVoice',{channelId:this.roomId});else if(this.roomType==='DM_CALL')await API.call('leaveCall',{dmId:this.roomId})}catch{}Object.assign(this,{active:false,roomType:'',roomId:'',channel:null,label:'',localStream:null,screenStream:null,muted:false,deafened:false,pushToTalk:false,videoEnabled:false,screenSharing:false,roomModalOpen:false});$('#remote-media').innerHTML='';closeModal();await refreshVoiceStates();renderAll();toast('Voice disconnected.')}
};
window.addEventListener('beforeunload',()=>{if(Voice.active){navigator.sendBeacon?.(CONFIG.backendUrl,new Blob([JSON.stringify({action:Voice.roomType==='VOICE'?'leaveVoice':'leaveCall',token:State.token,channelId:Voice.roomId,dmId:Voice.roomId})],{type:'text/plain;charset=utf-8'}))}});
